[2단계 - DB 복제와 캐시] 켬미(김경미) 미션 제출합니다.
woowacourse/java-coupon pull request #102
Opened 2024-10-28 04:29 UTC by kyum-q

안녕하세요 잉크 ~!
이번 미션이 캐시인줄 모르고 1단계에서 캐시를 사용해서 별로 수정사항이 없네요 ~!
이번에 저번 미션에서 했던 도메인 로직 테스트 추가했습니다 ~!

2024-10-29 08:25 UTC, yechop requested changes
안녕하세요 켬미!
1단게에서 캐싱을 잘 해놓으셔서 2단계 캐싱에 대한 리뷰는 드릴게 별로 없네요
코멘트 드린 요구사항의 조건이나 기능들 추가해주세요!

2024-10-29 08:25 UTC, yechop commented on src/main/java/coupon/member/domain/MemberCoupon.java
>      private LocalDateTime expiresAt;
회원 쿠폰 요구사항의 발급일시가 빠져있네요!

2024-10-29 08:25 UTC, yechop commented on src/main/java/coupon/member/service/MemberCouponService.java
> +    }
기능 요구사항 
- 한 명의 회원은 동일한 쿠폰을 사용한 쿠폰을 포함하여 최대 5장까지 발급할 수 있다.

요구사항 기능을 추가해주세요

2024-10-29 08:25 UTC, yechop commented on src/main/java/coupon/member/domain/MemberCoupon.java
> +    public MemberCoupon(Member member, CouponEntity couponEntity) {
2. 회원의 쿠폰 목록 조회 기능 구현
[미션 설명](https://techcourse.woowahan.com/s/Cjiz6fNL/lt/R6TAnPXF)에 있는 것처럼 쿠폰과 회원에게 발급된 쿠폰의 저장소가 분리될 예정이므로, 두 테이블을 조인할 수 없다.

기능 요구사항 2번을 확인해주세요.
쿠폰과 회원에게 발급된 쿠폰의 저장소는 분리해야 합니다!

2024-10-29 08:25 UTC, yechop commented on src/test/java/coupon/coupon/domain/IssuePeriodTest.java
> +class IssuePeriodTest {
시작일은 종료일보다 이전이어야 한다. 시작일과 종료일이 같다면, 해당 일에만 발급할 수 있는 쿠폰이 된다.
시작일 00:00:00.000000 부터 발급할 수 있다.
종료일 23:59:59.999999 까지 발급할 수 있다.
요구사항의 소수점 6자리도 반영해주세요

저는 쿠폰 엔티티에서 @Column(columnDefinition = "DATETIME(6)") 으로 설정해주었습니다.
다양한 방법이 있을듯 하네요!

2024-10-29 08:25 UTC, yechop commented on src/main/java/coupon/member/repository/MemberCouponRepository.java
> +@Repository
bean 등록이 되지 않고있어요
DataSourceConfig 의 @EnableJpaRepositories를 확인해보시겠어요?

2024-10-29 08:25 UTC, yechop commented on src/test/java/coupon/coupon/domain/CouponNameTest.java
> +    }
@NullAndEmptySource 에 대해 알아봅시다!

2024-11-01 04:52 UTC, kyum-q commented on src/test/java/coupon/coupon/domain/CouponNameTest.java
> +    }
허걱 Null과 Empty를 한번에 테스트할 수 있군요 ! 처음 알았습니다 좋은 정보 감사합니다!

2024-11-01 07:35 UTC, kyum-q commented
잉크 반영이 늦었네요 ~!
급하게 하다보니 요구사항을 제대로 확인 못했네요 ㅜㅜ
리뷰 반영하여 수정하였습니다 감사합니다 !

2024-11-01 07:52 UTC, yechop approved these changes
리뷰 반영하시느라 고생 많으셨습니다!! 
2단계 approve 할게요

2024-11-01 07:53 UTC, merged