Step2
woowacourse/java-coupon pull request #104
Opened 2024-10-28 05:17 UTC by JINU-CHANG

2024-10-31 08:35 UTC, jhon3242 requested changes
안녕하세요 제제! 🍊
리뷰가 좀 늦었네요 죄송해요!!

캐시 관련되어서 제제의 생각이 궁금한 부분에 대해 커멘트 몇 개 달아보았습니다!!
그리고 레디스 관련 테스트가 통과가 안되는데 확인 부탁드릴게요!!
얼마 남지 않은 레벨4 화이팅입니다!!

2024-10-31 08:35 UTC, jhon3242 commented on src/main/java/coupon/domain/DiscountAmount.java
> +    private static final int DISCOUNT_RATE_MAX_AMOUNT = 20;
👍

2024-10-31 08:35 UTC, jhon3242 commented on src/test/java/coupon/service/CouponServiceTest.java
> +
![image](https://github.com/user-attachments/assets/47f9a2f8-3248-48cd-800c-091f10f4ad84)
Redis에 연결이 안되어서 테스트가 실패하네요 🥲

2024-10-31 08:35 UTC, jhon3242 commented on src/main/java/coupon/config/RedisConfig.java
> +                .disableCachingNullValues();
질문) 따로 TTL 설정은 안해주셨네용 특별한 이유가 있을까요??

2024-10-31 08:35 UTC, jhon3242 commented on src/main/java/coupon/config/RedisConfig.java
> +    }
질문) 어떤 이유에서 ObjectMapper를 따로 설정해주셨나요??

2024-10-31 08:35 UTC, jhon3242 commented on src/main/java/coupon/service/UserCouponService.java
> +    }
질문) 쿠폰을 발급할 수 있는 멤버들에게 전부 쿠폰을 발급해주는 방식으로 구현하셨군요! 어떤 시나리오를 가정하고 이렇게 구현하셨는지 궁금하네요!

2024-10-31 08:35 UTC, jhon3242 commented on src/main/java/coupon/service/CouponService.java
>                  .orElseGet(() -> couponWriteService.getCoupon(couponId));
질문) 서비스를 통해 캐싱된 쿠폰을 가져오는 방식이군요! 캐싱을 활용할 때 고려되어야할 사항이 데이터의 정합성이라고 생각하는데 이에 대해 제제의 생각이 궁금해요!
![image](https://github.com/user-attachments/assets/8eba34c8-5a8e-46f1-bde0-49e1db151732)

이전의 수업에서 보았던 상황과 같이 먼저 데이터를 수정하는 쓰레드의 캐싱이 늦게 발생한다면 어떻게 해결할 수 있을까요?? 제제의 생각이 궁금합니다!!

2024-11-01 04:26 UTC, JINU-CHANG commented on src/main/java/coupon/config/RedisConfig.java
> +    }
Redis에 LocalDateTime을 캐싱 또는 적재를 하였을 때 발생하는 에러를 해결하기 위해 설정했습니다.

```
org.springframework.data.redis.serializer.SerializationException: Could not write JSON: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
```

2024-11-01 04:30 UTC, JINU-CHANG commented on src/main/java/coupon/service/UserCouponService.java
> +    }
쿠폰 발급이라고하니 쇼핑몰에서 발급해주는 쿠폰이 가장 먼저 떠올랐는데요, 경험삼으로는 특정 등급이나 기간에 맞춰 모든 회원에게 쿠폰을 발급했던 것으로 기억해요! 특정 시즌이 되어 모든 회원에게 할인 쿠폰을 지급한다는 시나리오를 가정하고 구현했습니다 😄

2024-11-01 04:38 UTC, JINU-CHANG commented on src/main/java/coupon/service/CouponService.java
>                  .orElseGet(() -> couponWriteService.getCoupon(couponId));
`@CachePut` 어노테이션을 활용해 update 메서드 실행 시 이미 캐시된 값이 있다면 업데이트하도록 구현할 것 같습니다!

```java
@CachePut(value = "coupons", key = "#couponId")
    public Coupon updateCoupon(Long couponId) {
       ...
}

```

2024-11-01 05:14 UTC, JINU-CHANG commented on src/test/java/coupon/service/CouponServiceTest.java
> +
DM으로 따로 말씀드렸어요!

2024-11-01 05:48 UTC, JINU-CHANG commented on src/main/java/coupon/config/RedisConfig.java
> +                .disableCachingNullValues();
당시에는 조금 더 공부해보고 적용해야겠다고 생각한 부분이었는데,
아직까지도 기준이 확실하지는 않지만 생각정리한 부분까지 말씀드려볼게요 :)

Redis의 TTL 설정은 지정된 시간이 지나면 자동으로 키를 삭제합니다. 쿠폰의 특성을 고려해봤을 때 한 번 발급되면 거의 변경사항이 없을 것이라고 생각됩니다. 그러면 `쿠폰의 유효시간동안 캐싱해도 괜찮을까?` 라는 생각이 먼저 들었는데요, 중간에 쿠폰 내용이 업데이트되어도 아래 설명드린 `@CachePut` 어노테이션을 활용하면 변경사항을 적용할 수 있어 문제가 없다고 생각했습니다. 하지만 도메인마다 다르겠지만, 제가 생각한 쇼핑몰에서의 쿠폰 특성을 생각해보면 유효기간이 1주일 혹은 1달까지도 존재합니다. 아무래도 그 기간동안 적절한 초기화가 이루어지지 않으면 예상치못한 데이터 불일치 문제가 발생할 수도 있겠다는 생각이 들었습니다. 따라서 지금 TTL을 설정해야 한다면 하루르 기준으로 선택할 것 같습니다. 하루동안은 캐싱의 이점을 누리면서 적절한 주기로 초기화를 해주어 예상치 못한 문제를 피할 수 있을 거라고 생각합니다!

2024-11-01 06:12 UTC, jhon3242 approved these changes
안녕하세요 제제! 🍊
마지막 미션 수고 많았어요!!
레벨 5 잘 마무리하고 제제가 원하는 일들 다 이루었으면 좋겠네요!!
화이팅입니다!! 🔥🔥

2024-11-01 06:12 UTC, jhon3242 commented on src/main/java/coupon/config/RedisConfig.java
> +                .disableCachingNullValues();
제제만의 명확한 생각이 있네요! 좋아요!! 👍 
만약 TTL를 설정한다면 얼마나 유효한 캐싱을 하는지 판단하기 위해선 상황이 필요할 것 같아요!! 제제의 말대로 쿠폰을 변경하는 작업은 거의 없을 것 같다는 생가기 드네요! 만약 변경이 일어난다면 캐시되고 있는 쿠폰을 지워줄 수도 있을 것 같네요! 

추가로 TTL을 짧게 유지하고 조회가 자주 발생한다면 TTI를 설정하는 방식도 고려해볼 수 있을 것 같네요!

2024-11-01 06:12 UTC, jhon3242 commented on src/main/java/coupon/service/UserCouponService.java
> +    }
좋네요!! 생일자 쿠폰 등이 제제가 말한 시나리오가 되겠네요!! 
저는 이벤트로 쿠폰 발급 버튼을 누른 사용자에게 쿠폰을 발급한다는 시나리오를 가정했는데 서로 다른 시나리오여서 그런지 재미있게 느껴지네요 ㅎㅎ

2024-11-01 06:13 UTC, merged