[2단계 - DB 복제와 캐시] 카피(김상혁) 미션 제출합니다.
woowacourse/java-coupon pull request #107
Opened 2024-10-28 05:49 UTC by tkdgur0906

안녕하세요 초코칩!
2단계 미션 구현완료해서 제출합니다~

캐시는 도커로 제공된 redis를 사용했습니다.
쿠폰 id를 key로 Cacheable 어노테이션을 사용해서 쿠폰을 간단하게 캐싱시켰습니다!

잘부탁드립니다~

2024-10-30 10:24 UTC, Chocochip101 requested changes
안녕하세요, 카피!

관련해서 리뷰 남겼습니다 :) 확인해주세요!

cf. init.sql도 변경된 스키마 추가해주세요~

2024-10-30 10:24 UTC, Chocochip101 commented on src/main/java/coupon/config/RedisConfig.java
> +                .entryTtl(Duration.ofMinutes(3L));
3분으로 TTL을 정하신 이유가 있나요?

2024-10-30 10:24 UTC, Chocochip101 commented on src/main/java/coupon/service/CouponService.java
> +    @Cacheable(key = "#id", value = "coupon")
캐싱 구현 방법이 여러가지가 있을 것 같아요. 
`@Cacheable`, `@RedisHash`, RedisTemplate 방법도 있는데, 해당 방식을 선택한 이유가 있나요?

2024-10-30 10:24 UTC, Chocochip101 commented on src/main/java/coupon/service/MemberCouponService.java
> +        if (existCouponCount >= 5) {
1. 쿠폰 발급 수량이 변경되면, 코드도 변경되어야 하나요?
2. 모든 쿠폰 발급 수량은 동일해야하나요?

2024-10-30 10:24 UTC, Chocochip101 commented on src/main/java/coupon/CouponApplication.java
> +@EnableCaching
SpringBootTest에서만 테스트가 가능하겠군요?

2024-11-01 05:48 UTC, tkdgur0906 commented on src/main/java/coupon/config/RedisConfig.java
> +                .entryTtl(Duration.ofMinutes(3L));
해당 설정은 큰 이유 없이 해 놓았던 것 같네요!
지금 다시 생각해보니 쿠폰의 정책에 대한 명확한 설명이 없어서 그것이 정해지고 난 후에 TTL을 적용해볼 수 있을 것 같습니다.
지금은 제거했습니다!

2024-11-01 06:33 UTC, tkdgur0906 commented on src/main/java/coupon/service/CouponService.java
> +    @Cacheable(key = "#id", value = "coupon")
RedisTemplate을 사용할 만큼 복잡한 작업이 아니라 제외하였고,
`@RedisHash`를 사용하는 방법도 가능하지만 `@Cacheable`을 사용하는게 개인적으로 간단하게 구현가능하다 생각해 선택했습니다!

2024-11-01 06:39 UTC, tkdgur0906 commented on src/main/java/coupon/service/MemberCouponService.java
> +        if (existCouponCount >= 5) {
현재는 5개에서 6개로 변경될 경우 코드의 수정이 필요합니다!
확장 여지를 고려해봤을 떄 외부에서 최대 쿠폰의 개수를 입력받게 해서 쿠폰별로 달라질 수 있는 쿠폰 발급 수량을 유연하게 처리할 수 있을 것 같습니다!

2024-11-01 06:42 UTC, Chocochip101 commented on src/main/java/coupon/service/CouponService.java
> +    @Cacheable(key = "#id", value = "coupon")
나중에 Cacheable을 사용했을 때 어떤 단점이 있을지 찾아보면 좋을 것 같아요!

2024-11-01 06:49 UTC, Chocochip101 commented on src/main/java/coupon/service/MemberCouponService.java
> +        if (existCouponCount >= 5) {
다음에 디비에 저장하는 설계도 고려해보는 것도 좋을 것 같아요.

2024-11-01 06:56 UTC, Chocochip101 approved these changes
바쁘신 와중에 리뷰하시느라 수고했어요!

2024-11-01 06:57 UTC, merged