[2단계 - DB 복제와 캐시] 릴리(최윤서) 미션 제출합니다.
woowacourse/java-coupon pull request #116
Opened 2024-10-28 07:00 UTC by lilychoibb

안녕하세요 우주~
마지막 미션이네요.
리뷰 잘 부탁드립니다 :)

2024-10-28 15:23 UTC, tsulocalize requested changes
안녕하세요 릴리!
마지막까지 함께 힘내봐요~

2024-10-28 15:23 UTC, tsulocalize commented on src/main/java/coupon/application/MemberCouponReadService.java
> +                .toList();
쿠폰 정보를 캐시에서 가져와볼까요?

2024-10-28 15:23 UTC, tsulocalize commented on src/main/java/coupon/application/MemberCouponWriteService.java
> +        Coupon coupon = memberCoupon.getCoupon();
> 쿠폰과 회원에게 발급된 쿠폰의 저장소가 분리될 예정

Coupon과 MemberCoupon 사이 연관관계를 끊어줘도 좋을 것 같네요!

2024-10-28 15:23 UTC, tsulocalize commented on src/main/java/coupon/domain/membercoupon/MemberCoupon.java
> +    }
👍👍👍

2024-10-31 11:03 UTC, lilychoibb commented on src/main/java/coupon/application/MemberCouponReadService.java
> +                .toList();
오 넵 그렇게 할 수 있겠네요 수정했습니다!

2024-10-31 11:26 UTC, lilychoibb commented on src/main/java/coupon/application/MemberCouponWriteService.java
> +        Coupon coupon = memberCoupon.getCoupon();
수정했습니다!

2024-10-31 12:14 UTC, tsulocalize approved these changes
이번 단계는 이정도면 충분할 것 같네요!
나중에 다중 서버 상황이라면 어떻게 구현할지도 생각해보면 좋을 것 같아요!
그동안 수고 많으셨어요~

2024-10-31 12:14 UTC, merged