[2단계 - DB 복제와 캐시] 몰리(김지민) 미션 제출합니다.
woowacourse/java-coupon pull request #119
Opened 2024-10-28 07:34 UTC by jminkkk

안녕하세요 제우스~

### 고려한 점
쿠폰이라는 도메인에 대해 읽기 작업이 더 월등할 것이라고 예상했어요.

- 조회가 매우 빈번하고 동일한 쿠폰에 대해 반복적으로 조회할 일이 많다고 판단
- 또한 하나의 쿠폰은 발행 가능할 경우 최소 한번 이상은 조회될 가능성이 높으며, 이미 발생한 가능한 쿠폰에 대해 수정될 일은 현저히 낮다고 생각

결론적으로, Read-Through + Write-Through 조합을 사용, 쿠폰은 글로벌 캐시인 레디스를 사용하여 구현하였습니다!

이번 단계도 잘 부탁드려요~!

2024-10-29 09:57 UTC, zeus6768 requested changes
안녕하세요 몰리~!!

요즘 갑작스런 채용 일정으로 바쁜데도 미션 구현하느라 고생 많았어요 😭😭😭

---

DB 초기화를 위한 DDL을 추가해주시면 제가 테스트하기 편할 것 같아요~

일단 이번에는 제가 수동으로 DB를 만들어서 테스트했어요 ㅎㅎ

도메인보다는 미션의 주제인 캐시와 관련된 코멘트를 남겼어요. 

코멘트로 질문과 의견 남겼으니 확인해주세요~~

추가적으로, 

다음의 테스트 실패를 해결해주세요.  

![스크린샷 2024-10-29 오후 5 34 38](https://github.com/user-attachments/assets/ea0fbc0a-d36f-4d8b-b334-600d65a7a8c5)

2024-10-29 09:57 UTC, zeus6768 commented on docs/STEP2.md
> +- [ ] 쿠폰 캐싱
😄
```suggestion
- [x] 쿠폰 캐싱
```

2024-10-29 09:57 UTC, zeus6768 commented on build.gradle
> +    implementation 'com.github.ben-manes.caffeine:caffeine'
위 두 의존성은 어떤 기능을 위해 필요한가요?

의존성을 추가하지 않을 경우 어떤 문제가 있나요?

2024-10-29 09:57 UTC, zeus6768 commented on docs/STEP2.md
> +따라서 Read-Through + Write-Through 조합을 사용, 쿠폰은 글로벌 캐시인 레디스를 사용한다.
고민과 결론을 자세히 작성해줬네요. 

몰리의 분석과 결론에 저는 충분히 납득됐어요. 

덕분에 저도 많이 배워가요  ☺️

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/coupon/application/CouponService.java
> +    @CachePut(value = CACHE_NAME, key = "#result.id", unless = "#result == null")
create() 메서드의 결과가 null이 될 수 있나요? 

어떤 상황을 고려해서 추가한 조건인지 알고 싶어요 😄

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/coupon/application/CouponService.java
> +    @Cacheable(value = CACHE_NAME, key = "#id")
`@Transactional(readOnly = true)`이 없다면 캐시와 writer DB만 사용할 것 같은데, 몰리가 그것을 의도한 게 맞을까요?

그렇다면 reader DB는 쿠폰 조회에서 사용하지 않는 건가요?

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/coupon/domain/CouponRepository.java
> +    List<Coupon> findAllByIdIn(List<Long> couponId);
현재 이 메서드는 사용되지 않는 것 같은데, 삭제하면 어떨까요?

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/coupon/domain/CouponRepository.java
>      Optional<Coupon> findById(Long id);
`findById`는 Spring Data JPA에서 기본적으로 제공해주는 메서드인데, 명시적으로 선언한 이유가 무엇인가요?

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/infrastructure/cache/redis/RedisCacheConfig.java
> +    }
ObjectMapper를 생성하는 코드에 중복이 있는 것 같아요.

빈으로 등록되는 ObjectMapper에 activateDefaultTyping 속성을 추가하고, 그렇게 생성된 ObjectMapper만 사용하면 어떨까요?

몰리의 생각이 궁금해요~!

2024-10-29 09:57 UTC, zeus6768 commented on src/main/java/coupon/membercoupon/application/MemberCouponService.java
> +    }
Map 대신 일급컬렉션 형태의 객체를 만들면 코드 가독성이 개선될 것 같은데 몰리는 어떻게 생각하나요?

또, createMemberCoupon 직후 이 메서드를 실행하면 복제지연 문제가 있을 것 같은데, 해결하지 않아도 괜찮을까요? 😄

2024-10-29 09:57 UTC, zeus6768 commented on src/test/java/coupon/coupon/application/CouponServiceTest.java
> +@Transactional
`@Transactional` 애너테이션이 클래스에 붙어있을 때, 테스트 메서드에서 정상적으로 캐시에 접근하나요?

2024-10-29 09:57 UTC, zeus6768 commented on src/test/java/coupon/membercoupon/application/MemberCouponServiceTest.java
> +    }
> 성능을 위해 쿠폰을 캐싱하고, 회원의 쿠폰 목록 조회 시 쿠폰 정보는 캐시를 통해 조회하도록 수정한다.

위와 같은 LMS 요구사항이 있었는데요. 

현재 이 메서드는 쿠폰 정보를 캐시를 통해 조회하는지 궁금해요~!

2024-10-29 17:55 UTC, jminkkk commented on src/main/java/coupon/infrastructure/cache/redis/RedisCacheConfig.java
> +    }
BasicPolymorphicTypeValidator 를 추가하면서 중복 코드를 확인하지 못했네요 🥲
너무 좋습니다 🔥

2024-10-29 18:32 UTC, jminkkk commented on build.gradle
> +    implementation 'com.github.ben-manes.caffeine:caffeine'
> implementation 'com.github.ben-manes.caffeine:caffeine'

앗,,, 사실 처음 설계를 구상할 때는 로컬 캐시(자주 조회되는 캐시)와 글로벌 캐시(쿠폰 캐시)를 같이 사용하는 방식을 생각했는데요.

그래서 도전까지는 했었는데 도저히 시간관계상 불가능해서 하다가 롤백을 했었습니다...ㅎㅎ
그 흔적들이 여기저기에 남아있네요 큽 🥲

caffeine은 자바 진영에서 사용하는 로컬 캐시 라이브러리입니다. 
성능 부분에서 우수하다고 알고 있어서 사용을 고려했었습니다!

> implementation 'org.springframework.boot:spring-boot-starter-cache'

스프링에서 제공하는 캐시 추상화 라이브러리입니다.
현재 저는 레디스로 CacheManager를 등록하고 @Cacheable 같은 추상화된 어노테이션을 사용하여 구현했는데요.

해당 라이브러리 덕분에 특정 캐시에 종속되지 않고 어노테이션을 기반으로 로직에 캐시를 적용할 수 있었습니다!

만약 해당 라이브러리가 없다면 RedisTemplate 같은 구현체에 직접 접근하여 로직을 작성해야 한다고 알고 있습니다. 
그렇게 되면 비즈니스 로직과 부가 기능이 섞이기 때문에 유지보수에 바람직하지는 않는 것 같다고 생각이 드네용...

2024-10-29 18:34 UTC, jminkkk commented on src/main/java/coupon/coupon/domain/CouponRepository.java
>      Optional<Coupon> findById(Long id);
이 부분도 로컬 캐시를 동시에 적용하다가 남겨진 코드네요 🥲
제거하겠슴다!

2024-10-29 19:09 UTC, jminkkk commented on src/main/java/coupon/coupon/application/CouponService.java
> +    @CachePut(value = CACHE_NAME, key = "#result.id", unless = "#result == null")
헉 getCoupon() 에서 조회할 때 아래와 같은 에러 때문에 추가했었어요. 그런데 create에 있네요... 정신이 많이 없었나봅니다... 🥲

`java.lang.IllegalArgumentException: Null key returned for cache operation [Builder[public coupon.coupon.domain.Coupon coupon.coupon.application.CouponService.getCoupon(java.lang.Long)] caches=[coupon] | key='#id' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false']. If you are using named parameters, ensure that the compiler uses the '-parameters' flag.`

2024-11-01 01:25 UTC, jminkkk commented on src/main/java/coupon/coupon/application/CouponService.java
> +    @Cacheable(value = CACHE_NAME, key = "#id")
오!
캐시에서 읽기 때문에 @Transactional(readOnly = true)를 제거하였는데요. 
캐시 미스인 경우 Read DB에서 가져오도록 변경하는 것이 적절할 것 같네요!
감사합니다 👍👍

2024-11-01 07:46 UTC, jminkkk commented on src/test/java/coupon/membercoupon/application/MemberCouponServiceTest.java
> +    }
MemberCoupon은 캐시를 사용하지 않고, Coupon은 캐시를 사용하도록 구현하였습니다.
관련 테스트 코드 추가하였으니 확인해주시면 감사하겠습니다!

2024-11-01 07:49 UTC, jminkkk commented on src/main/java/coupon/membercoupon/application/MemberCouponService.java
> +    }
> Map 대신 일급컬렉션 형태의 객체를 만들면 코드 가독성이 개선될 것 같은데 몰리는 어떻게 생각하나요?

그러네요! 일급 컬렉션 생각을 못했어요 😁
반영하였습니다!

> 또, createMemberCoupon 직후 이 메서드를 실행하면 복제지연 문제가 있을 것 같은데, 해결하지 않아도 괜찮을까요? 😄

회원 쿠폰 조회에 대해 테스트를 하다가 바로 이 상황을 마주쳤는데요!

각각의 쿠폰은 여러 회원에게 사용되어 캐시를 하는 것이 효율적이라고 생각했는데요.

특정 회원의 쿠폰은 발급 후 해당 회원이 아예 조회를 안할 수도 있을 수도 있는 등 리소스 낭비같다고 느꼈어요. 
또 5개만 가능하다는 제한도 있구요! 크게 필요성을 느끼지 못해서 Write DB에서 조회하도록 하였습니다 😁

2024-11-01 07:58 UTC, jminkkk commented on src/test/java/coupon/coupon/application/CouponServiceTest.java
> +@Transactional
저는 내부 캐시 테스트에서 레포지토리 메서드를 호출하지 않는 것을 확인하고 캐시에 접근 한다고 생각했어요!

2024-11-01 08:02 UTC, zeus6768 approved these changes
리뷰 반영하느라 고생 많았어요 몰리~

수료를 위해 여기서 머지할게요. 

지난 10개월 간 고생 많았어요. 레벨5도 응원할게요 🔥

2024-11-01 08:02 UTC, merged