[2단계 - DB 복제와 캐시] 시소(신지송) 미션 제출합니다.
woowacourse/java-coupon pull request #123
Opened 2024-10-28 07:44 UTC by shin-jisong

안녕하세요 커찬!
마지막 단계네요 (3단계는... 진행할 수 있을까 고민 중에 있습니다)

저는 `Look Aside` 캐싱 전략을 사용했어요!
한번 조회한 것은 여러 번 조회할 가능성이 높다고 판단하였습니다

TTL의 경우, 7일로 설정해 두었는데요
쿠폰의 만료 기한을 7일로 설정한 것을 고려하여 설정한 기한입니다

또한 지난 번 리뷰 중에 이야기를 나누었던 `TrasactionWriterExcecutor`를 도입하여 Service 계층 분리를 줄여보고자 하였어요
다만 해당 로직을 적용하려면 Service 단에 있는 어노테이션을 제거해야 되기 때문에 아쉽게 느껴져요
Service 단에 있는 어노테이션을 제거하더라도 READ와 WRITE가 잘 분리되어 요청이 가는 것을 확인했어요
JPA에서 ReadOnly를 자동적으로 설정해 주는 것 같은데 관련 공식 문서를 아직 찾지 못하여서 혹시나 찾게 되면 공유 바랍니다

잘 부탁드려요!

2024-10-28 08:52 UTC, leegwichan requested changes
안녕하세요 시소! 커찬입니다! (:시소미소:)
이렇게 우테코에서의 마지막 리뷰가 미션이 끝나는 것이 아쉽네요 😭 그래도 연극조에서 유일하게 같이 페어를 못해본 시소와 같이 할 수 있어 즐겁습니다~

제 리뷰에서 2가지를 강조했습니다. 해당 주제 위주로 피드백 반영 부탁드릴께요~
- TTL 기간을 7일로 설정해도 문제없는가?
- Redis 저장 시에 Serializable을 이용해도 문제없는가?

추가로 제 리뷰에 의문이 있거나 이상한 점이 있다면 언제든지 DM 주세요!

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/Member.java
MemberCoupon과 Coupon을 따로 관리하는데, Member도 따로 관리할 것 같아서 저는 따로 구현 안했는데...
시소 대단하자널 👍

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/MemberCoupon.java
> +        this.expiredAt = issuedAt.plusDays(7).withHour(23).withMinute(59).withSecond(59).withNano(999999000);
뒤를 000으로 하신 이유 무엇인가요?

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/MemberCoupon.java
> +        this.expiredAt = issuedAt.plusDays(7).withHour(23).withMinute(59).withSecond(59).withNano(999999000);
```suggestion
        this.expiredAt = LocalDateTime.of(issuedAt.toLocalDate().plusDays(7), LocalTime.MAX);
```

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/MemberCoupon.java
> +        this.expiredAt = issuedAt.plusDays(7).withHour(23).withMinute(59).withSecond(59).withNano(999999000);
> 회원에게 발급된 쿠폰은 발급일 포함 7일 동안 사용 가능하다. 만료 일의 23:59:59.999999 까지 사용할 수 있다.

발급일 포함이면 6일 추가가 맞겠죠?

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/global/CacheManagerConfig.java
> +
Cache의 TTL이 7일이군요...

> 개발팀에서는 쿠폰 서비스의 고가용성을 위해 두 대의 DB를 사용하기로 했다. 서비스와 데이터의 특성을 고려했을 때 쿠폰과 회원에게 발급된 쿠폰의 양이 다를 것으로 예상되어, 두 데이터의 저장소를 분리하는 작업을 계획 중이다.

이 두 테이블을 분리를 고려할 정도면 다루고자 하는 쿠폰의 양이 상당할 것으로 생각되요. 7일 동안 딱 한 번 조회되는 쿠폰의 정보까지 모두 메모리에 올리면 메모리의 비용이 상당할 것이라고 생각되는데, 시소의 생각은 어떤가요?

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/global/CacheManagerConfig.java
> +
시소가 바쁜 것 같으니 제 의견까지 덧붙일께요. 지금 TTL(time to live)을 사용하셨는데, TTI(time to idle)을 사용하는 건 어떨까요?

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/Coupon.java
혹시 Redis에서 어떻게 조회되는지 확인해 보셨나요?

```text
�� sr coupon.domain.Coupon�Y�o
M^ I discountAmountI minimumOrderAmountL categoryt Lcoupon/domain/Category;L endDatet Ljava/time/LocalDateTime;L idt Ljava/lang/Long;L namet Ljava/lang/String;L 	startDateq ~ xp  �  '~r coupon.domain.Category          xr java.lang.Enum          xpt FOODsr 
java.time.Ser�]��"H�  xpw
  �$�xsr java.lang.Long;��̏#� J valuexr java.lang.Number������  xp       t 쿠폰sq ~ 
w
  �
$�x
```
이런 형식으로 저장하고 조회가 됩니다~ 물론 정상 작동하니까 크게 상관 없다고 생각하실 수 있어요.
[자바 직렬화의 단점](https://velog.io/@whitebear/%EC%9E%90%EB%B0%94-%EC%A7%81%EB%A0%AC%ED%99%94-%ED%99%95%EC%8B%A4%ED%9E%88-%EC%95%8C%EA%B3%A0-%EA%B0%80%EA%B8%B0#%EC%9E%90%EB%B0%94-%EC%A7%81%EB%A0%AC%ED%99%94%EC%9D%98-%EB%8B%A8%EC%A0%90-%EC%9C%A0%EC%9D%98%ED%95%A0-%EC%A0%90)
무중단 배포를 하고 Coupon의 필드들이 바뀔 수 있는 상황에서 Serializable은 고려해야 할 상황이 많을 것 같아요. (역직렬화 실패 고려, serialVersionUID 고려 등등...) 그리고 Redis에서 값을 조회해서 보더라고 실제 어떤 값이 있는지 알 수 없구요.

직렬화 대신 다른 좋은 방법이 없을까요?

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/Coupon.java
여기에서 코멘트를 끝내고 싶었으나, 시소도 바쁠까 싶어 첨언합니다.
Redis에서 JSON 형태로 저장하고 조회할 수 있습니다! 이것을 적용하시면 더 좋다고 생각합니다~
이외의 시소만의 방법이 있다면 적용하시고 알려주셔도 좋을 것 같아요!

```java
@Configuration
public class RedisConfig {

    @Bean
    public RedisTemplate<String, Coupon> redisTemplate(RedisConnectionFactory connectionFactory) {
        GenericJackson2JsonRedisSerializer genericJackson2JsonRedisSerializer =
                new GenericJackson2JsonRedisSerializer(objectMapper());

        RedisTemplate<String, Coupon> template = new RedisTemplate<>();
        template.setConnectionFactory(connectionFactory);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(genericJackson2JsonRedisSerializer);
        return template;
    }

    ...
}
```

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/domain/MemberCoupon.java
> +import jakarta.persistence.*;
와일드카드 빼주세요...

2024-10-28 08:52 UTC, leegwichan commented on src/main/java/coupon/service/CouponService.java
>      }
transactionWriterExecutor를 적용하신 것 확인했습니다 👍

2024-10-30 04:31 UTC, shin-jisong commented on src/main/java/coupon/domain/Member.java
어리둥절하지만 감사하자널 👍

2024-10-30 04:35 UTC, shin-jisong commented on src/main/java/coupon/domain/MemberCoupon.java
> +        this.expiredAt = issuedAt.plusDays(7).withHour(23).withMinute(59).withSecond(59).withNano(999999000);
조건에서 언급한 것이 999999 나노초였는데, 나노초의 경우 999999999까지 있으므로 이를 반영하기 위해 해당 부분을 000으로 처리하였습니다. LocalTime.MAX의 경우에는 나노초가 999999999까지 반영될 것 같아 도입하지 않았어요. 사실 해당 부분이 최대 시간을 지정하라는 건지, 6자리까지만 허용하라는 건지 명확하게 뜻하는 바가 궁금하였지만 현재로서는 조건을 최대한으로 구현하는 걸 목표로하였습니다. 강의에서 배운 내용을 적용해보고 싶기도 했습니다. 🤔

 그리고 6일의 경우에는 계산 실수였어요! 반영하였습니다.

2024-10-30 04:43 UTC, shin-jisong commented on src/main/java/coupon/global/CacheManagerConfig.java
> +
커찬은 생성된 것의 유효날짜와 마지막 사용 후 유효날짜 중 마지막 사용 후 유효 날짜를 사용하는 것을 제안해 주셨네요!

제가 TTL을 7일로 설정한 것은 쿠폰이라는 도메인의 특성 때문이었어요.
해당 로직은 MemberCoupon이 있고, Coupon 도메인이 따로 있어서 각 멤버마다의 쿠폰이 발급되고 그 쿠폰은 재사용될 확률이 굉장히 높다 생각했어요.
특정 이벤트마다의 쿠폰이 발급될 것을 생각하면 개수가 많지도 않을 거라 생각하고요.

예를 들어, 크리스마스 할인 쿠폰이 발급될 때에 모든 고객에게 발급되더라도 MemberCoupon과 Coupon은 다르므로 캐시에 저장되는 쿠폰은 하나일 거라고 생각합니다. 
레디스가 기본적으로 사용 가능한 용량을 봤을 때에 하나의 서비스에서 한번에 진행하는 이벤트의 수는 충분히 수용할 거라고 판단하였어요!

다만 7일이라는 기간은 멤버 쿠폰에 한정된 조건이며 TTI를 사용하면 해당 쿠폰을 더 이상 사용하지 않을 때 조금 더 빨리 만료시킬 수 있다는 이점이 있을 것 같아요.
쿠폰의 사용 기한이 23:59:59:999999라는 점을 감안해 하루로 설정해 보겠습니다.

2024-10-30 05:04 UTC, shin-jisong commented on src/main/java/coupon/domain/Coupon.java
사실 어떤 구글링을 해도 `org.springframework.data.redis.serializer.SerializationException: Cannot serialize`이 문제를 해결하지 못해서 눈물을 머금고 해당 부분을 추가했는데요
커찬의 PR을 보고 objectMapper까지 정의해 주었으나 여전히 실패하네요...

혹시 커찬은 왜 이러는지 아시나요? 아무리 파도 모르겠어서 도움을 요청합니다

2024-10-30 05:22 UTC, shin-jisong commented on src/main/java/coupon/domain/MemberCoupon.java
> +import jakarta.persistence.*;
반영하였습니다!

2024-10-30 06:01 UTC, leegwichan commented on src/main/java/coupon/domain/Coupon.java
1. CashManagerConfig에서.... serializeKeysWith, serializeValuesWith를 설정하고... JavaTimeModule을 ObjectMapper로 만들어서... serializeValuesWith에 같이 넣어주면...
2. json 변환에 성공한다면, Coupon의 Serializable은 제거해도 될 것 같아요!

2024-10-30 06:03 UTC, leegwichan requested changes
도움 요청하신 부분에 답변 달았습니다!
그리고 전반적인 파일에 사용하지 않는 import문 제거해주세요!

(더 많은 도움이 필요하시다면 DM 보내주세요!)

2024-10-31 01:56 UTC, shin-jisong commented on src/main/java/coupon/domain/Coupon.java
감사합니다~! 삽 들고 파봐야겠어요 
반영하였습니다 👍

2024-10-31 02:28 UTC, leeseongsil approved these changes
:시소미소:

제 리뷰 잘 반영해 주신 것 확인했습니다! 그래서 미션은 이만 마치도록 하겠습니다.
레벨 1 이후 자주 이야기 못 나눴는데 미션을 통해 이야기 할 수 있어 좋았습니다! 레벨 5 되서 여유있을 때 같이 만나서 놀았으면 좋겠네요! 시소 고생 많았고 남은 것들 잘 마무리하세요!

2024-10-31 02:29 UTC, leegwichan approved these changes
:시소미소:

제 리뷰 잘 반영해 주신 것 확인했습니다! 그래서 미션은 이만 마치도록 하겠습니다.
레벨 1 이후 자주 이야기 못 나눴는데 미션을 통해 이야기 할 수 있어 좋았습니다! 레벨 5 되서 여유있을 때 같이 만나서 놀았으면 좋겠네요! 시소 고생 많았고 남은 것들 잘 마무리하세요!

2024-10-31 02:29 UTC, merged