[1단계 - DB 복제와 캐시] 릴리(최윤서) 미션 제출합니다.
woowacourse/java-coupon pull request #13
Opened 2024-10-17 15:37 UTC by lilychoibb

안녕하세요 우주 :)
처음 인사드리는 것 같네요!

저는 복제지연을 캐싱을 통해 해결해보았습니다.
redis 를 쓰기엔 애플리케이션 규모가 작다고 생각해서, 스프링이 제공하는 캐싱을 사용했습니다.

스키마는 init 에 두어서 `docker compose up` 만 실행시키셔도 아마 작동할 거에요! 

그럼 리뷰 잘 부탁드립니다
감사합니다 🤗

2024-10-19 05:25 UTC, tsulocalize requested changes
안녕하세요 릴리!
마지막 미션이니 함께 힘내보자구요~

2024-10-19 05:25 UTC, tsulocalize commented on src/main/java/coupon/application/CouponWriteService.java
> +}
서버 내 캐시로 복제 지연을 해결하신 것 같은데, 서버가 2대 이상이어도 괜찮나요?
예를 들어 서버 A에서 쿠폰을 생성하고, 서버 B에서 쿠폰을 조회하는 경우에는 어떻게 동작하나요?

2024-10-19 05:25 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +    ) {
Entity 생성자에 id가 들어있네요?

2024-10-19 05:25 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private BigDecimal value;
소수점이 아닌 정수를 표현할 때도 `BigDecimal`을 쓴 이유가 있을까요?

2024-10-19 05:25 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
발급 가능한지 여부를 도메인을 통해 알 수 있으면 좋을 것 같네요!

2024-10-19 05:25 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    }
>발급 기간
시작일은 종료일보다 이전이어야 한다. 시작일과 종료일이 같다면, 해당 일에만 발급할 수 있는 쿠폰이 된다.

2024-10-19 05:28 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    private void validate(LocalDateTime startDate, LocalDateTime endDate) {
발급 기간
시작일은 종료일보다 이전이어야 한다. 시작일과 종료일이 같다면, 해당 일에만 발급할 수 있는 쿠폰이 된다.

2024-10-21 04:23 UTC, lilychoibb commented on src/main/java/coupon/application/CouponWriteService.java
> +}
서버가 1대라고 생각하고 구현해서 2대 이상일 땐 레디스를 써야하지 않을까요? 
필요하면 레디스로 갈아탈 것 같습니다!

2024-10-21 04:27 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +    ) {
현재는 테스트 할 때만 필요해서 부생성자를 만들어두지 않았는데, 추가해두는게 좋을까요?

2024-10-21 04:50 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private BigDecimal value;
아무래도 돈을 다루는 도메인이다보니 정밀도와 정확한 계산이 필요하다고 생각해서 `BigDecimal` 을 사용했습니다!

2024-10-21 05:04 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
그렇긴 한데 1단계에서 필요한 메서드인지 잘 모르겠습니다..! 우주는 어떻게 생각하시나요?

2024-10-21 05:11 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    private void validate(LocalDateTime startDate, LocalDateTime endDate) {
혹시 빠트린 검증이 있을까요? 제가 보기엔 우주가 말씀하신 부분은 검증이 되고 있는 것 같아보이는데 조금 더 자세히 말씀해주실 수 있나요?

2024-10-21 09:10 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    private void validate(LocalDateTime startDate, LocalDateTime endDate) {
시작일과 종료일이 같은 경우도 있습니다!

2024-10-21 09:16 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
발급 가능 여부에 대한 제한 사항도 1단계 요구 사항이라고 생각합니다!

2024-10-21 09:17 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +    ) {
저는 테스트에서도 id를 포함한 생성자를 사용하지 않는 편이긴 합니다!
릴리만의 코드 스타일이 있다면 그렇게 가시죠~

2024-10-21 09:18 UTC, tsulocalize requested changes
리뷰 답변 추가해드렸습니다~

2024-10-21 10:13 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
저는 미션 요구사항의 제한 사항은 validation 을 통해 구현이 되었다고 생각했는데요!
혹시 우주는 발급 가능 여부에 대한 메서드가 따로 필요한 것이 필수라고 생각하신 이유가 어떤 것인지 궁금합니다!

(2단계에선 추가될 것 같네요~)

2024-10-21 10:17 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    private void validate(LocalDateTime startDate, LocalDateTime endDate) {
시작일과 종료일이 같은 경우에도 LocalDateTime 이라 time 까지 비교하지 않을까요? 

- 시작일과 종료일의 날짜와 시간이 완전히 동일하면 예외가 발생하지 않는다.
- 시작일과 종료일의 날짜가 같고 시간이 다르지만 시작일이 종료일보다 빠르면 예외가 발생하지 않는다.
- 날짜는 같지만 종료일의 시간이 시작일보다 빠르면 예외가 발생한다.

2024-10-21 12:07 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
저는 `DB 복제와 캐시`에 작성된 모든 제약조건이 코드로 나타나야 된다고 생각했습니다!

2024-10-21 12:10 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +    private void validate(LocalDateTime startDate, LocalDateTime endDate) {
에궁... 제가 LocalDateTime인 줄 모르고 잘못 작성했네요!

2024-10-21 12:10 UTC, tsulocalize requested changes
추가 답변 남겼습니다!

2024-10-21 12:50 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
> 저는 미션 요구사항의 제한 사항은 validation 을 통해 구현이 되었다고 생각했는데요!

저는 모든 제약조건이 구현이 되었다고 생각해서 말씀드린 부분이었습니다 :) 
그래서 우주가 생각했을 때 어떤 제약 조건이 어떻게 코드로 나타나지 않았는지를 좀 더 구체적인 이유가 듣고 싶어요. 
어차피 2단계에서 추가될 메서드이기도 하고 추가하는데 리소스도 많이 들지 않기에 우주의 의견대로 따라가도 되지만, 
우주가 왜 1단계에서 필수적인 메서드라고 생각하셨는지 좀 더 자세하게 설명해주셔야 납득이 될 것 같아요.
저도 제가 생각하기에 당장 필요하지 않은 메서드를 두는게 맞나 싶기도 하고요.

2024-10-25 15:29 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
> 어차피 2단계에서 추가될 메서드이기도 하고

저는 2단계에 해당 제약 조건이 구현될 거라는 확신을 가질 수 없습니다. 릴리가 아닌 그 어떤 개발자가 와도 똑같이 대답할 것 같네요.

> 당장 필요하지 않은 메서드를 두는게 맞나

1. 아래는 1단계 미션 완료 기준입니다.
프로그래밍 요구사항을 지키고, 기능 요구사항을 모두 구현한다.
2. 아래는 기능 요구사항입니다.
쿠폰의 제약조건은 [DB 복제와 캐시](https://techcourse.woowahan.com/s/Cjiz6fNL/lt/R6TAnPXF) 페이지의 미션 설명을 참고한다.
3. 아래는 [DB 복제와 캐시] 페이지 일부 발췌입니다.
발급 기간
시작일은 종료일보다 이전이어야 한다. 시작일과 종료일이 같다면, 해당 일에만 발급할 수 있는 쿠폰이 된다.
시작일 00:00:00.000000 부터 발급할 수 있다.
종료일 23:59:59.999999 까지 발급할 수 있다.

저는 [DB 복제와 캐시]에 적혀있는 요구사항이 코드에 반영되어있지 않는 한 미션 완료 기준을 준수했는지 확신할 수 없고, 나중에 구현하겠다는 것은 코드 리뷰어
에게 이중 부담을 안겨준다고 생각합니다. 

저와 다른 생각/의견을 가질 수 있는 점은 충분히 존중합니다만, 저로서는 요구사항이 반영되지 않은 코드(혹은 해당 검증이 필요할 때 작성하겠다는 코드)를 approve할 수 없다는 점을 알려드립니다.

p.s. 저는 현직자도 아닌 릴리와 같은 크루입니다. 의견에 대해 논의하고 싶으시면 함께 얘기해보시죠!(같은 선릉 캠퍼스인 걸로 알고 있습니다)

2024-10-25 15:31 UTC, tsulocalize requested changes
추가 답변 남겨드렸습니다!

2024-10-25 18:14 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
> 그래서 우주가 생각했을 때 어떤 제약 조건이 어떻게 코드로 나타나지 않았는지를 좀 더 구체적인 이유가 듣고 싶어요.

저는 어차피 나중에 구현될 메서드이니 구현을 안 하겠다는 의미가 아니라 우주가 왜 그렇게 생각했는지를 이해하고 코드를 작성하고 싶다는 의미였는데 당황스럽네요. 부담까지 안겨드렸다고 하니 오해하신 부분이 있는 것 같아서 말씀드립니다.

계속해서 우주의 의견을 여쭤봤는데도 추가 설명을 해주신 건 4일 뒤이고, 추가 설명에서도 위의 제약 조건이 왜 '발급 가능한지 여부에 대한 메서드'로 나타나야 하는지에 대한 설명은 없네요.

>  시작일 00:00:00.000000 부터 발급할 수 있다.
> 종료일 23:59:59.999999 까지 발급할 수 있다.

해당 제약 조건이 반영이 안되어있다고 생각하시는 것 같은데, 저는 위에서 '저는 모든 제약조건이 구현이 되었다고 생각해서 말씀드린 부분이었습니다 :)' 라고 말씀드렸는데요. 
제약 조건을 못 봐서 그런게 아니라 위의 제약 조건이 왜 우주가 주장하는 메서드로 구현이 되어야 하는지에 대한 설득이 필요했습니다. 

어쨌든 미션 마감 기한도 촉박해졌고, 리뷰어가 필요하다고 생각하시니 추가하고 다시 요청드리겠습니다~

2024-10-26 05:05 UTC, tsulocalize commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
당황스럽게 할 의도는 전혀 아니였는데 죄송스럽네요...

제가 주장하는 내용은 `쿠폰 객체의 생성`과 `쿠폰 발급`이 다른 정의를 가진다 에서 출발합니다.
객체 생성 시점에서는 IssuablePeriod를 통해 알 수 있지만, 이미 생성된 객체를 사용(발급)하는 시점에서는 사용(발급) 제약조건에 대해 알지 못할 가능성도 있다고 생각했습니다.

추가로 MemberCoupon 객체에 대한 제약 조건 또한, 생성 시점이 아닌 사용 시점에 대한 제약 조건이라고 생각합니다!
다만 기한이 얼마 남지 않아 우선 Approve&Merge 할 테니 위 부분도 꼭 코드로 나타날 수 있도록 요청드립니다!

2024-10-26 05:06 UTC, merged

2024-10-28 04:23 UTC, lilychoibb commented on src/main/java/coupon/domain/coupon/Coupon.java
> +public class Coupon {
넵 감사합니다 :)
다만 처음부터 말씀해주셨으면 좀 더 많은 이야기를 나눠볼 수 있었을 것 같네요!