[2단계 - DB 복제와 캐시] 아톰(이하늘) 미션 제출합니다.
woowacourse/java-coupon pull request #135
Opened 2024-10-28 08:34 UTC by le2sky

2024-10-29 07:05 UTC, hyxrxn requested changes
아톰 안녕하세요~~ 아토입니다!

캐싱 요구사항 만족하신 것 확인했습니다!
구현해주신 부분 중 궁금한 점 몇 가지 코멘트 남겼어요.

그런데 미션 수료 조건 중에

> 내가 선택한 캐시 전략과 구현, 이러한 선택을 한 이유를 설명할 수 있다.

가 있는데요,
왜 이런 전략을 택하셨는지 description이나 comment에 설명해주셔야 이 부분에 대해 좀 더 얘기해볼 수 있겠어요!

그리고 도커를 아예 지웠다가 다시 띄우고 어플리케이션을 실행해보아도
![image](https://github.com/user-attachments/assets/b54fc24b-7922-42f8-b51e-79ed0a609854)
이런 오류가 뜨며 실행이 되지 않습니다 ㅠㅠ
마찬가지의 이유로 서비스 테스트도 돌아가지 않네요.
이 부분도 확인 한 번 부탁드려요!

2024-10-29 07:05 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
`MemberCouponMapper` 인터페이스는 `membercoupon` 패키지에 있고,
그 구현체는 `coupon` 패키지에 있는 이유가 뭔가요??

2024-10-29 07:05 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
1. create 메서드 호출되어 쿠폰 writer에 저장
2. issue 메서드 호출되어 쿠폰 발급 요청
3. issue 메서드 내부에서 getCoupon시 writer에서 읽어옴
4. getMemberCoupons 메서드 호출되어 회원의 쿠폰 목록 조회 요청
5. getMemberCoupons 메서드 내부에서 getReadCoupon시 reader에서 읽어옴
6. 이제서야 1번에서 저장된 쿠폰 reader로 복제

의 순서로 일이 일어난다면 3번 과정에서 사용자는 분명히 쿠폰을 발급 받았는데, 5번 과정에서 조회하려고 하니 존재하지 않는 쿠폰이라고 예외가 터질 것 같은데요!
이를 해결해아 하지 않을까요....?!

2024-10-29 07:05 UTC, hyxrxn commented on src/test/java/coupon/domain/MemberCouponTest.java
> +    }
> 만료 일의 23:59:59.999999 까지 사용할 수 있다.

`use` 메서드 같은 것을 만들어 사용하려 하는 상황을 구체적으로 만드는 것은 어떨까요?
`expiresAt`까지 사용이 가능한 것인지, 아니면 `expiresAt`부터 사용할 수 없는 것인지 헷갈려요.

그리고 대부분의 경우 전자의 의미로 사용하는 것 같은데,
만약 아톰도 전자의 의미를 담았다면 `plusDays(6)`을 해야 할 것 같아요!
발급일 포함 7일이면 날짜로는 6일 후까지 사용이 가능한 것이니까요~~~

2024-10-29 11:38 UTC, le2sky commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
Copon에서 MemberCoupon을 생성하는데 필요한 데이터를 가지고 있으니 MemberCoupon의 생성 책임은 Coupon에 있다고 판단했습니다. 그러면 Coupon에서 MemberCoupon을 알고 있는게 타당하고, MemberCoupon은 Coupon을 몰라야하는게 느슨한 설계라고 생각했습니다. (하지만, 웹 프로젝트를 수행할 때는 이렇게 엄격하게 지키는 것이 비효율적이기도 합니다. 왜냐하면, 의존성을 단방향으로 유지하기 위해서 희생해야하는 것들이 있기 때문입니다.)

다만, 현재는 MemberCoupon과 Coupon은 데이터베이스를 분리하니 연관관계 매핑을 사용할 수 없는 상황입니다.
따라서 약한 참조를 가지고 연관을 맺도록 구현을 해야하니, 자연스럽게 Coupon에서 MemberCoupon을 의존하게 할 수 있었습니다. 
그래서 응용 계층에서도 일관성있게 Coupon 영역에서 MemberCoupon 영역으로 흐르도록 의존 방향을 관리했습니다.
쉽게 말하자면, 아래와 같이 추상화를 사용해 의존성을 역전 시켰습니다.

```
Coupon[MemberCouponMapperImpl] -> MemberCoupon[MemberCouponMapper <- MemberCouponService]  
```

 제가 아직 경험이 부족해서 모르는 부분도 많습니다. 어색한 부분이 있다면 추가 피드백 부탁 드립니다!

2024-10-29 11:52 UTC, le2sky commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
호오.. 생각해보지 않은 케이스인데 성장에 큰 도움이 됐습니다. 감사합니다. 😅

말씀주신 케이스는 어떤 케이스인지 더욱 구체적인 상황을 생각해봐야할 것 같아요. 왜냐하면, MemberCoupon 조차도 복제지연이 발생하니, 사용자는 예외가 아닌 빈 리스트를 받을 것 같습니다. 그러면 빈 리스트를 줘야하나? 아니면 실시간으로 사용자의 쿠폰을 Writer에서 가져와 보여줘야하나?가 고민되네요.

이 부분은 아토의 의견을 더욱 듣고 반영하고 싶어요. 
말씀주신 케이스는 복제지연이 MemberCoupon은 1초, Coupon은 2초가 수행되는 경우에 발생할 수 있을 것 같은데요. 이런 경우를 가정하고 피드백을 주신걸까요?

2024-10-29 11:54 UTC, le2sky commented on src/test/java/coupon/domain/MemberCouponTest.java
> +    }
놓치고 있던 부분인데 감사합니다! 현재 use 메서드를 추가하고 plusDays를 6으로 변경해봤어요. 
어색한 부분이 있다면 추가 피드백 부탁 드립니다!

2024-10-29 12:26 UTC, le2sky commented
> 왜 이런 전략을 택하셨는지 description이나 comment에 설명해주셔야 이 부분에 대해 좀 더 얘기해볼 수 있겠어요!

감사합니다. 제가 정신이없어서 놓쳤었네요. 🥲
캐시 look up 이후 cache miss인 경우 서버에서 직접 db 값을 캐싱해주는 look aside(lazy loading) 읽기 전략을 사용했어요.
read through 읽기 전략과 비교했을 때 redis의 장애가 애플리케이션의 장애로 번지는 게 상대적으로 덜 할 것 같다고 생각했어요. (Redis와 MySQL로 구현하는 방법을 알고 계신가요?) 그리고 Cacheable 어노테이션을 사용하기 편리하기도 했습니다.
그리고 해당 방식은 대규모 캐시 미스가 발생하는 경우, 캐시 부하가 db에 붙어 위험할 수도 있다는 것이 단점인 걸로 알고 있습니다.
제가 놓치고 있는 부분이 있다면, 피드백 부탁 드립니다. 그리고 별개로 아토는 어떤 전략을 어떤 이유로 사용하셨는지도 궁금합니다!

2024-10-29 12:32 UTC, le2sky commented
> 이런 오류가 뜨며 실행이 되지 않습니다 ㅠㅠ
마찬가지의 이유로 서비스 테스트도 돌아가지 않네요.
이 부분도 확인 한 번 부탁드려요!

제 컴퓨터에서는 잘 돌아가는데, 어떤 이유인지 잘 모르겠네요..  😥
혹시 다음과 같이 컨테이너를 정리 해보셨을까요?

1. 현재 docker compose를 다운
2. 프로젝트 경로 docker/data 디렉터리를 제거
3. docker 디렉터리 내부에서 `docker compose up -d --build` 실행

2024-10-30 07:08 UTC, hyxrxn requested changes
안녕하세요 아톰~~ 아토입니다!!

DM으로 말씀드렸던 테스트 관련 내용을 포함해 추가 코멘트 몇 가지 남겼습니다!
거의 마무리된 것 같아요~~~
데이터 파일을 정리하고 다시 띄워야 했군요... 몰랐네요 😅

마지막까지 화이팅입니다!

2024-10-30 07:08 UTC, hyxrxn commented on src/main/java/coupon/domain/MemberCoupon.java
>      }
저는 지금은 발급하자마자 사용할 수 있지만 언젠가 사용 기간이 다르게 설정될 수 있다고 생각했거든요!
그래서 이 메서드에서는 사용 기간 시작보다 현재 날짜가 이후인지도 검증해야 한다고 생각했어요.
메서드 이름의 의미상요!

실제로 AllArgsConstructor도 열려있고, `issuedAt`이 미래로 설정되어 객체가 생길 수도 있으니까요...!!
(물론... `issuedAt`이 사용 기간 시작을 의미하는 게 아니긴 한데... 아무튼요!!)
여기에 대한 아톰의 생각이 궁금해요~~~

2024-10-30 07:08 UTC, hyxrxn commented on src/test/java/coupon/domain/MemberCouponTest.java
> +        assertThat(actual).isEqualTo(afterSixDay.getDayOfMonth());
애초부터 date로 하면 좀 더 편할 것 같은데 이렇게 구현하신 이유가 무엇인가요???
뭔가 이유가 분명 있을 것 같은데... 궁금해서요!!

`getDayOfMonth()`도 `actual`은 미리 하고 `expected`는 메서드 안에서 한것도 이유가 궁금해요.
둘 다 미리 하든지, 둘 다 안에서 하든지 맞춰야 덜 헷갈릴 것 같아서요!

2024-10-30 07:08 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
그렇다면 언젠가 `MemberCoupon`을 생성할 때 `Member`의 정보도 필요하다면 어떻게 하실건가요???
저는 그런 상황에는 `membercoupon` 패키지에 둘 수밖에 없지 않을까 싶고, 
그렇다면 다른 상황에서도 `membercoupon` 패키지에 두어야 하지 않을까 생각해요!

2024-10-30 07:08 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
지금은 복제지연의 원인을 우리가 명확하게 알지만, 실제로는 다양한 이유로 발생할 수 있잖아요!
그러니까 특정 이유로 아톰이 말씀하신 MemberCoupon은 1초, Coupon은 2초가 지연되는 현상도 생길 수 있다고 가정해야 하지 않을까 생각했어요~

2024-10-30 07:08 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
이 메서드의 동작은 따로 테스트하지 않아도 괜찮을까요?
캐시가 의도한대로 잘 동작하는지, 혹시 휴먼에러로 config를 잘못 작성하지는 않았을지...

2024-10-30 07:10 UTC, hyxrxn reviewed
제 정책과 구현은 이렇습니다!
pr description에서 긁어왔어요... ㅎㅎ

> 예전 쿠폰은 이미 사용했을 가능성이 크고, 최근 발급한 쿠폰은 아직 가지고 있을 가능성이 크다고 생각했습니다.
그래서 사용자별로 가지고 있는 쿠폰이 비슷할 것이라 생각해 최근에 조회된 쿠폰을 캐시했습니다.
기본적으로 쿠폰의 종류가 다양하지 않을 것 같아 캐시된 개수는 일단 100개로 설정했고,
이후 히트한 비율을 파악해 비율이 너무 낮다면 개수를 늘리는 방식으로 수정하려 합니다!
> 
> 또한 서버에 따로 가정이 없어 이것도 가장 간단하게 한대라고 생각했습니다.
그래서 인메모리 캐시로도 충분하다고 보았습니다.
> 
> 그리고 캐시 정책은 상황에 따라 변하기 쉽다고 생각했습니다.
당장 서버가 여러대가 되기만 해도 인메모리 캐시가 확 비효율적이게 바뀌니까요.
그래서 변경을 쉽게 하기 위해 인터페이스를 사용해보았습니다!
그리고 Configuration으로 빈을 생성해 주입했습니다.
캐시될 쿠폰의 개수도 설정 중 하나라고 생각해 쿠폰서비스에 두지 않고 CacheConfiguration에서 변경할 수 있도록 했습니다.

2024-11-01 06:06 UTC, le2sky commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
https://github.com/woowacourse/java-coupon/pull/135/commits/9c98afe0abbba452ec03ccbfc42b0304874636a3 에서 캐싱 테스트를 추가했습니다!

2024-11-01 06:29 UTC, le2sky commented on src/main/java/coupon/domain/MemberCoupon.java
>      }
한 번도 생각해보지 못했던 관점인데 좋은 피드백 남겨주셔서 감사합니다. 🙇🏻‍♂️
확실히 아토가 말씀주신 것처럼 issuedAt이 미래 시점으로 가는 경우도 고려해볼 필요성이 있겠네요.
조금 염려되는 부분은 issuedAt이라는 이름과는 조금 다른 의미로 사용되는 것 같아요. 가령, 관리자가 쿠폰을 관리할 때 오늘 발급된 쿠폰의 수를 찾기 위해서 issuedAt을 사용할텐데 issuedAt이 미래로 저장되는 경우(발급된 쿠폰마다 또 다르겠죠?)에는 추적하기가 어려울 것 같아요. 그래서 차라리 해당 요구사항이 등장했을 때 신규 컬럼을 추가해볼 것 같은데 아토의 생각은 어떠신가요? 제가 아토의 피드백을 오해한 부분이 있다면 추가 피드백 부탁 드립니다!

2024-11-01 06:32 UTC, le2sky commented on src/test/java/coupon/domain/MemberCouponTest.java
> +        assertThat(actual).isEqualTo(afterSixDay.getDayOfMonth());
요구사항에 발급 일시라고 써있어서 LocalDataTime을 사용했었어요. 현재는 https://github.com/woowacourse/java-coupon/pull/135/commits/3473e72ec947a129b7085bb1a7759d1f4998aa7c 커밋에서 LocalDate 타입으로 변경했습니다!그리고, 타입이 변경되어 스키마도 변경되었어요. 1단계에서 아토가 마지막에 피드백 남겨주신 부분이 떠오르더라구요. 성장에 큰 도움이 됐습니다. 감사합니다. 😀

2024-11-01 06:38 UTC, le2sky commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
현재 read에 없으면 write를 구현하도록 구현했어요~ 어색한 부분이 있다면 말씀 주세요!

2024-11-01 06:56 UTC, le2sky commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
"Copon에서 MemberCoupon을 생성하는데 필요한 데이터를 가지고 있으니 MemberCoupon의 생성 책임은 Coupon에 있다"에서 필요한 데이터는 쿠폰의 만료시간(CouponIssuableDuration)이라 생각했어요. memberCoupon은 어차피 누군가 만들어야하는데 누군가 coupon.getCouponIssuableDuration()을 수행해서 만드는 것보다 coupon이 스스로 생성해내는게 낫다고 생각했습니다.

그러면 이제 coupon에서 memberCoupon을 알게되었는데요. memberCoupon를 조회할때는 coupon의 원본 데이터를 알아야하니 coupon을 다시 의존하게 되면 양방향이라는 것을 이야기하고 싶었습니다.

말씀 주신 `그렇다면 언젠가 MemberCoupon을 생성할 때 Member의 정보도 필요하다면 어떻게 하실건가요???` 이 부분은 어떤 연관이 있는지 제가 역량이 부족하여 이해하지 못했습니다. MemberCoupon을 생성할때 id 이외에 다른 것은.. 무엇이 들어올지 잘 모르겠네요. Member가 없기도 하구요. 현재 구조가 개발에 치명적인 구조인지 아토의 의견을 공유해주시면 성장에 큰 도움이 될 것 같습니다!

2024-11-01 08:20 UTC, hyxrxn approved these changes
안녕하세요 아톰! 아토입니다~

답변과 반영사항 잘 확인했습니다.
몇가지 대화할거리가 남아 코멘트로 남겨두었습니다.
당장 꼭 반영해야 하는 사항은 아닌 것 같아 머지합니다!
이후 답글 꼭 남겨주시면 정말 좋을 것 같아요 ㅎㅎ

답변을 너무 명확하게 잘 남겨주셔서 즐거운 리뷰였습니다!
레벨 4까지 고생하셨습니다👍

2024-11-01 08:20 UTC, hyxrxn commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
저는 코드를 작성할 때 규칙과 일관성을 중요하게 생각하는 편이거든요~~
지금 이런 의사결정을 하신 근본적인 이유가 `MemberCoupon`을 생성할 때 `Coupon`의 정보(`CouponIssuableDuration`)가 필요하기 때문이라고 읽혔습니다!
그렇다면 `MemberCoupon`을 생성할 때 `Member`의 정보가 필요하다면 `member` 패키지에서 그 일을 수행할 것이라고 추측했고요.

예를 들어, 쿠폰을 생성할 때에는 멤버의 등급별 권한이 필요하고,(vip용 쿠폰... 이런 거요!) 멤버 안에 그 정보가 포함되어있다고 생각해봅시다.
그렇다면 지금의 규칙상으로는 그 구현체는 `member` 패키지에 들어가겠죠?

하지만 두 가지의 정보가 모두 포함되는 순간 지금의 규칙은 바로 깨질 것이라는 것을 말씀드리고 싶었습니다.
`member` 패키지에서 생성할 수도 없고, `coupon` 패키지에서 생성할 수도 없는 상황이 올테니까요!

그러면 이 규칙이 잘못된 규칙이 아닐까?
여러 상황에서 통용될 수 없는 것이 아닐까?
에 관한 의문에서 또 다른 상황을 가정하고 질문을 드린 것입니다!

꼭 모든 상황에서 통용될 필요가 없다고 생각한다든지,
그 때 가서 패키지 변경을 하면 된다든지...
등등의 의견 모두 좋습니다~~~

제 코멘트가 좀 길어졌네요 ㅋㅋㅋㅋㅋ ㅠㅠ
혹시나 이해가 안가시는 부분이 있으시다면 편하게 DM 주세요...!

2024-11-01 08:20 UTC, hyxrxn commented on src/main/java/coupon/domain/MemberCoupon.java
>      }
맞아요~~~ 저도 이름의 의미에 대한 아톰의 의견에 동의합니다!
그런데 생성자의 접근제한자가 열려있어 원하지 않는 `issueAt`을 가지는 상황이 온다면 이름의 역할을 다하지 못하게 되는 것 같기도 한데요,
이는 동료 개발자들이 이름을 보고 알아서 잘 구현하겠거니 믿고 넘어가야 하는 부분일까요??
`issue` 메서드를 부를 때 오늘의 날짜로 `issuedAt`이 자동으로 설정되는 부분만 열어두어야 하지 않을까 하는 부분에서 단순히 고민이 되어 물어봅니다!

`해당 요구사항이 등장했을 때 신규 컬럼을 추가` 하겠다는 의견 또한 동의합니다!

2024-11-01 08:20 UTC, hyxrxn commented on src/main/java/coupon/DataSourceRoutingSupport.java
클래스로 나뉘어져 있으니 비슷한 작동이 필요할 때 여러 곳에서 활용할 수 있겠네용

2024-11-01 08:21 UTC, merged

2024-11-01 08:32 UTC, le2sky commented on src/main/java/coupon/application/coupon/MemberCouponMapperImpl.java
아하 멤버 등급을 비유해주셔서 아토가 염려하시는 부분이 어떤 것인지도 이해했습니다.
오늘도 부족함을 깨달아버렸네요. 좋은 피드백 감사합니다. 😀

2024-11-01 08:53 UTC, le2sky commented on src/main/java/coupon/domain/MemberCoupon.java
>      }
아토가 말씀해주신 것처럼 주생성자를 다른 개발자가 잘못 사용할 여지가 있어요. 개선해본다면 제안주신대로 주생성자의 파라미터를 줄여 볼 수 있겠네요. 좋은 피드백 남겨주셔서 감사합니다. 저도 즐거운 리뷰였어요. 남은 기간도 힘내시고 항상 좋은 결과 있으시길 바랍니다! 😀