[1단계 - DB 복제와 캐시] 백호(전호건) 미션 제출합니다.
woowacourse/java-coupon pull request #17
Opened 2024-10-18 00:06 UTC by Arachneee

안녕하세요 애쉬~

처음뵙겠습니다.

### 가정
- 어플리케이션 서버는 2대 이상이다.
- 읽기, 쓰기 DB가 분리되어있다. 읽기용 DB는 2대 이상이다.
- 쿠폰 조회는 유저, 어드민 둘다 필요하다.
- 쿠폰 서비스에 대한 유저, 어드민 서버가 분리되어있지 않은 환경이다.

복제 지연 시간이 대략 2초 정도이더라고요.

### 해결 방안
1. 클라이언트가 쿠폰 생성 후 2초 뒤에 읽을 수 있게한다.
  - 북제지연이 2초가 아닐 수 있다. 정확한 복제지연 시간을 정확히 예측하기 어렵다.
2. 쿠폰 생성 후 2초 응답을 준다.
  - 응답시간이 너무 느리고 커낵션을 소모하게된다.
3. 쿠폰을 읽을 때 2초기다리고 읽는다.
  - 유저도 쿠폰을 읽어야하는데 응답시간이 너무 느려진다. 
4. 쿠폰은 쓰기 DB에서 읽는다.
  - 쓰기 DB는 읽기 DB보다 적어 트래픽이 몰릴 수 있다.
5. 쿠폰을 처음에 읽기 DB에서 읽고 없으면 쓰기 DB에서 읽는다.
  - 쿠폰이 없는 경우 쓰기 DB 조회가 계속 일어날 수 있다.
6. 쿠폰을 쓰고나면 캐시에 저장한다. 읽을 때 캐시에서 먼저 읽는다.
  - 캐시 인프라를 별도로 구축해야한다.

저는 5번 방식을 선택했습니다.

쿠폰의 생성은 어드민에서 할 수 있는 작업으로 많이 일어나는지 않습니다. 또한 쿠폰을 생성하고 바로 조회하는 경우도 어드민이 하는 경우이기 때문에 복제지연을 느끼는 사용자는 어드민으로 한정됩니다.

그래서 쿠폰이 없는데 조회를 하는 경우는 별로 없다고 판단했습니다.

2024-10-19 08:18 UTC, ashsty requested changes
안녕하세요 백호~ 처음 뵙겠습니다!
이번 미션 동안 잘 부탁드려요. ☺️

간단한 질문 몇 가지 코멘트로 남겨두었습니다.

추가적으로 요구사항에서

- 시작일 00:00:00.000000 부터 발급할 수 있다.
- 종료일 23:59:59.999999 까지 발급할 수 있다.
- 만료일의 23:59:59.999999 까지 사용할 수 있다.

위 조건들에 대한 `validation`이 없는 것 같아요. 확인 부탁드릴게요!

---

그리고 지금 `복제 지연 테스트`가 제 로컬에서는 아래 에러 메시지와 함께 실패하고 있어요.
`Application`도 똑같이 돌아가지 않네요. 확인해주시면 감사하겠습니다! 👍 

```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-10-19T16:54:00.689+09:00 ERROR 43686 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [expirationDateTime] in table [MemberCoupon]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1234) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:952) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at coupon.CouponApplication.main(CouponApplication.java:10) ~[main/:na]
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [expirationDateTime] in table [MemberCoupon]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421) ~[spring-orm-6.1.5.jar:6.1.5]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-orm-6.1.5.jar:6.1.5]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:366) ~[spring-orm-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.5.jar:6.1.5]
	... 16 common frames omitted
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [expirationDateTime] in table [MemberCoupon]

```

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/DataSourceConfig.java
> +        return DataSourceBuilder.create().type(HikariDataSource.class).build();
[질문] `type`을 지정해주셨네요!

`HikariDataSource`로 설정해주신 이유가 있을까요? 👀
백호가 생각하시는 `HikariDataSource`의 장점이 궁금해요.

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/DataSourceConfig.java
> +        Map<Object, Object> dataSourceMap = new HashMap<>();
저는 변수 이름에 `Map`과 같은 타입을 넣지 않으려고 노력하는 편이에요.

그 편이 타입 변환이 있을 때에 조금 더 유연한 대처가 가능하다고 생각하기 때문인데요.
백호는 어떻게 생각하시나요?

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/application/CouponService.java
> +    @Transactional(readOnly = true)
[질문] 

지금처럼 메서드별로 트랜잭셔널 어노테이션을 걸어주는 대신

`@Transactional(readOnly = true)` 어노테이션은 클래스 단위로 걸어주고,
`update` 메서드에만 `@Transactional`을  걸어주도록 컨벤션을 수정하더라도 지금의 복제 지연 방지 방식이 먹히나요? 
(몰라서 물어보는 거예요 ㅎ.ㅎ!)

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/domain/Coupon.java
> +    @Column(nullable = true)
`nullable=true` 옵션을 사용하셨네요! ㅇ0ㅇ

그 이유가 궁금해요. 백호는 DB에 `null` 값을 저장하는 상황에 대해 어떻게 생각하시나요? 
장단점은 어떤 것들이 있을까요?

더해서, `startDate`와 `endDate`의 경우는 `null` 여부를 추가로 체킹하고 있는데
다른 `validation`에서는 하지 않고 있는 이유도 궁금해요. 👀

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/domain/Coupon.java
> +    private static final int MAX_NAME_LENGTH = 30;
상수 분리 👍

2024-10-19 08:18 UTC, ashsty commented on src/test/java/coupon/domain/CouponTest.java
> +    @Test
`@NullAndEmptySource`로 `@ParameterizedTest`를 해봐도 좋겠네요!

2024-10-19 08:18 UTC, ashsty commented on src/test/java/coupon/domain/CouponTest.java
전체적으로 중복되는 라인이 많은 것 같아요.

해당 부분들을 한 군데 모아놓아도 좋겠네요~👍

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/domain/MemberCoupon.java
> +    @ManyToOne(fetch = LAZY, optional = false)
[질문] `LazyLoading`을 하고 있네요!
`fetch` 옵션 중 `EAGER`와 `LAZY` 중 하나를 선택해야 할 때 백호의 선택 기준이 궁금합니다. 👀

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/application/CouponService.java
> +        return replicationHelper.get(() -> couponRepository.findById(id))
지금의 `reader`에 데이터가 없는 경우 `writer`에서 조회를 수행한다는 접근 방식 자체는 상당히 좋은 것 같아요!

하지만 지금 로직으로는 그 방식을 도입하기 위해 비즈니스 로직이 변경되어야 하는 것 같네요.
기존 비즈니스 로직에는 변경 없이 위와 같은 접근 방식을 고수할 수 있는 방법은 없을까요?

(e.g. AOP)

2024-10-19 08:18 UTC, ashsty commented on src/main/java/coupon/datasource/ReplicationHelper.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
새로운 트랜잭션 열기 (`Propagation.REQUIRES_NEW`) 👍

2024-10-19 10:27 UTC, Arachneee commented on src/main/java/coupon/DataSourceConfig.java
> +        return DataSourceBuilder.create().type(HikariDataSource.class).build();
![image](https://github.com/user-attachments/assets/7520da7e-9b48-429a-aaa3-31490b38f4f4)

HikariCP의 성능이 다른 dataSource에 비해 압도적으로 좋다고 하네요.
Spring Boot에서도 HikariCP의 성능이 좋아 기본값으로 HikariCP를 선택하고 있다고 합니다.

2024-10-19 10:28 UTC, Arachneee commented on src/main/java/coupon/DataSourceConfig.java
> +        Map<Object, Object> dataSourceMap = new HashMap<>();
저도 변수명에 타입을 잘 넣지 않는 편인데 실수로 들어갔네요.
dataSources로 변경했어요!

2024-10-20 13:15 UTC, Arachneee commented on src/main/java/coupon/domain/Coupon.java
> +    @Column(nullable = true)
> nullable=true 옵션을 사용하셨네요! ㅇ0ㅇ
그 이유가 궁금해요. 백호는 DB에 null 값을 저장하는 상황에 대해 어떻게 생각하시나요?
장단점은 어떤 것들이 있을까요?

nullable = false 로 해야하는 것을 전부 잘못지정했네요 ;;

데이터 정합성을 위해서 null이 들어가는 것은 안좋다고 생각해요. 또한 null이 많으면 인덱스를 효율적으로 타지 못해서 not null을 명시하는 것이 좋다고 생각합니다.

> 더해서, startDate와 endDate의 경우는 null 여부를 추가로 체킹하고 있는데
다른 validation에서는 하지 않고 있는 이유도 궁금해요. 👀

다른 validation에서는 int 로 null이 들어올 수 없어서 null 체킹을 하지 않았습니다.

2024-10-20 13:17 UTC, Arachneee commented on src/main/java/coupon/domain/MemberCoupon.java
> +    @ManyToOne(fetch = LAZY, optional = false)
저는 보통 LAZY를 default로 사용하는 편입니다. 
EAGER를 사용하면 불필요한 쿼리가 나가는 문제 때문에 lazy loading을 사용하는 편입니다.

2024-10-20 13:30 UTC, Arachneee commented on src/test/java/coupon/domain/CouponTest.java
> +    @Test
테스트 케이스를 추가했습니다!

2024-10-20 13:30 UTC, Arachneee commented on src/test/java/coupon/domain/CouponTest.java
테스트 코드를 보완했어요

2024-10-20 13:39 UTC, Arachneee commented on src/main/java/coupon/application/CouponService.java
> +    @Transactional(readOnly = true)
넵. 해보니까 잘 됩니다.
ReplicationHelper에서 내부에서 `@Transactional(propagation = Propagation.REQUIRES_NEW)` 를 사용하기 있기 때문에 외부의 `@Transactional` 위치는 전혀 상관이 없습니다.

2024-10-20 17:19 UTC, Arachneee commented on src/main/java/coupon/application/CouponService.java
> +        return replicationHelper.get(() -> couponRepository.findById(id))
AOP를 활용할 수 도 있겠네요!
AOP를 활용해서 변경해봤습니다!

2024-10-20 17:25 UTC, Arachneee commented
안녕하세요 에쉬 리뷰 감사합니다!

> 추가적으로 요구사항에서
시작일 00:00:00.000000 부터 발급할 수 있다.
종료일 23:59:59.999999 까지 발급할 수 있다.
만료일의 23:59:59.999999 까지 사용할 수 있다.
위 조건들에 대한 validation이 없는 것 같아요. 확인 부탁드릴게요!

저는 위 조건들을 시간은 신경쓰지말고 날짜로만 관리하라고 이해했어요.
다른 특별한 검증이 필요한건가요?

2024-10-21 16:40 UTC, ashsty commented on src/main/java/coupon/domain/Coupon.java
> +    @Column(nullable = true)
`nullable=false` 옵션으로 수정되었으니 더더욱 괜찮아지겠네요! 👍

2024-10-21 16:57 UTC, ashsty requested changes
안녕하세요 백호!
피드백 모두 잘 반영된 점 확인했습니다. ☺️

남겨주신 질문에 답변 드리면서 한 번만 더 rc 드려요! 

다음 요청 때는 아마 머지할 것 같으니,
더 수정하고 싶거나 보완하고 싶은 부분이 있으시다면 변경 후 리뷰 요청 부탁 드립니다 ☺️

--- 

> 저는 위 조건들을 시간은 신경쓰지말고 날짜로만 관리하라고 이해했어요.
다른 특별한 검증이 필요한건가요?

저는 기본 `LocalDate`의 나노세컨드는 `999,999,999`까지 세는데,
미션에서는 `999,999`까지로 지정되어 있어 해당 부분도 검증되어야 하지 않나 생각했던 것 같아요. 🤔

요구사항대로라면 만료일의 999999... 초까지 들어온 요청은 처리되지만
9999999초에 들어온 요청은 거절되어야 할 것 같거든요.

백호는 어떻게 생각하시나요?

2024-10-21 16:57 UTC, ashsty commented on src/main/java/coupon/replication/ReplicationLag.java
> +public @interface ReplicationLag {
커스텀 어노테이션 👍

2024-10-22 04:28 UTC, Arachneee commented
> 요구사항대로라면 만료일의 999999... 초까지 들어온 요청은 처리되지만
9999999초에 들어온 요청은 거절되어야 할 것 같거든요.

저는 그 정도의 정확도를 요구한 것이 아니라고 생각했어요. 9999999999초 부터는 쿠폰을 발급할 수 없다고 기획할 이유가 없다고 생각해요. 
단순히 해당 날짜까지만 발급할 수 있다는 요구사항으로 이해했어요.

2024-10-22 05:42 UTC, ashsty commented
1단계 요구사항은 모두 만족한 것 같아 머지합니다~
다음 단계도 화이팅~

2024-10-22 05:42 UTC, merged