[1단계 - DB 복제와 캐시] 포케(이무송) 미션 제출합니다.
woowacourse/java-coupon pull request #20
Opened 2024-10-18 02:39 UTC by fromitive

안녕하세요 테바! 포케 입니다.

```
작성중
```

미션 잘 부탁드립니다 🙇

2024-10-19 14:59 UTC, ksk0605 requested changes
안녕하세요 포케~🥗

코드를 굉장히 깔끔하게 잘 구현하셨네요 👍

도메인 객체와 JPA entity 를 분리하고 각 값 객체들에게 도메인 로직을 위임하신 것 인상깊게 봤습니다. 

포케가 접근한 방법에 대해서 같이 이야기 하고 싶은 내용을 좀 남겨볼게요. 

> 정합성이 중요하지 않은 조회 메서드가 별도로 있기 때문에 상황에 따라 유연하게 선택할 수 있습니다.
> 

정합성이 중요하지 않은 조회 메서드는 `@Transactional(readOnly = true)` 가 있는 메서드를 말씀하시는 거겠죠? 

정합성이 중요한 상황과 아닌 상황은 어떻게 판단하나요? 그 기준은 무엇인가요? 

일반적으로 쿠폰을 생성하는 입장은 쇼핑몰에 입점한 가게의 관리자겠죠. 그리고 구매자들은 쿠폰을 사용하는 입장일 거구요. 이 가정에서 포케가 생각하는 정합성이 중요한 상황과 아닌 상황이 어떤 예시가 있을지 들어보고 싶어요. 

--- 

> 저는 특히 협업을 고려했는데요 캐시 메모리를 도입했을 때 고려해야 할 시스템들을 생각하지 않아도 되기 때문에…
> 

개발자들은 서비스 코드에 두개나 존재하는 조회 메서드의 의도를 설명하지 않고 알 수 있나요? **캐시 메모리를 도입한 시스템이 갖추어야할 시스템들을 생각하는 것**과, **두 조회 메서드 중 어느 메서드를 사용해야하는지 판단하는 것** 중 포케는 후자가 협업관점에서 덜 부담이라고 생각했다고 이해했어요.

그럼 조회 메서드에서 어떤 것을 사용해야하는지 고려하지 않아도 되도록, **조회 기능을 적절히 추상화하는 방법**을 선택하시지 않은 이유는 무엇인가요?

--- 

> 앞으로 (정합성이 중요하지 않은)조회하는 메서드가 쓰기 메서드보다 상대적으로 많이 생길 것임을 예상하고 있어 위의 방식을 선택했습니다.
> 

정합성이 중요하지 않은 조회메서드가 더 많이 쓰일 거라는 의미인가요? 그렇다면 왜 캐시를 사용하지 않았나요? 정합성이 중요할 땐 reader DB를 읽고 나머지는 캐시에서 조회하는 것도 가능할텐데말이죠! 포케가 가정한 상황을 좀 더 구체적으로 듣고 싶어요.

2024-10-19 14:59 UTC, ksk0605 commented on src/main/java/coupon/service/CouponService.java
> +
쿠폰 도메인 객체와 DB 엔티티를 분리해서 구현하셨어요. 한 가지 질문이 있는데요!

서비스 코드에 왜 두 객체가 모두 드러나야 했나요? **두 객체를 분리하겠다는 말은 도메인 로직을 수행하는 역할과 DB 접근을 위한 역할을 분리하겠다는 의미**라고 생각합니다. 그럼 비즈니스 로직을 수행하는 역할인 서비스 객체가 엔티티를 알아야 할 이유가 있나요? 

포케가 두 객체를 분리한 이유와 서비스 코드에 둘 모두 드러낸 이유를 듣고 싶어요!

2024-10-20 05:24 UTC, fromitive commented
안녕하세요 테바! 의미있는 리뷰를 해주셔서 감사합니다..!

아래는 각각 질문해주신 것에 대한 답변이에요



> 정합성이 중요한 상황과 아닌 상황은 어떻게 판단하나요? 그 기준은 무엇인가요?
> 일반적으로 쿠폰을 생성하는 입장은 쇼핑몰에 입점한 가게의 관리자겠죠. 그리고 구매자들은 쿠폰을 사용하는 입장일 거구요. 이 가정에서 포케가 생각하는 정합성이 중요한 상황과 아닌 상황이 어떤 예시가 있을지 들어보고 싶어요.

저는 정합성이 중요한 상황을 판단할 때 **데이터베이스에 저장된 쿠폰 내용이 변경되는 상황인가를** 판단했습니다. 

제가 생각하는 상황은 아래와 같습니다.

**정합성이 중요한 상황**
* 관리자가 발행한 쿠폰 내용과 구매자가 발급 받는 쿠폰 내용 일치 여부
	* 쿠폰의 할인 정보가 변경될 때 지연이 발생해서 기존 정보가 업데이트 되지 않았을 때 구매자가 지불한 금액과 관리자가 받아야 하는 금액이 일치하지 않을 가능성이 있다고 생각했습니다.

**정합성이 중요하지 않은 상황**
* 구매자가 발급 가능한 쿠폰 목록들을 조회할 때
	* 쿠폰 정보를 조회하는 건 데이터베이스 쿠폰 내용을 변경하는 작업이 아니기 때문에 정합성이 중요하지 않은 상황이라고 생각했습니다.

> 개발자들은 서비스 코드에 두개나 존재하는 조회 메서드의 의도를 설명하지 않고 알 수 있나요? **캐시 메모리를 도입한 시스템이 갖추어야할 시스템들을 생각하는 것**과, **두 조회 메서드 중 어느 메서드를 사용해야하는지 판단하는 것** 중 포케는 후자가 협업관점에서 덜 부담이라고 생각했다고 이해했어요.
> 
> 그럼 조회 메서드에서 어떤 것을 사용해야하는지 고려하지 않아도 되도록, **조회 기능을 적절히 추상화하는 방법**을 선택하시지 않은 이유는 무엇인가요?

테바가 이해하신 부분은 정확합니다. 정말 좋은 질문이라고 생각합니다. 사건이 발생한지 얼마 되지 않은 상황에서는 임시 방편으로는 팀원들에게 직관적으로 설명할 수 있어 좋은 방법이라고 생각했습니다.

하지만 시간이 지나고 사건에 대한 배경지식을 모르는 개발자가 제 코드를 보면 과연 의도가 제대로 전달될까를 고민해봤을 때 제대로 전달되지 않을 수 있겠다고 생각합니다.

조회 기능 메서드를 나눈 이유는 해당 메서드를 사용할 상황이 많이 없을 것이라고 판단했습니다.

메서드 네이밍 의도대로 **즉시**라는 의도는 담았지만 이 서비스 메서드가 어디서 사용되는지 이 메서드를 **반드시** 활용해야지만 해결할 수 있는 문제인가는 전달이 되지 않을 것 같아요.

코드 작성할 때 이러한 부분은 생각하지 못했는데 좋은 지적 감사합니다!

> 정합성이 중요하지 않은 조회메서드가 더 많이 쓰일 거라는 의미인가요? 그렇다면 왜 캐시를 사용하지 않았나요? 정합성이 중요할 땐 reader DB를 읽고 나머지는 캐시에서 조회하는 것도 가능할텐데말이죠! 포케가 가정한 상황을 좀 더 구체적으로 듣고 싶어요.

* **팀이 캐시메모리에 대한 배경지식이 부족하다.**
팀(저포함 ㅜㅜ)이 캐시 메모리에 대한 배경지식이 부족한 상황에서 빠르게 오류를 해결해야하 함을 가정했어요. 캐시 메모리를 사용할 때 주의해야 할 상황을 숙지하지 못한 채 도입하게 되면 장애가 발생할 때 원인을 찾기가 힘들 것이다라고 판단했습니다.

reader DB는 writer DB에 레플리카로 연동되어는 있는 반면 캐시는 writer DB와 아무런 연관도 맺지 않은 시스템이기 때문에 캐시에 있는 쿠폰 데이터를 어디까지 신뢰할 수 있을지 기준이 잡히지 않았습니다(신뢰를 해야할까요?). reader DB에 있는 쿠폰 데이터가 캐시와 일치하지 않는다면 업데이트하는 것 까지 고려하는 로직을 넣어야 되는데 복잡하다고 느껴졌어요.

* **복제지연 문제가 캐시를 도입할 정도로 심각하다고 판단하지 않았다.**
복제지연으로 인해서 시스템에 장애가 발생한 상황에서 이를 빠르게 해결(미션 제출 기한이 촉박(?))하기 위해서는 상대적으로 기존 시스템을 활용해서 해결하는 편이 적절하다고 생각했습니다.
복제지연으로 인한 발생한 문제가 캐시 메모리를 새로 도입할 정도로 심각한가? 라고 판단할 수 있는 근거는 없었기 때문에 캐시메모리를 사용하지 않았습니다. 


---

결론

이제 제가 처음 제출한 상황에서 많이 달라졌는데요. 코드를 아래와 같이 반영하려고 합니다.

> 캐시 메모리 학습 후 복제지연 해결 (메서드를 나누는 방식이 아닌 한 서비스 메서드를 적절히 추상화)

혹시 저의 의견 중 이해가 되지 않은 부분이 있다면 피드백 부탁드립니다..! 감사합니다!

2024-10-20 06:01 UTC, fromitive commented on src/main/java/coupon/service/CouponService.java
> +
도메인과 엔티티를 엄밀하게 분리한 이유는 없지만 구현하다 보니 도메인 역할과 DB 접근 역할이 자연스럽게 나뉘어졌습니다. (엄밀하게 나눠야 한다곤 생각하지 않았어요)

커밋 히스토리에서 보셨듯이 구현 할 때 도메인을 먼저 만들고 구현 하면 DB 의존성 없이 바로 테스트가 가능하기 때문에 도메인부터 구현 했고, 자연스럽게 엔티티를 생성 할 때 도메인을 사용하게 되는 구조가 되었습니다.

(현재의 상황에선) 서비스 코드에서 DB 로직을 수행하기 위한 또다른 DB 객체를 만드는 것이 필요 이상이라고 생각했습니다..!

2024-10-27 10:04 UTC, ksk0605 approved these changes
안녕하세요 포케 많이 늦어서 미안해요..😥

그 사이에 코드에는 많은 변경사항이 있었네요. 
캐시를 사용하게 되면서 또 다시 고민해볼 거리가 생겼어요. 
남겨놓은 코멘트는 다음번 제출에 답변 부탁드려요 😀

이번 미션은 충분하다고 생각해서 이만 머지하겠습니다.
다음 스탭에서 뵈어요!

2024-10-27 10:04 UTC, ksk0605 commented on src/main/java/coupon/config/CacheConfig.java
> +        return template;
```java
    private final ObjectMapper objectMapper;

    public CacheConfig(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Bean
    public RedisTemplate<String, CouponEntity> couponRedisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, CouponEntity> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new Jackson2JsonRedisSerializer<>(objectMapper, CouponEntity.class));
        return template;
    }
}
```
직접 new 키워드로 ObjectMapper 를 생성해도 JacksonConfig의 ObjectMapper 빈이 주입되나요?
JacksonConfig의 ObjectMapper 는 무슨 용도인가요?

2024-10-27 10:04 UTC, ksk0605 commented on src/main/java/coupon/service/CouponReader.java
> +    }
```java
    @Transactional
    public Long save(Coupon coupon) {
        CouponEntity couponEntity = new CouponEntity(coupon);
        CouponEntity savedCoupon = couponRepository.save(couponEntity);
        couponCache.save(savedCoupon);
        // 이 시점 뒤로 버그가 생김을 가정
        return savedCoupon.getId();
    }
```

포케가 작성한 CouponWriter 코드에요. 

만약 제가 표시간 지점이후로 버그가 발생한다면 @Transactional 로 인해 DB는 롤백되겠지만 캐시는 남아있게 됩니다. 
이때 Reader의 코드에서 쿠폰을 조회하면 캐시에는 정상적으로 데이터가 들어있기 때문에 문제 없이 데이터를 반환하게 될텐데요. 

캐시에는 존재하지만 실제 데이터베이스에 저장되지 않은 데이터를 반환하는 상황이 벌어질 수 있겠네요. 
포케가 의도한 상황일까요? 아니라면 어떻게 개선해볼 수 있을까요?

2024-10-27 10:04 UTC, ksk0605 commented on src/main/java/coupon/service/CouponWriter.java
> +    }
캐시 저장과 DB 저장이 같은 트랜잭션 안에 물려있네요. 
이 경우 캐시 저장 실패시 DB 저장 또한 롤백되겠네요. 
캐싱 실패가 DB 저장 실패와 같은 레벨로 취급하여도 괜찮을까요?

2024-10-27 10:05 UTC, merged

2024-10-28 04:18 UTC, fromitive commented on src/main/java/coupon/service/CouponWriter.java
> +    }
동기 처리할 때 try-catch로 별도의 예외처리를 했습니다 😃

2024-10-28 04:21 UTC, fromitive commented on src/main/java/coupon/config/CacheConfig.java
> +        return template;
redis로부터 데이터를 읽어 올 때 LocalDateTime을 역직렬화 하는 도중 jsr-310 오류가 발생하여 `objectMapper`에 `JavaTimeModule`을 추가했습니다!

redis에서만 발생하는 오류이기에 ObjectMapper를 빈주입 하지 않고, 새로 생성하여 설정을 적용하는 용도로 사용했습니다 😄