[1단계 - DB 복제와 캐시] 트레 미션 제출합니다.
woowacourse/java-coupon pull request #24
Opened 2024-10-18 03:19 UTC by takoyakimchi

테니 반가워요 🎾 이번 미션 재밌게 해봅시다~

복제 지연은 다음과 같이 해결해봤어요.
1. 단건 조회할 때 optional에서 값이 존재하지 않으면, Writer DB를 참조하는 fallback-service에서 다시 조회
2. Writer DB에서도 값이 존재하지 않으면 예외 발생

다중 datasource를 구성하면서, 트랜잭션의 read-only 여부로 어떤 DB를 사용할지 판단하는 로직이 생겼는데요.
추가로 강제로 Writer DB를 사용하도록 하는 로직을 작성했어요.
`CouponQueryFallbackService`를  `readOnly = false`로 만들면 해당 로직은 크게 필요가 없지만
`readOnly = true`로 하면 성능상 이점을 가져갈 수 있을 것 같아 이렇게 구성했습니다.

제 방식은 생성 후 곧바로 조회하는 상황이 빈번하지 않을 때는 적합하다고 생각합니다.
생성 후 곧바로 조회하는 상황이 빈번하다면, 조회를 하는 시점에서 DB까지 찌르지 않고 1차 캐시의 내용을 반환해 주는 방식으로 개선해볼 수 있을 것 같아요.

리뷰 잘 부탁드립니다!

2024-10-19 09:40 UTC, ay-eonii requested changes
안녕하세요 트레~ 반갑습니다 🤡
테이블이 생성되지 않는데요 ㅜㅜ 이 부분은 확인 한 번 부탁드려요~

강제로 Writer DB를 사용하도록 하는 로직이 인상적이네요 😁
몇가지 코멘트 남겼는데 확인 부탁드려요~

추가로

> readOnly = true로 하면 성능상 이점을 가져갈 수 있을 것 같아 이렇게 구성했습니다.

트레가 경험했거나 기대한 `readOnly = true` 에 대해 조금 더 자세히 설명이 듣고싶어요 😋

2024-10-19 09:40 UTC, ay-eonii commented on src/test/java/coupon/domain/CouponTest.java
> +    }
> 할인율은 20% 이하여야 한다.

20.99% 는 20% 이상이 아닌가요 ? 
상한 경계값은 20.01% 인 거 같아요 ㅎ-ㅎ

2024-10-19 09:40 UTC, ay-eonii commented on src/main/java/coupon/domain/Coupon.java
> +        long discountRate = (discountMoney * 100 / minimumOrderMoney);
long 이라면 정수가 나오겠네요 👀

2024-10-19 09:40 UTC, ay-eonii commented on src/test/java/coupon/domain/MemberCouponTest.java
> +        Member member = new Member("teni");
😁

2024-10-19 09:40 UTC, ay-eonii commented on src/test/java/coupon/domain/MemberCouponTest.java
> +        assertThat(memberCoupon.isUsable()).isTrue();
메서드, display name이랑 내용이 다른 것 같아요 확인 부탁해용~

2024-10-19 09:40 UTC, ay-eonii commented on src/test/java/coupon/service/CouponCommandServiceTest.java
> +        Coupon foundCoupon = couponQueryService.findById(savedCouponId);
command service와 query service는 어떤 관계가 있나요?
해당 테스트에서는 command service를 검증하려는 것 같은데 query service로부터 영향을 받을 것 같아요,

2024-10-19 09:40 UTC, ay-eonii commented on src/main/java/coupon/config/DataSourceConfig.java
> +                .type(HikariDataSource.class)
해당 설정이 없으면 어떻게 되나요? 😄

2024-10-19 09:40 UTC, ay-eonii commented on src/main/java/coupon/service/CouponQueryFallbackService.java
> +public class CouponQueryFallbackService {
대체 클래스를 따로 만드셨네요 !

개인적으로 writer에서 읽어오는 작업을 public으로 만든다면 `CouponQueryService.findById`가 아닌 `CouponQueryFallbackService.findById`을 오용하지 않을까 라는 걱정이 있을 것 같아요 🤔

트레는 이 부분에 대해 어떻게 생각하시나요 ?

2024-10-19 09:40 UTC, ay-eonii commented on src/main/java/coupon/config/DataSourceRouter.java
> +    }
스레드가 재활용되는 경우에는 따로 설정하지 않아도 true를 반환하지 않을까요?

2024-10-20 08:58 UTC, takoyakimchi commented on src/test/java/coupon/domain/CouponTest.java
> +    }
소수점은 버리는 요구사항에 맞게 작업했습니다!

2024-10-20 08:58 UTC, takoyakimchi commented on src/main/java/coupon/domain/Coupon.java
> +        long discountRate = (discountMoney * 100 / minimumOrderMoney);
소수점은 버리는 요구사항에 맞게 작업했습니다!

2024-10-20 09:08 UTC, takoyakimchi commented on src/test/java/coupon/domain/MemberCouponTest.java
> +        assertThat(memberCoupon.isUsable()).isTrue();
예리하시군요 👀 수정했슴다

2024-10-20 09:13 UTC, takoyakimchi commented on src/test/java/coupon/service/CouponCommandServiceTest.java
> +        Coupon foundCoupon = couponQueryService.findById(savedCouponId);
read-only인 작업과 아닌 작업을 메서드로 서로 분리하고자 했습니다 (CQRS)
올바른 저장을 확인하기 위해서는 복제 지연이 해결된 버전의 코드가 필요해서
어쩔 수 없이 query service를 의존하도록 했습니다 😭

2024-10-20 09:18 UTC, takoyakimchi commented on src/main/java/coupon/config/DataSourceConfig.java
> +                .type(HikariDataSource.class)
<img width="664" alt="image" src="https://github.com/user-attachments/assets/19445ba7-5357-4e0f-8e27-672e66557a69">

<img width="578" alt="image" src="https://github.com/user-attachments/assets/4ce09cca-213f-4d30-b5a4-dc08d7fb7b62">

오오 `type`을 명시해주지 않아도 스프링이  hikari 커넥션 풀을 사용하는군요

2024-10-20 09:23 UTC, takoyakimchi commented on src/main/java/coupon/config/DataSourceConfig.java
> +                .type(HikariDataSource.class)
아 `application.yml`에 이미 명시해주고 있어서 그런걸까요?? 👀 
<img width="418" alt="image" src="https://github.com/user-attachments/assets/4a9393f3-8bc3-4f0d-9e56-19913b94dd89">

2024-10-21 08:05 UTC, takoyakimchi commented on src/main/java/coupon/config/DataSourceRouter.java
> +    }
해제해주는 작업이 필요하겠네요!

2024-10-21 08:37 UTC, takoyakimchi commented on src/main/java/coupon/service/CouponQueryFallbackService.java
> +public class CouponQueryFallbackService {
self-invocation 하게 되면 proxy를 타지 않고 `CouponQueryService`를 그대로 타게 되서
트랜잭션이 원하는대로 적용되지 않는 문제가 있었는데요.
proxy를 통해서 호출하는 방식으로 해볼게요

2024-10-21 08:38 UTC, takoyakimchi commented
잘 부탁해요 😸

2024-10-23 00:31 UTC, ay-eonii approved these changes
안녕하세요 트레~ 

미션 요구사항 잘 만족해주셔서 approve 합니다! 
할인률 소수점 관련해서 잘 못 리뷰 했는데 정정해주셔서 감사합니다 😁

다음 미션에서 봅시다~!!

2024-10-23 00:31 UTC, ay-eonii commented on docker/init/init.sql
>  create database if not exists coupon;
이미 지우셨긴한데 저는 \`coupon\` 처럼 백틱 넣어주니까 생성 되더라구요 👀

2024-10-23 00:31 UTC, ay-eonii commented on src/main/java/coupon/aspect/FallbackWriterAspect.java
> +    }
명시적으로 허용/차단해주지 않아도되네요 !

2024-10-23 00:31 UTC, ay-eonii commented on src/main/java/coupon/domain/Category.java
> +@Embeddable
이 어노테이션은 왜 필요한가요 ?? 몰라서  질문합니닷

2024-10-23 00:31 UTC, ay-eonii commented on src/main/java/coupon/service/CouponQueryService.java
> +    public Coupon findByIdFromWriter(long id) {
`@Transactional` 이 붙여서 어쩔 수 없이 public 인가봐요 😢

2024-10-23 00:31 UTC, merged

2024-10-23 01:08 UTC, takoyakimchi commented on src/main/java/coupon/domain/Category.java
> +@Embeddable
헉 실수요 ㅎ ;;

2024-10-23 01:09 UTC, takoyakimchi commented on src/main/java/coupon/service/CouponQueryService.java
> +    public Coupon findByIdFromWriter(long id) {
이 부분은 개선이 필요하겠네요!!!