[1단계 - DB 복제와 캐시] 위브(김기범) 미션 제출합니다.
woowacourse/java-coupon pull request #32
Opened 2024-10-18 05:22 UTC by jimi567

안녕하세요 로빈 
마지막 미션 리뷰 잘 부탁드립니다.

제가 선택한 방식은 
Reader 조회 -> lag로 조회x -> writer 조회 -> 조회가 안되면 예외

replica의 장점 일부와 가용성을 포기하는 방식이지만, 데이터 정합성이 중요한 조회 작업에서 사용할만한 방식이라고 생각해서 위 방식을 택했습니다.

제가 생각한 후보군은 다음과 같아요.

1. 반동기 및 동기로 복제
복제 방식을 반동기 및 동기로 하게 된다면, 저장 트랜잭션의 connection 점유가 길어질 것 같아요.
다만, 데이터 정합성을 맞추기 위한 가장 좋은 방법이라고도 생각해요. 이 방식은 코드 레벨에서의 해결이 아니라서 일단은 제외했어요.
2. 데이터 정합성이 중요한 조회는 무조건 Writer에서 조회
쿠폰 도메인을 잠깐 내려놓고 생각하면, 특정 비즈니스에 따라서는 데이터 정합성이 매우 중요한 조회작업이 있을 것 같아요.
이러한 조회작업에 한해서 무조건 writerDB에서 조회하도록 한다면 복제 지연으로 인한 데이터 조회 실패를 해결할 수 있을 것 같아요. 다만 복제의 장점인 조회작업과 쓰기작업의 분산은 큰 폭으로 포기해야 될 것 같아요.
만약 위를 구현한다면 spring의 AOP를 활용할 것 같아요.  
현재는 조회 작업이 하나라서, 결국은 모든 작업을 writerDB에서 작업하는 형태가 될 것 같아 채택하지 않았습니다.

혹시 제가 잘못 알고 있거나, 의문스러운 부분이 있으면 편하게 코멘트 남겨주세요.

2024-10-18 15:43 UTC, robinjoon requested changes
안녕하세요 위브! 이렇게 코드리뷰로 만나니 새롭네요😀. 복제 지연 방식을 현재 요구사항에 알맞게 선택하셨다 생각해요. 그래서 자연스럽게 리뷰의 포커스를 다른 쪽으로 맞추게 된 것 같네요. 그래서 고민거리를 두개 더 던져드리려고 합니다.😀

현재는 쿠폰이 한번 생성되면 변경되지 않아요. 그런데, 만약 쿠폰을 수정할 수 있다는 요구사항이 추가된다면, 그때도 현재의 방법이 유효할까요? 만약 아니라면 그때는 어떻게 할 수 있을까요?

> 쿠폰 도메인을 잠깐 내려놓고 생각하면, 특정 비즈니스에 따라서는 데이터 정합성이 매우 중요한 조회작업이 있을 것 같아요.
이러한 조회작업에 한해서 무조건 writerDB에서 조회하도록 한다면 복제 지연으로 인한 데이터 조회 실패를 해결할 수 있을 것 같아요. 다만 복제의 장점인 조회작업과 쓰기작업의 분산은 큰 폭으로 포기해야 될 것 같아요.

조금 더 생각의 폭을 넓혀보면, 도메인을 무결성과 가용성을 어느정도로 요구하는지에 따라 분류한다면 다음과 같을 것 같아요.

1. 높은 무결성과 낮은 가용성
2. 낮은 무결성과 낮은 가용성
3. 낮은 무결성과 높은 가용성
4. 높은 무결성과 높은 가용성 

각각의 경우 어떤 방식으로 복제 및 조회 전략을 수립할 수 있을까요?

2024-10-18 15:43 UTC, robinjoon commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final BigDecimal UNIT = new BigDecimal("500");
돈과 관련된 것이기 때문에 높은 정밀도를 요구하니 `BigDecimal`을 사용하신거라 생각해요. 그런데, 정말 현재 요구사항에 적합한 선택일까요?

제가 `BigDecimal`을 사용하는 것이 적절하지 않다고 생각하는 이유는 다음과 같아요.

1. 요구 사항이 큰 숫자를 다루지 않는다.
2. 요구 사항이 정수만을 다룬다.
3. 쇼핑몰에서 다루는 금액이 더욱 커지거나 원화가 아닌 다른 통화로 결제하는 미래를 생각한다면 "화폐" 혹은 "돈"을 의미하는 도메인으로 분리하는 것이 더욱 확장에 유리하다.

2024-10-18 15:43 UTC, robinjoon commented on src/main/java/coupon/service/RoutingMasterTemplate.java
> +}
왜 Bean으로 관리하셨나요? 아 @Transaction 어노테이션이 Spring AOP 기반으로 동작하기 때문에, Bean이 아니면 트랜잭션이 적용되지 않나요?

2024-10-18 15:43 UTC, robinjoon commented on src/main/resources/application.yml
> +        hbm2ddl.auto: update
![image](https://github.com/user-attachments/assets/f7fb1d92-4ee5-4c91-b709-8adf99890cb7)
미션이 프로덕션 환경을 가정하고 있는데 위브는 프로덕션 환경에서도 update 설정을 해도 된다고 생각하시나요?

2024-10-18 15:43 UTC, robinjoon commented on src/main/resources/application.yml
> +        mode: always
프로덕션을 가정한다면, 상당히 무서운 옵션이라고 생각해요.

2024-10-18 15:43 UTC, robinjoon commented on src/test/java/coupon/DataSourceRoutingTest.java
> +                .invoke(replicationRoutingDataSource);
왜 리플랙션을 이용해 테스트를 동작하도록 했는지 이해가 안갔는데, 테스트 대상이 상속받은 메서드고, 하필이면 그게 protected 메서드라서 그랬군요.

하지만, 그거 아시나요? **자바는 메서드 오버라이딩 시 접근 지정자를 더 큰 범위로 넓히는 것을 허용**하고 있어요!

default 메서드를 오버라이딩 한다면 protected, public 으로 변경이 가능하고, **protected 메서드를 오버라이딩 한다면 public으로 변경이 가능**해요!

2024-10-18 15:43 UTC, robinjoon commented on src/test/java/coupon/domain/coupon/DiscountRateTest.java
> +        MinimumOrderAmount minimumOrderAmount = new MinimumOrderAmount("40000");
경계값 테스트를 수행할 수 있을 것 같아요. 할인 금액이 1000원이라면 구매 제한 금액이 33334원일 때가 테스트로 알맞을 것 같네요.

다른 부분도 경계값 테스트를  수행하면 좋을 것 같아요.

2024-10-21 04:26 UTC, jimi567 commented on src/main/resources/application.yml
> +        hbm2ddl.auto: update
그러네요. mode를 none이나 validate로 수정해야 될 것 같습니다.

2024-10-21 04:43 UTC, jimi567 commented on src/main/java/coupon/service/RoutingMasterTemplate.java
> +}
첨언하자면, 해당 클래스는 일반 클래스로 선언해서, service쪽에서 di해주기 위해서도 있어요.
제가 따로 빈으로 등록안하고 테스트 해보진 않았지만, spring aop가 말씀하신 것 처럼 bean이 아니면 동작을 안하는것으로 알고 있어서, 자연스럽게 bean으로 관리하게끔 구성했던 것 같아요.
혹시 더 좋은 방법이 있을까요?

2024-10-21 05:37 UTC, jimi567 commented on src/test/java/coupon/DataSourceRoutingTest.java
> +                .invoke(replicationRoutingDataSource);
말씀하신 것을 적용한다면, 굳이 리플렉션을 사용하지 않더라도 테스트 가능할 것 같아요.
다만 현재 검증은 datasource를 바인딩하는 key값을 검증하는 테스트지 실제 datasource가 writer 인지 reader인지 테스트하는게 아니에요.
미션 당시에는 시간 부족으로 이렇게라도 검증을 했지만, 트랜잭션 옵션에 따라 실제 등록되는 datasource가 어떤것인지 검증하도록 변경하려고 합니다.

>  자바는 메서드 오버라이딩 시 접근 지정자를 더 큰 범위로 넓히는 것을 허용하고 있어요!

별개로, 새로운 사실을 알아가게 되네요.  ㄷㄷ  아직 자바도 잘 모르는 것 같습니다.

2024-10-24 11:18 UTC, jimi567 commented on src/test/java/coupon/domain/coupon/DiscountRateTest.java
> +        MinimumOrderAmount minimumOrderAmount = new MinimumOrderAmount("40000");
전체적으로 살펴보면서 아쉬웠던 부분 개선했습니다.

2024-10-24 11:25 UTC, jimi567 commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final BigDecimal UNIT = new BigDecimal("500");
500으로 나누어 떨어진다. 할인율은 내림한다. 등의 요구사항을 살펴보면, 기본 정수타입으로도 충분한 것 같아요.
저 역시 처음에 기본 정수 타입을 고려하려고 했습니다.
BigDecimal을 사용하게 된 이유가 3번이긴 한데, 조금 관점이 달랐던 것 같습니다.
Money 도메인으로 확장하더라도 기존 로직과 검증도 지속적으로 활용하기 편할 것 같았고, 돈이라는 도메인 특징상 BigDecimal을 활용해보는 경험을 해보고 싶었던 이유였던 것 같습니다.

2024-10-24 12:10 UTC, jimi567 commented
안녕하세요! 로빈 
로빈의 질문을 보고 엄청 고민이 많아졌습니다.

> 도메인을 무결성과 가용성을 어느정도로 요구하는지에 따라 분류한다면 다음과 같을 것 같아요
>    1. 높은 무결성과 낮은 가용성  
>    2 . 낮은 무결성과 낮은 가용성
>    3. 낮은 무결성과 높은 가용성
>    4. 높은 무결성과 높은 가용성
> 각각의 경우 어떤 방식으로 복제 및 조회 전략을 수립할 수 있을까요?

가용성의 경우 제가 알고 있는 지식 한에서는 고고익선이라고 생각해요.(주어진 비용에 한해서...)
그래서 조금 답변하기가 많이 어려웠고, 가용성의 중요성이 도메인과 연관이 있을까? 라는 생각이 들더라고요.

다만, 가용성을 포기하더라도 높은 정합성을 챙겨야 하는 도메인의 경우는 당장 떠오르는 것이 금융 관련 도메인인 것 같습니다. 위 예시로 들자면 4번? 일 것 같아요.
금융 관련 도메인은 데이터 유실이 절대 일어나선 안되기 때문에 복제를 통한 백업 데이터 유지는 필수라고 생각해서 복제는 무조건적으로 해야 될 것 같아요.
무작정 LeaderDB를 조회하도록 하면 세상 편하지만, 가용성을 챙길 수 없겠죠. 
만약 저 4번 상황이라면 저의 경우 복제를 반동기 방식으로 할 것 같습니다. 최소한 하나 이상의 Reader에 복제가 완료 되도록 만 보장한다면 트랜잭션을 종료해도 큰 문제가 있을 것 같진 않아요.

3번 경우인 무결성을 크게 챙길 필요가 없는 도메인의 경우는 그대로 ReaderDB에서 조회하되, 만약 실패하게 된다면 후속 작업 없이 트랜잭션을 종료 or 롤백하도록 할 것 같아요.!

제가 질문의 의도를 잘 이해한게 맞는지도 의심스럽네요. 혹시 원했던 방향의 답변이 아니거나 아쉬운 점이 있다면 추가 피드백 부탁드립니다!

2024-10-25 09:34 UTC, robinjoon approved these changes
안녕하세요 위브! 리뷰 반영이 다 된 것으로 보이네요! 저와 생각이 다른 부분을 확실히 알 수 있어서 좋았어요! 다음 단계도 화이팅합시다!

2024-10-25 09:34 UTC, merged