[DB 복제와 캐시 1단계] 초롱 미션 제출합니다.
woowacourse/java-coupon pull request #36
Opened 2024-10-18 06:16 UTC by HoeSeong123

안녕하세요 레모네!!!!🍋

제가 생각한 복제 지연에 대한 해결 방법은 다음과 같아요.
- 데이터 읽기에 실패할 경우 Writer DB에서 재시도 한다.

이렇게 했을 때 생각나는 문제점은 다음과 같아요.
- 악의적인 사용자가 존재하지 않는 데이터에 대한 읽기 요청을 무한하게 보낼 경우 심각한 성능 저하가 발생할 수 있습니다.
- update시 데이터 정합성을 보장하기 어렵습니다.

그럼에도 해당 방법을 선택한 이유는 다음과 같습니다.
- (그럴일은 없겠지만) 현재 제 코드가 그대로 서비스 되게 된다면 수정 기능이 없으므로 두 번째 문제사항에 대해서는 아직 고려하지 않았습니다.
- 데이터를 가장 빠르게 가져올 수 있는 방법이라고 생각했습니다.

그럼 이번 미션 잘 부탁드립니다 레모네!!

2024-10-19 06:29 UTC, JiHyeonL requested changes
안녕하세요 초롱! 레모네입니다 😊
먼저 리뷰가 늦어 죄송합니다 😭😭
깔끔하게 구현해 주셔서 간단한 리뷰 몇가지 남겼습니다!

서비스 테스트를 실행하기 위해 직접 테이블 스키마를 넣어 주었는데요, 제대로 실행되지 않는 부분이 있어서 한번 확인해 주시면 감사하겠습니다! 
+) 테이블 스키마를 제공해 주시면 테스트를 실행하기 더 편할 것 같습니다 🙇‍♀️

2024-10-19 06:29 UTC, JiHyeonL commented on README.md
> +### 쿠폰
요구사항 정리👍👍 좋습니다!

2024-10-19 06:29 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    private Category category;
초롱의 테이블 스키마를 넣어서 테스트를 실행해 보려 하는데, 

```
Schema-validation: wrong column type encountered in column [category] in table [Coupon]; found [enum (Types#CHAR)], but expecting [tinyint (Types#TINYINT)]
```
이런 에러가 발생하네요!

Category enum을 문자열로 저장할 수 있도록
`@Enumerated(EnumType.STRING)` 어노테이션을 추가해 주세요!

+) 테이블 스키마를 제공해 주시면 테스트를 돌리기 더 수월할 것 같습니다!

2024-10-19 06:29 UTC, JiHyeonL commented on src/main/java/coupon/config/DataSourceConfig.java
> +    @DependsOn({"routeDataSource"})
`@DependsOn`은 어떤 역할을 하는 어노테이션인가요?
`@Primary`와 `@DependsOn` 을 함께 사용하면 어떤 효과가 있을까요?

+) 비슷한 역할을 하는 `@Qualifier` 어노테이션에 대해서도 찾아보시면 좋을 것 같아요!

2024-10-19 06:29 UTC, JiHyeonL commented on src/main/java/coupon/utils/TransactionSupport.java
> +    }
읽기 지연 문제를 Service 단에서 처리하지 않고, `TransactionSupport` 클래스가 담당하고 있군요!
역할 분리 좋습니다👍

2024-10-19 06:29 UTC, JiHyeonL commented on src/main/java/coupon/service/CouponService.java
> +    }
read DB에 쿠폰이 없을 경우 write DB에서 쿠폰을 찾는데, `readOnly = true` 가 적절한 옵션인지 의문이 들었습니다!
초롱은 어떻게 생각하시나요?

2024-10-19 06:29 UTC, JiHyeonL commented on src/main/java/coupon/utils/TransactionSupport.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
해당 트랜잭션 내에서 `couponRepository.findById(id)` 를 수행하면 write DB에 접근하는 이유가 무엇일까요?

2024-10-24 06:09 UTC, HoeSeong123 commented on src/main/java/coupon/domain/Coupon.java
> +    private Category category;
도커에 스키마 파일을 추가했습니다!! 도커 재실행하면 테이블 생성될 것 같습니다.
만약 안되면 docker/data 폴더를 삭제 후 재실행해주세요!!

2024-10-24 06:39 UTC, HoeSeong123 commented on src/main/java/coupon/service/CouponService.java
> +    }
처음에는 read DB에서 읽어야 하기 때문에 `readOnly = true` 옵션을 추가해주었습니다.
조회에 실패할 경우에는 `getCouponWithWriter` 메소드가 실행되며 write DB에서 쿠폰을 다시 한 번 조회합니다.

2024-10-24 06:43 UTC, HoeSeong123 commented on src/main/java/coupon/utils/TransactionSupport.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
Propagation 옵션을 `REQUIRES_NEW`로 설정해주었기 때문입니다!!
`REQUIRES_NEW` 옵션은 부모 트랜잭션과 별도의 트랜잭션을 생성합니다. 따라서 부모 트랜잭션은 read DB에 접근하는 옵션이었지만 해당 트랜잭션은 별도의 트랜잭션을 생성하기 때문에 write DB에 접근할 수 있습니다!

2024-10-26 05:02 UTC, HoeSeong123 commented on src/main/java/coupon/config/DataSourceConfig.java
> +    @DependsOn({"routeDataSource"})
`@DependsOn`은 특정 빈이 생성되기 전에 다른 빈이 먼저 생성되어야 할 때 사용하는 어노테이션입니다. 현재 `dataSource`는 `routeDataSource`를 의존하고 있기 때문에 `dataSource`가 생성되기 전에 `routeDataSource`가 생성되어야 합니다. 이런 식으로 특정 빈 간에 순서를 지정할 필요가 있는 경우, 이 어노테이션을 통해 그 순서를 제어할 수 있습니다. Spring은 기본적으로 빈을 자동으로 생성하지만, 특정 빈 간에 순서를 지정할 필요가 있는 경우, 이 어노테이션을 통해 그 순서를 제어할 수 있습니다.

`@Primary`는 동일한 타입의 여러 빈이 있을 때, Spring이 의존성 주입 시 기본적으로 사용할 빈을 지정할 수 있는 어노테이션입니다. 즉, 같은 타입의 빈이 여러 개 있을 때, `@Primary`가 지정된 빈이 우선적으로 주입됩니다.

`@Primary`로 설정된 빈은 동일한 타입의 여러 빈 중 기본적으로 주입되지만, 그 빈이 다른 빈에 의존하고 있다면 `@DependsOn`으로 그 의존성을 설정할 수 있습니다. 이렇게 하면 해당 빈이 먼저 생성되도록 하고, 그 후에 `@Primary`로 설정된 빈이 주입되는 순서를 보장할 수 있습니다.

`@Qualifier`는 동일한 타입의 여러 빈이 있을 때, 특정 빈을 선택적으로 주입할 수 있도록 도와주는 어노테이션입니다. `@Primary`와는 달리, `@Qualifier`는 명시적으로 어떤 빈을 주입할지 지정하는 역할을 합니다.

`@Primary`는 기본 빈을 지정하는 반면, `@Qualifier`는 명시적으로 특정 빈을 선택합니다. 만약 두 어노테이션을 함께 사용하면 주입할 때 기본적으로는 `@Primary` 빈을 사용하되, 필요할 때 `@Qualifier`로 다른 빈을 선택적으로 주입할 수 있습니다.

2024-10-26 05:04 UTC, HoeSeong123 commented
안녕하세요 레모네!! 데모데이 준비로 이제서야 리뷰 요청을 드리게 되었네요ㅠㅠ
요청하신대로 스키마 파일을 추가하였습니다!!
그럼 이번 리뷰도 잘 부탁드립니다!!

2024-10-26 19:16 UTC, JiHyeonL approved these changes
안녕하세요 초롱!
1단계 미션 요구사항은 모두 만족하신 것 같아 approve 드리겠습니다.
추가적으로 도메인 & 클린코드 관련 피드백을 남겼는데요,
2단계 진행하시면서 함께 반영해 주시면 좋을 것 같아요!!
수고하셨습니다~~

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    }
Category를 제외하고 나머지 필드는 엔티티 내에서 예외 처리를 해 주신 이유가 궁금하네요!
자신만의 도메인 규칙이 있는 변수들은 객체를 생성해서 역할 분리를 해 주는 것도 좋을 것 같아요!

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +        if (discountAmount % 500 != 0) {
도메인 분리를 해주신다면 매직넘버도 상수화 해 주면 좋겠네요!

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    private static void validatePurchaseAmount(Integer purchaseAmount) {
static은 생략해 줘도 될 것 같아요~

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    private Integer purchaseAmount;
두 값은 null을 허용하지 않는데 래퍼 클래스를 사용하신 이유가 있을까요?

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    ) {
생성자 파라미터로 id가 존재하면, 개발자가 임의로 id를 조작할 수 있다는 문제점이 발생할 수 있겠네요!
Id를 조작할 수 있는 권한은 JPA에게만 부여하는 것이 더 안정적일 것 같아요.

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Coupon.java
> +    }
위에서 언급한대로 id 파라미터가 없는 생성자가 있다면 이 생성자도 불필요 할 것 같아요.

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Member.java
> +
Member와 MemberCoupon 클래스 마지막에 불필요한 공백 삭제해 주세요!

2024-10-26 19:16 UTC, JiHyeonL commented on src/main/java/coupon/domain/Member.java
> +    private Long id;
클래스 선언부 다음으로 오는 필드 사이에 공백을 추가한 클래스도 있고, 공백이 없는 클래스도 있어서 컨벤션을 맞춰주시면 좋을 것 같아요!

2024-10-26 19:18 UTC, merged

2024-10-29 04:49 UTC, HoeSeong123 commented on src/main/java/coupon/domain/Coupon.java
> +    }
시간이 없어서 냅다 만들어버리느라... 책임 분리를 전혀 하지 않았네요..
래퍼 클래스 생성 후 책임에 맞게 검증 메소드를 분리해주었습니다!!