[1단계 - 복제 지연] 에버(손채영) 미션 제출합니다.
woowacourse/java-coupon pull request #44
Opened 2024-10-18 07:25 UTC by helenason

배키 안녕하세요!
이전에 페어로 만났었는데 이번에는 저의 리뷰어가 되셨군요! 반갑습니다.

제가 고려했던 방법들, 그리고 최종적으로 선택한 방법과 이유 설명 드릴게요!
인프라 관련해서 부족한 편이라 지적 많이 부탁 드려요.

감사합니다 :)

## 고려 방법

### 1. Reader DB에서 조회 성공할 때까지 무한 반복 조회

무식한 방법일 수 있지만 하나의 방법이기 때문에 구현해보았습니다.
- 장점: Reader DB에서의 조회를 보장
- 단점: 성공을 보장하진 않음, 서버 부하, 무한 트랜잭션(커넥션) 생성, 무한 루프로 인한 서버 중단 가능성 존재

### 2. Redis 도입

- 장점: 읽기/쓰기 속도 빠름, 쓰기 작업 완료 전 읽기 작업 처리 가능
- 단점: 다른 해결 방법이 존재하고, 복제 지연 발생률이 매우 높지 않기 때문에 과한 설계라고 판단

### 3. 조회 전 일정 시간 지연 처리

- 장점: 적은 구현 리소스
- 단점: 해결 방법이라기보다는 예외 발생 가능성을 줄이는 방법, 지연 시간의 기준 설정이 어려움, 명확한 기준이 없기 때문에 불안정

### 4. Reader DB 조회 실패 시 Writer DB로 조회

- 장점: 적은 구현 리소스
- 단점: 애플리케이션 내 비즈니스 로직에 인프라 관련 코드 침투

## 구현 방법
4번 방법인, Reader DB 조회 과정에서 예외가 발생한 경우 Writer DB로 조회하도록 구현하였습니다. 비즈니스 코드에 인프라 관련 코드가 침투되는 것은 찝찝하지만, 네가지 방법 중 리소스 대비 해결 정도가 가장 명확하다고 판단하였습니다. 혹시나 제가 고려한 방법에 대한 코드가 궁금하시면 이전 커밋을 까보시면 됩니다!

2024-10-19 14:35 UTC, ehBeak requested changes
안녕하세요~ 에버!
우선 하루 내로 리뷰해야 했는데, 늦어서 죄송합니다🥲

페어로 만났을 때가 엊그제 같은데, 벌써 우테코의 마지막 미션이네요..ㅎㅎ
잘 부탁드려요! 

추가로 어플리케이션 테스트가 실패하는 것 같아요. 확인 부탁드려요 :)
혹시 궁금한 점이 있다면 언제든지 dm 환영입니당

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/config/DataSourceConfig.java
> +    @DependsOn({"writerDataSource", "readerDataSource"})
단순한 궁금증입니다~ 매개변수로 받지 않고 DependsOn을 사용한 이유가 있을까요? 🤔

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/domain/coupon/CouponName.java
> +        if (name.length() > 30) {
`CouponAmount` 클래스에서는 상수를 뺀 것을 보입니다. 이름 길이를 나타내는 30도 상수로 빼보면 어떨까요?

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/domain/coupon/ProductCategory.java
> +    ;
한국어로 상수명을 설정하셨네요😲

사실 그렇게 중요한 부분은 아니지만, 상수명은 영어로 관례를 따르고 한국어 이름은 문자열 필드를 하나 두어서 관리하면 어떨까요?

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/repository/entity/MemberCoupon.java
> +        this.endedAt = issuedAt.plusDays(6);
다음과 같은 요구사항이 있습니다~!
> 회원에게 발급된 쿠폰은 발급일 포함 7일 동안 사용 가능하다. 만료 일의 23:59:59.999999 까지 사용할 수 있다.

이 요구사항을 만족하기 위해 만료일의 마지막 시간을 설정해 보는 것은 어떨까요? 😊

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/service/CouponService.java
> +        log.info("쿠폰 저장: {}", saved.getId());
꼼꼼한 로깅 좋습니다👍👍

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/service/CouponService.java
> +    }
이 함수는 처음 조회할 때, 읽기 전용 DB에서 조회를 하나요? 아니면 쓰기 전용 DB에서 조회를 하나요?
어떤 DB에서 조회를 하는지, 그리고 그 이유가 무엇인지 궁금합니다 🤔

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/config/DataSourceRouter.java
> +        return DataSourceLookupKey.WRITER;
`DataSourceRouter`는 어떤 것을 기준으로 `READER DB`에 접근하고 `WRITER DB`에 접근할까요?

2024-10-19 14:35 UTC, ehBeak commented on src/main/java/coupon/service/ReaderService.java
> +    @Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
`Propagation.REQUIRES_NEW`를 설정한 이유가 궁금합니다!

2024-10-19 14:35 UTC, ehBeak commented on src/test/java/coupon/service/CouponServiceTest.java
> +         */
주석은 의도하신 걸까요? 만약 아니라면 지워도 좋을 것 같습니다 :)

2024-10-28 05:36 UTC, helenason commented on src/main/java/coupon/config/DataSourceConfig.java
> +    @DependsOn({"writerDataSource", "readerDataSource"})
매개변수로 입력받는 방식보다 더 가독성이 높다고 판단하였습니다!

2024-10-28 05:38 UTC, helenason commented on src/main/java/coupon/domain/coupon/ProductCategory.java
> +    ;
만약 팀 프로젝트에서의 코드라면 무조건 배키의 코멘트를 따랐겠지만, 현재는 저 혼자 작성하는 미션 코드라서 제가 편한 방식으로 enum 클래스를 만들어보았어요! 조금 더 직관적이지 않나요? ㅎㅎㅎㅎ

2024-10-28 05:49 UTC, helenason commented on src/main/java/coupon/repository/entity/MemberCoupon.java
> +        this.endedAt = issuedAt.plusDays(6);
저는 `만료일의 23:59:59.999999까지`가 결국 만료일 당일까지라고 생각해서, 추가적인 시간 설정은 하지 않았습니다! 토미도 강의에서 비슷한 말씀을 하신 것 같아요 😲

2024-10-28 05:51 UTC, helenason commented on src/main/java/coupon/service/CouponService.java
> +    }
위 함수만 보았을 때는, 쓰기 전용 DB에서 조회합니다! `@Transactional`에 readOnly 조건이 붙지 않았기 때문이에요. 읽기 전용 DB에서 조회하는 로직은 `readerService.read(() -> getCoupon(saved.getId()));`와 같이 구현하였어요!

2024-10-28 05:53 UTC, helenason commented on src/main/java/coupon/config/DataSourceRouter.java
> +        return DataSourceLookupKey.WRITER;
`TransactionSynchronizationManager.isCurrentTransactionReadOnly()`라는 조건에 따라서, `@Transactional` 어노테이션의 readOnly 조건을 기준으로 READER DB와 WRITER DB에 접근하게 됩니다!

2024-10-28 05:56 UTC, helenason commented on src/main/java/coupon/service/ReaderService.java
> +    @Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
ReaderService의 read 메서드는 CouponService의 saveCoupon에서 호출되는 메서드인데요. 전파 레벨을 REQUIRES_NEW로 설정하지 않은 경우 기존의 readOnly가 false인 트랜잭션 상태가 전파되더라구요. 따라서 전파 레벨을 위와 같이 설정함으로써 전파를 막았습니다!

2024-10-28 05:57 UTC, helenason commented on src/test/java/coupon/service/CouponServiceTest.java
> +         */
 로그 결과를 통해 테스트가 잘 동작하는지 확인하기 위해 달아둔 주석이었습니다! 😁

2024-10-28 06:29 UTC, helenason commented
배키 안녕하세요

벌써 미션 마지막 날이네요.
데모데이가 끝났는데도 여전히 정신이 없어요..
그래도 리뷰 반영하여 제출합니다!
테스트 깨지는 부분도 해결해두었습니다.
곧 2단계 미션도 제출할게요.

마지막까지 잘 부탁드려요 :)

2024-10-28 06:52 UTC, ehBeak commented on src/main/java/coupon/domain/coupon/ProductCategory.java
> +    ;
확실히 직관적이네요ㅎㅎㅎ

2024-10-28 06:53 UTC, ehBeak approved these changes
안녕하세요 에버~
바로 다음 단계 진행하시면 좋을 것 같아서 머지합니다~!

고생 많으셨고 2단계에서 뵈어요😊

2024-10-28 06:53 UTC, merged