[DB 복제와 캐시- 1단계] 아토(이혜린) 미션 제출합니다.
woowacourse/java-coupon pull request #48
Opened 2024-10-18 07:49 UTC by hyxrxn

켈리 안녕하세요! 아토입니다.
레벨4 첫 미션 리뷰어가 망쵸였는데, 코드리뷰 스터디의 스터디원을 마지막에 또 만나게 되었네요 ㅋㅋㅋㅋ
함께 미션을 마무리하게 되다니,,, 반가워요~~~

-------------

그럼 제 구현에 대해 설명을 하도록 하겠습니다.

먼저 뭔가가 저장이 완료되었는데, 읽히지 않는 것을 해결하는 것이 테스트코드의 목적입니다.
그래서 저는 이 문제를 **무조건 해결해야만 하는 상황**이라고 보았어요.
이런 저런 방법을 중간에 사용하더라도, 정 안된다면 마지막엔 writer를 이용해서라도 해결해야 하는 것이죠.

그래서 가장 먼저 생각했던 방법인 읽고 없다면 `Thread.sleep()`으로 쉬다가 reader에서 다시 읽는 방법은 제외했습니다.
얼마나 쉬어야 **무조건**해결할 수 있는지 보장할 수 없기 때문이죠.
지금 상황에서는 몇 초가 지연되는지 구체적으로 알 수 있으나... 실제였다면 확실히 알 수 없었을 겁니다.

중간에 사용할 방법으로 캐시를 이용하는 것도 생각을 해보았습니다.
그런데 저는 `생성하자마자 조회하는 일이 writer에 영향을 줄만큼 자주 일어날까`에 대한 의문이 있었어요.
제가 쇼핑몰을 사용할 때에는 대부분 쇼핑몰에 들어가자마자 쿠폰을 먼저 발급 받고, 이후 살 물품을 구경하고, 결제 시 적용이 가능하다면 쿠폰을 적용하는 순서였거든요.
그래서 쿠폰을 발급받고 바로 그 쿠폰이 잘 있는지 확인해야 할 일이 별로 없을 것이라 예상이 되니, 중간에 다른 과정을 넣는 것이 지금은 불필요해 보였습니다.
하지만 아직 저는 사용자의 통계를 정확히 모르다보니 서비스 중 이 로직이 writer에 부하를 과도하게 줄 가능성이 있다고 생각하기는 합니다!
그렇지만 그건 그 때 생각해 추가하면 된다고 생각해요! 일단 현재의 문제 해결은 했으니까요.

부하가 심해 문제가 생긴다면 인메모리 캐시를 사용해 해결하고, 메모리를 너무 많이 차지해 문제가 생긴다면 캐시 데이터베이스를 활용해 해결하고... 정도로 예상은 해두었습니다만 지금은 생기지 않은 문제(그리고 제 생각엔 일어나지 않을 것 같은 문제)니 미리 메모리나 새로운 데이터베이스를 사용할 필요가 없다고 생각했습니다.

정리를 하자면,
1. 이 문제는 무조건 해결해야 하는 문제
2. 생성하자마자 바로 조회할 일은 (일어나긴 일어날 수 있지만) 많지는 않을 것
3. 그렇다면 그 상황에만 writer로 넘기자
4. 만약 writer에 부하가 심해지면 그 때 추가로 다른 것을 도입하자

입니다!

writer로 넘기는 방식에 대해서도 잠시 언급을 하겠습니다.
트랜잭션을 새로 열어야 하기 때문에 세 가지 방식을 고려했습니다.

먼저, 새로운 클래스를 만들어 그 클래스의 메서드를 호출하는 방식이 있습니다.
그런데 지금은 추가로 필요한 메서드(`getCouponOnWriter`)가 하나밖에 없고, 이를 위해 새로운 클래스를 생성하는 것은 관리 포인트를 늘리는 일이라고 생각했습니다.
또한 이 메서드를 public으로 열어둔다면 사용하면 안되는 곳에서 사용할 가능성을 열어준다는 생각도 들었고요.

다음으로 `AopContext.currentProxy()`를 이용해 프록시를 직접 생성하는 방식이 있습니다.
이를 위해서는 `application.yml`에
```yml
spring:
  aop:
    proxy-target-class: true
    expose-proxy: true
```
를 추가해야 합니다.
그런데 제가 아직 이 설정으로 인해 생길 수 있는 파급효과에 대해 잘 알지 못합니다.
그래서 사용하기가 좀 두려워 도입하지 않았습니다.

그래서 마지막 방식인 트랜잭션을 직접 관리하는 것을 선택했습니다!
이렇게 하면 클래스를 분리할 필요도 없고, 메서드를 private으로 막아둘 수 있습니다.

-------------
관련해서 편하게 피드백 주시길 바랍니다!
도메인 설계나 기타 등등(별 거 없지만...) 관련해서 함께 말해주셔도 좋습니다.
오랜만에 0부터 시작하니 재밌네요.

마지막 미션 잘 부탁드립니다 😋

2024-10-20 17:10 UTC, kelly6bf requested changes
안녕하세요 아토! 이렇게 뵈니까 너무 반가워요. 전체적으로 코드를 야무지게 작성해주셔서 레벨1때 다루던 내용들이 대부분의 코멘트네요. 추억이 돋아서 너무 좋네요.. (레벨1으로 돌아가고 싶다..)

마지막 미션을 함께 할 수 있어 너무 영광입니다! 잘 부탁 드려요!

---
남겨주신 선택 이유 정말 재밌게 읽었어요. 아토의 의식의 흐림이 보여서 재밌게 읽었네요. 저도 같은 방식을 사용했는데 만약 조금더 현실적인 가정을 한다면 이 방식을 어디까지 사용하실거 같나요? (~를 기준으로 이걸 넘으면 이 방식외 다른걸 생각하겠다!)

조금 추상적인 질문이지만, 그만큼 자유롭게 내주신 의견을 듣고싶습니다!

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/config/DataSourceConfiguration.java
> +    @Qualifier(RoutingDataSource.WRITER_SERVER)
개인 취향이지만 `SERVER`라는 단어가 들으니까 DB보다는 WAS가 연상되서 SERVER는 제거하고 간결하게 사용하는것도 좋은거 같아요!

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        int discountRate = (int) (((double) discountAmount / minimumOrderAmount) * 100);
할인율 계산은 다른 로직에서 써먹을 여지가 있으니 따로 분리해보는게 어떨까요?

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        validate(discountAmount, minimumOrderAmount);
개인 취향인거 같지만 그냥 `validate` 보다는 대략적으로 무엇을 validate 하는지 메서드명을 좀 더 자세하게 적어도 좋을거 같아요.

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (MINIMUM_OF_AMOUNT <= discountAmount && discountAmount <= MAXIMUM_OF_AMOUNT) {
이것도 개인 취향이지만 if문안에 throw가 들어가면 로직이 더 짧아지지 않을까요! `return'`문을 적을 필요도 없고요!

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (discountAmount % DIVISOR != 0) {
위 검증 메서드랑 반대로 이곳은 if문에서 throw를 하고 있네요? 통일해주면 어떨까요!

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/PeriodOfIssuance.java
> +        validate(startDate, endDate);
날짜 객체로 `null`이 들어오는 상황은 검증할 필요가 없을까요? 🤔

2024-10-20 17:10 UTC, kelly6bf commented on src/test/java/coupon/domain/coupon/DiscountAmountTest.java
> +    @ParameterizedTest
테스트 로직도 취향 차이지만 전 개인적으로 `Give & When & Then`을 즐겨 사용하는데 아토는 따로 나누지 않으시는 이유가 있으신가요! 개인적으로 파트를 나눠주면 테스트 가독성이 좋아지지 않을까 생각해서요! (아토의 개인 의견이 궁금합니당)

2024-10-20 17:10 UTC, kelly6bf commented on src/test/java/coupon/domain/coupon/MinimumOrderAmountTest.java
> +    @ValueSource(ints = {4999, 100001})
경계값 테스트 야무지네요 🍚

2024-10-20 17:10 UTC, kelly6bf commented on src/test/java/coupon/domain/coupon/PeriodOfIssuanceTest.java
> +        assertAll(
`AssertJ`에 비슷한 역할을 하는 `SoftAssertion`이 존재합니다! 이 기회에 사용해보시는거 어떠신가요?

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/service/CouponService.java
> +            return transactionTemplate.execute(status -> couponRepository.findById(id)
`PlatformTransactionManager`을 활용하는 코드가 기능 확장에 따라 자주 발생할거 같은데 이 로직을 별도의 클래스로 분리해보시는건 어떤가요!

2024-10-20 17:10 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/Name.java
> +public class Name {
개인적으로는 DB 테이블과 1:1 매핑되는 `Entity`와 DB와 관련없이 비즈니스 지식을 가지고 수행하는 `Domain`객체를 분리하는 편입니다! 실제로 대부분의 필드 값들은 불변 객체일텐데 `Entity`가 도메인 지식을 가지고 활동하면 필드를 `final`로 유지하기 힘들고 로직이 잘못 작성되면 더티 체킹으로 DB에 잘못된 업데이트가 발생할 여지가 있고요. (WAS와 DB는 별개의 환경이라 WAS를 꺼도 DB 변경 사항은 그대로 남으니까요)

아토는 `Entity`에 비즈니스 규칙을 주는 지금의 방식 VS `Entity`와 `Domain`객체 분리에 대해 어떤 의견을 가지고 계신가요! 첫 번째 방식을 선택하신 이유를 듣고 싶습니다! (요즘 이걸로 많이 고민하고 있어 인사이트를 얻고 싶네요!)

2024-10-22 13:18 UTC, hyxrxn commented on src/main/java/coupon/config/DataSourceConfiguration.java
> +    @Qualifier(RoutingDataSource.WRITER_SERVER)
그럴 수 있겠네요!
수정하겠습니다.

2024-10-22 13:32 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        validate(discountAmount, minimumOrderAmount);
메서드 내부에서 여러가지를 검증하고 있어서... 한 번에 설명할만한 메서드명이 떠오르지 않았습니다 ㅠ
and로 연결해서 메서드명을 짓자니 내부 내용들을 너무 많이 담고 있는 것 같아서요...!
혹시 추천해주실만한 이름이 있을까요?

2024-10-22 13:33 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (MINIMUM_OF_AMOUNT <= discountAmount && discountAmount <= MAXIMUM_OF_AMOUNT) {
discountAmount가 가운데에 들어가있는 것이 if문의 범위를 알아보기가 더 좋다고 느껴져 이렇게 만들었습니다...!!
이렇게 보아야 가능한 discountAmount가 무엇인지 확인이 빠르더라고요.

2024-10-22 13:36 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (discountAmount % DIVISOR != 0) {
validateRange -> 범위가 이 안이어야만 하는구나!
validateMultiple -> 0이 아니면 안되는구나!

검증의 느낌이 좀 다르다고 생각했어요.
그래도 켈리가 통일하는 게 알아보기 편하다면 변경하도록 하겠습니다~~
읽어보시고 코멘트 다시 달아주세요!

2024-10-23 02:56 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/PeriodOfIssuance.java
> +        validate(startDate, endDate);
그러네요!
방지해보도록 하겠습니다.

2024-10-23 03:02 UTC, hyxrxn commented on src/test/java/coupon/domain/coupon/DiscountAmountTest.java
> +    @ParameterizedTest
현재 도메인 객체들의 테스트는 모두 생성에서만 일어나고 있어
`assertDoesNotThrow`와 `assertThatThrownBy`만 사용합니다!
그래서 그 부분에서는 따로 나누지 못했고요
(혹시 나눌만한 예시가 있다면 하나만 들어주시면 감사하겠습니다...!)
`createAndGet`은 lms의 예시 코드를 가져왔습니다!
새로운 로직 관련 테스트를 짜게 된다면 좀 더 신경써서 만들어보겠습니닷

2024-10-23 09:12 UTC, hyxrxn commented on src/test/java/coupon/domain/coupon/PeriodOfIssuanceTest.java
> +        assertAll(
오! 그렇군요
알아보니 여러 개 실패했을 때 예외를 더 잘 구분해서 보여주는 것이 장점이라고 이해했는데 맞을까요?!
적용해보았습니다!

2024-10-24 12:19 UTC, hyxrxn commented on src/main/java/coupon/service/CouponService.java
> +            return transactionTemplate.execute(status -> couponRepository.findById(id)
저도 생각했던 부분인데 아직 하나라 그냥 두었었어요.
분리해보았습니다!

2024-10-24 12:29 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        int discountRate = (int) (((double) discountAmount / minimumOrderAmount) * 100);
필드로 들고있을 필요가 없는 메서드인 것 같아 static 메서드로 분리했습니다!

2024-10-24 13:04 UTC, hyxrxn reviewed
>  만약 조금더 현실적인 가정을 한다면 이 방식을 어디까지 사용하실거 같나요? (~를 기준으로 이걸 넘으면 이 방식외 다른걸 생각하겠다!)

완전히 초보자라서 아주 자세히 가정을 하기는 어렵지만... 좀 더 생각을 해보자면,
모니터링 중 writer의 cpu 혹은 메모리 사용량이 80%를 초과하면 변경해야 한다는 신호로 받아들일 것 같습니다.
쿼리 시간이 너무 오래 걸려도 변경하려 하겠는데, 정확한 수치는 아직 잘 모르겠네요.
기존에 걸리던 시간과 비교해볼 것 같은데, 5배 이상 정도 증가하면 고려해보지 않을까 싶어요!

2024-10-24 13:13 UTC, hyxrxn commented on src/main/java/coupon/domain/coupon/Name.java
> +public class Name {
NoArgsConstructor와 더티 체킹 때문에 final이 원래 불가능하지 않나요...?! Domain 객체의 필드를 말씀하신 걸까요??

아무튼! 그 부분을 제외하더라도, Entity와 Domain이 모두 각각 분리되어 있다면 관리 포인트가 너무 많아질 것 같다는 생각이 들어요.
예시가 없어 확실히 어떤 상황인지 아직 잘 모르겠으나, db와 연결되는 Entity로서의 Name과 비즈니스 규칙을 들고 있는 Domain으로서의 Name이 두 가지가 모두 존재해야 할텐데...
편하자고 JPA를 쓰면서 JPA로 다시 불편해지는 느낌이 들어요.

아직까지는 단점이 많이 와닿지는 않나봐요...!
많이 고민해본 적은 없던 주제라, 다른 생각이 든다면 다시 남겨보도록 할게요!

2024-10-25 13:18 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        validate(discountAmount, minimumOrderAmount);
다시 생각해보니 저도 묶어주는 메서드로 `validate`가 나쁘지 않은거 같습니다! 그대로 유지하셔도 좋을거 같아요!

2024-10-25 13:19 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (MINIMUM_OF_AMOUNT <= discountAmount && discountAmount <= MAXIMUM_OF_AMOUNT) {
오.. 납득했습니다!

2024-10-25 13:19 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        if (discountAmount % DIVISOR != 0) {
이유가 있어 이 구조를 선택하신거라면 납득합니다! 위 코멘트에 적어주신 이유도 납득하였으니 유지하셔도 좋을거 같아요!

2024-10-25 13:27 UTC, kelly6bf commented on src/main/java/coupon/domain/coupon/Name.java
> +public class Name {
아토가 말씀해주신 내용에 동의합니다!

사실 JPA의 Entity와 도메인 객체를 나누는 방식은 그 장단점이 명확한거 같아요. 필드가 불변인 객체를 유지하면서 테스트 작성이 편한 방식을 원한다면 분리가 맞지만, 그럴 필요가 없다면 아토의 말처럼 편하라고 만든 `JPA`의 장점이 퇴색되는 단점이 생기더라구요.. 결국 한 가지 방식이 정답이기 보다는 프로젝트 상황에 맞춰 올바른 선택을 하는 능력을 키우는게 맞는거 같습니다.

의견 들려주셔서 감사해요!

2024-10-25 13:28 UTC, kelly6bf approved these changes
아토! 고생 많으셨습니다! 1단계는 이만 머지할게요! 2단계 진행해주세요!

2024-10-25 13:28 UTC, merged