[1단계 - DB 복제와 캐시] 마크(김승현) 미션 제출합니다.
woowacourse/java-coupon pull request #50
Opened 2024-10-18 07:56 UTC by seunghye218

안녕하세요 이든~ 이번에 DB 복제와 캐시 리뷰이 마크입니다~~

1단계 문제 상황인 복제 지연을 해결하기 위해 reader DB에 데이터가 없다면 writer DB를 조회하도록 해봤어요.

잘 부탁드려요~~

2024-10-19 05:21 UTC, PgmJun requested changes
안녕하세요 마크~
구현해주신 내용 잘 보았습니다:)
열심히 구현해주셨네요!
간단한 의견 남겨두었으니 확인 후에 답변 부탁드립니다!

추가로 Replication Lag에 대해서 어떤 고민을 하셨고 어떤 의사결정 과정을 통해 지금 방식이 선택되었는지도 남겨주신다면 더 잘 이해할 수 있었을 것 같아요~
시간이 괜찮으시다면 이 부분도 남겨주시면 더 섬세한 리뷰가 가능할 것 같습니다:)

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/config/DataSourceConfig.java
> +    public static final String READER = "reader";
Enum말고 String을 사용해주신 이유가 궁금합니다!

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/config/DataSourceConfig.java
> +            @Qualifier(READER) DataSource reader
dataSource() 메서드에서 직접 아래와 같이 특정 DB DataSource를 주입해주는데,
별도로 `@Qualifier` 설정을 추가해주신 이유가 있을까요?
`DataSource dataSource = routingDataSource(writerDataSource(), readerDataSource());`

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/MinimumOrderAmount.java
> +            throw new CouponException("최소 주문 금액은 %d원 이상이어야 합니다.".formatted(MIN_AMOUNT));
예외 상황이 다양한데 별도의 Exception으로 구분하지 않고 CouponException 하나만 두어 관리해주신 이유가 무엇인가요?

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/Coupon.java
> +@Entity(name = "coupon")
기본적으로 생성되는 이름과 크게 다르지 않아보이는데, 위와 같이 명시해주신 이유가 있는 지 궁금합니다!

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/Coupon.java
> +        this.category = Category.valueOf(category);
Category 같은 Enum값을 왜 별도의 String으로 받으려고 하셨는지 이유가 궁금합니다!

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/Coupon.java
> +            Long id,
**auto_increment** 되도록 `IDENTITY` 전략을 설정해주신 것으로 보았는데요
외부에서 사용가능한 public 생성자에 id를 열어두게 되면 잘못 사용할 수 있는 가능성이 발생하지 않을까요?

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/CouponName.java
> +        if (name == null || name.isBlank() || name.length() > 30) {
null과 Blank는 Strings.isBlank() 를 사용하면 한 번에 처리할 수 있는 것으로 알고 있습니다~

<img width="621" alt="스크린샷 2024-10-19 13 55 36" src="https://github.com/user-attachments/assets/6d072c93-bbeb-45c2-8952-686795aaf010">

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/CouponName.java
> +        if (name == null || name.isBlank() || name.length() > 30) {
추가로 `길이 제한`과 `null 제한` 은 별도라고 생각이 드는데 validateLength로 관리해주신 이유도 궁금합니다~ 조금은 어색하게 느껴져서요

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final int MAX_AMOUNT_CONSTRAINT = 10000;
CONSTRAINT 라는 네이밍 좋은데요??
고민이 많았던 네이밍 부분이었는데 좋은 네이밍인 것 같습니다 👍👍

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final int MAX_RATE_CONSTRAINT = 20;
만약 3~20% 할인율만 허용하는 제약 외에
또 다른 할인 제약 조건이 발생한다면 어떻게 관리할 수 있을까요?

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        }
이 할인가 제약을 별도의 분기로 관리해주신 이유가 궁금합니다!
OR 연산자로 처리 가능할 것 같고 컨텍스트도 동일한 것 같아서요~!


<img width="491" alt="image" src="https://github.com/user-attachments/assets/9aa25183-64df-4a73-b4f1-d96c90dba77f">

위 Coupon 객체의 검증과 같이 어떤 검증은 OR 연산자로 처리되어 있고
지금 같은 연산은 별도의 분기로 처리되어 있는데 마크의 기준을 들어볼 수 있을까요?

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +            throw new CouponException("발급일은 만료일 보다 같거나 이전이어야 합니다.");
다른 예외들처럼 예외가 발생한 값인 `발급일`, `발료일`을 출력해줘도 더 빠르게 분석이 가능할 것 같은데 어떻게 생각하세요~?

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/MemberCoupon.java
> +    private LocalDateTime expiredAt;
시간까지 관리하시는 이유가 궁금합니다:)
저같은 경우는 몇몇 배달앱들의 쿠폰을 확인하고 다녔는데, 보통은 일자 단위로 쿠폰 발급을 수행해서 시간은 따지지 않더라구요
`nnnn년도 nn월 nn일까지 사용` 이런 구조가 많은데 마크는 시간도 관리해야한다고 생각하신 이유가 궁금했어요

결국 마크도 IssuancePeriod 까지 LocalDateTime을 넘겨서 LocalDate로 변환해서 사용중인것으로 보이는데 Time까지 관리해줄 필요가 있을까요??

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/MemberCoupon.java
> +
다른 도메인과는 다르게 공백이 2칸인 것 같아요!

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/service/coupon/CouponService.java
> +                .orElseGet(() -> getCouponWriter(id));
굿굿이네여:)

2024-10-19 05:21 UTC, PgmJun commented on src/main/java/coupon/support/TransactionSupport.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
해당 전파 레벨에 대해서 설명해주시겠어요?

2024-10-28 03:07 UTC, seunghye218 commented on src/main/java/coupon/config/DataSourceConfig.java
> +    public static final String READER = "reader";
단순히 상수화 하려고 사용했어요. RoutingDataSource 등 다른 클래스에서도 사용할 여지가 있어 Enum으로 분리해볼게요!

2024-10-28 03:33 UTC, seunghye218 commented on src/main/java/coupon/config/DataSourceConfig.java
> +            @Qualifier(READER) DataSource reader
@Qualifier를 의도에 맞게 사용하지 못하고 있었네요.. dataSource에도 메서드 파라미터 주입을 사용하여 유연성을 높여보겠습니다.

2024-10-28 03:40 UTC, seunghye218 commented on src/main/java/coupon/domain/MinimumOrderAmount.java
> +            throw new CouponException("최소 주문 금액은 %d원 이상이어야 합니다.".formatted(MIN_AMOUNT));
현재 Coupon에 관한 코드밖에 없지만 서비스가 커지면서 다양한 도메인이 생기게 되면 모든 상황에 대한 별도의 예외를 구현하면 관리하기 복잡한 면이 있어 그랬습니다!

2024-10-28 03:43 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/Coupon.java
> +@Entity(name = "coupon")
테이블 이름을 명확하게 지정하기 위해 사용했던 저희 프로젝트의 컨벤션을 사용해봤어요.

2024-10-28 03:50 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/Coupon.java
> +            Long id,
좋은 지적 감사해요👍 id는 닫아두도록 하겠습니다.

2024-10-28 04:21 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/Coupon.java
> +        this.category = Category.valueOf(category);
Enum으로 리팩터링하면서 단순하게 변경했었네요. 구현한다면 Enum으로 받을 것 같네요!

2024-10-28 04:25 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/CouponName.java
> +        if (name == null || name.isBlank() || name.length() > 30) {
추가로 말해준 부분에 대해 적용하는 것이 디버깅할 때도 편하겠네요~!

2024-10-28 04:40 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +        }
일관성있게 작성하지 못했네요😅 할인가 제약은 하나의 조건문에서 처리하는 것이 사용자가 여러번 틀리지않게 할 수 있겠어요.

2024-10-28 04:44 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final int MAX_RATE_CONSTRAINT = 20;
제약 조건에 대해 추상화하여 주입하는 방식이 조건 추가 및 테스트에도 유연하게 관리할 수 있을 것 같아요.

2024-10-28 04:53 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +            throw new CouponException("발급일은 만료일 보다 같거나 이전이어야 합니다.");
다른 예외들은 쿠폰을 생성하는데 정확한 수치가 필요했다면 IssuancePeriod의 검증은 어찌보면 당연한 만료일이 발급일 이후여야 하는 정보라고 생각하기에 해당 메시지로 쉽게 이해할 수 있을 것 같아요😄

2024-10-28 05:43 UTC, seunghye218 commented on src/main/java/coupon/domain/coupon/MemberCoupon.java
> +    private LocalDateTime expiredAt;
우선 쿠폰과 다르게 회원 쿠폰의 도메인 설명에서 발급, 만료 '일시'의 정보를 포함한다고 하였기에 시간까지 관리하게 되었어요. 쇼핑몰 도메인의 경우 특정 일시까지 쿠폰 사용이 가능하다는 등 배달 쿠폰과 다른 특성을 가질 수도 있을 것 같아요!

2024-10-28 05:56 UTC, seunghye218 commented on src/main/java/coupon/support/TransactionSupport.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
REQUIRES_NEW 트랜잭션 전파 레벨은 항상 새로운 트랜잭션이 필요할 때 사용하며 기존 트랜잭션이 없으면 새로운 트랜잭션을 생성하고 기존 트랜잭션이 있다면 기존 트랜잭션을 보류시키고 새로운 트랜잭션을 생성해요. 

쿠폰 서비스에서 쿠폰을 조회할 때 reader DB에 쿠폰이 없다면 readOnly가 아닌 새로운 트랜잭션을 생성하여 writer DB에 조회하도록 하기 위해 사용했어요.

2024-10-28 06:06 UTC, seunghye218 commented
writer DB에만 조회하는 방식은 관리자 쿠폰을 생성하고 즉시 조회하는 경우가 전체 조회에 비해 많지 않기 때문에 비효율적이라 생각했어요.
일반 사용자가 아닌 관리자가 관리하는 쿠폰이므로 생성, 조회도 많지 않을 것으로 예상하여 복제지연에 대해서 이와같이 구현하게 되었어요 😄

2024-10-28 14:44 UTC, PgmJun commented on src/main/java/coupon/domain/MinimumOrderAmount.java
> +            throw new CouponException("최소 주문 금액은 %d원 이상이어야 합니다.".formatted(MIN_AMOUNT));
마크의 기준대로라면 Coupon과 관련된 Exception은 모두 CouponException으로 처리한다고 이해했습니다!
그렇다면 만약 특정 Coupon 예외 대해서는 상태코드를 다르게 Response 해야한다고 하면 어떻게 구분해서 처리할 수 있을까요??
한 번 생각해보시면 좋을 것 같네요:)

2024-10-28 14:45 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/Coupon.java
> +@Entity(name = "coupon")
저희 땅콩 팀은 "Default 설정은 따로 명시하지 않는다" 라는 컨벤션을 지키고 있어서 궁금했네요:)
의도가 있었다면 굿입니다!

2024-10-28 14:47 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/IssuancePeriod.java
> +            throw new CouponException("발급일은 만료일 보다 같거나 이전이어야 합니다.");
마크의 의견도 맞는 말이네요:) 굿!

2024-10-28 14:48 UTC, PgmJun commented on src/main/java/coupon/support/TransactionSupport.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
잘 알고 사용하셨는지 검사해봤습니다! ㅋㅋㅋ
잘 알고 계시네요:)

2024-10-28 14:49 UTC, PgmJun commented on src/main/java/coupon/domain/coupon/MemberCoupon.java
> +    private LocalDateTime expiredAt;
마크의 의견도 좋은 의견이네요:)

2024-10-28 14:50 UTC, PgmJun approved these changes
안녕하세요 마크!
마크의 의견도 잘 들었고 리뷰 반영도 잘 해주셔서 이만 STEP1은 머지하겠습니다!!
STEP2에서 만나요:)
고생하셨습니다!! 남은 기간도 화이팅!!!

2024-10-28 14:50 UTC, merged

2024-10-29 01:11 UTC, seunghye218 commented on src/main/java/coupon/domain/MinimumOrderAmount.java
> +            throw new CouponException("최소 주문 금액은 %d원 이상이어야 합니다.".formatted(MIN_AMOUNT));
관련된 상태 코드와 에러 코드 등을 Enum으로 관리하며 ProblemDetail을 사용할 것 같습니다. 이번 미션에서 그 의도를 잘 보여주지 못했네요🥲 좋은 예외처리를 위해 더 고민해보록 하겠습니다!