[1단계 - DB 복제와 캐시] 카고(정민호) 미션 제출합니다.
woowacourse/java-coupon pull request #54
Opened 2024-10-18 08:20 UTC by devhoya97

안녕하세요 산초~ 미션으로 만나니 새롭네요 😄

프로덕션 환경에서 복제 지연으로 인한 문제가 예방하는 방법에 대해 고민해봤는데요. 제가 선택한 방법은 캐시입니다. 
writer DB에 데이터가 들어가는 동시에 캐시에도 데이터가 들어가므로, reader DB에 복제 지연이 발생하더라도 문제가 없을 것이라 판단했어요.
스프링부트에서 제공하는 기본적인 캐시를 사용했으므로, 서버 내부의 메모리를 사용하고 있어서 서버가 다중화됐을 때에는 A 서버 저장해서 캐시가 되었는데 B 서버로 조회가 갔을 때 복제 지연으로 인한 문제가 그대로 생길 것 같아요. 서버가 다중화 되어있다면 Redis와 같이 여러 서버가 함께 바라볼 수 있는 캐시를 사용해야 할 것 같아요. (2,3단계를 진행하면서 필요성이 느껴지면 Redis로 갈아탈 것 같습니다!)

reader DB에서 조회에 실패하면 writer DB에 접근하는 방법도 생각해봤는데, 최근에 만든 쿠폰일수록 접근할 가능성이 높으므로 복제 지연 문제가 아니더라도 캐시를 하는게 합리적이라고 판단했어요.

리뷰 잘 부탁드립니다 :)

2024-10-19 18:33 UTC, nayonsoso requested changes
안녕하세요 카고!🐈
잘 지내고 계신가요 ㅎㅎ 리뷰로 만나게 되어 반갑습니다.
이번 미션의 본질이 무엇일까~ 생각을 해보니 
1) 서로 다른 데이터 소스를 사용할 때 이를 설정해보는 것
2) 복제 지연을 해결하는 과정을 깊이 고민해보는 것
이라 생각을 했습니다. 그래서 코멘트를 이것들 위주로 남겨봤어요😊
그럼 남은 단계도 잘 부탁드리겠습니다🙇🏻‍♀️

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +}
[학습을 위한 질문]
LazyConnectionDataSourceProxy을 사용하셨군요! 이것이 어떤 이점을 제공해서 사용하셨나요?

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +        Map<Object, Object> dataSources = new HashMap<>();
Object 보다는 타입 안정성을 위해서 구체적인 타입을 명시하는게 좋을 것 같아요😊

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +    @DependsOn({"writerDataSource", "readerDataSource"})
`@DependsOn` 어노테이션을 사용하셨군요! 이게 없어도 잘 동작하는데, 달아주신 이유는 무엇인가요?

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/domain/DiscountAmount.java
> +    }
예외 메서지에 '1000원' 이라는 구체적인 값이 들어갔네요,
할인 최대, 최소 금액이 바뀌면 이 예외 메세지까지 바꿔줘야 할 것 같아요.
이걸 해결하도록 코드를 바꿔볼 수 있을 것 같아요!

2024-10-19 18:33 UTC, nayonsoso commented on src/test/java/coupon/domain/DiscountAmountTest.java
> +    }
위 코멘트와 같은 맥락으로, 저는 DisplayName 에 구체적인 값이 들어가지 않게 노력하는 편이에요. 예를 들어서 "할인 금액이 정해진 범위를 벗어나면 예외를 발생시킨다" 처럼 바꿔볼 수 있을 것 같아요.
다만 이것은 취향의 영역일 수 있으니 참고만 해주셔도 괜찮아요😊

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/service/CouponService.java
>          return couponRepository.findById(id)
[생각을 듣고 싶은 부분]
이 커밋에서 getCoupon 함수 위의 `@Transactional(readOnly = true)`를 제거해준 이유는 무엇인가요?

제 생각에는 cache 를 사용한 조회를 함에도 불구하고, 
`@Transactional(readOnly = true)`를 사용하면 변경 감지 기능을 사용하지 않기 때문에 
1/ 값을 변경하는 개발자의 실수가 있더라도 반영되지 않아 안전하다는 점
2/ 변경 감지 기능에 사용되는 리소스를 readOnly 에서는 사용하지 않기 때문에 성능이 더 좋을 것이라는 점
때문에 `@Transactional(readOnly = true)` 를 달아주는게 더 좋을 것 같아요😊

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/service/CouponService.java
> +        return couponRepository.save(coupon);
이런게 있군요 배워갑니다!! 😲

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +        router.setDefaultTargetDataSource(writerDataSource);
[학습을 위한 질문]
`ReadOnlyDataSourceRouter router`의 default Target DataSource 로 writerDataSource를 지정하는 것은 얼핏 보면 모순적으로 보여요. 그럼에도 이렇게 설정해줄 필요가 있는 것은 무엇 때문일까요?

2024-10-19 18:33 UTC, nayonsoso commented on src/main/java/coupon/CouponApplication.java
>      public static void main(String[] args) {
[반대를 위한 반대]
복제 지연 문제를 해결하기까지 카고도 많은 고민을 했을 것 같아요!
그래서 카고의 방법이 잘못되었다는 것은 아니지만, 누군가 이런 의문을 제기한다면 어떻게 대답할지 궁금해서 한가지 말씀을 드려봐요.

이 시스템의 인프라 구조는 'reader' 와 'writer' DB를 따로 둘 만큼 규모가 큰 서비스예요.
따라서 여러개의 서버가 존재하는 것은 필연적일 것 같아요.
카고가 앞서서 '여러 서버가 있을 경우 외부 캐시서버를 사용하겠다'고 했는데, 아마 반드시 적용이 되는 상황 같아요.

2024-10-24 03:46 UTC, devhoya97 commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +}
DataSource를 결정할 때, readOnly이면 reader, 그렇지 않으면 writer를 선택해야하는데, 이 과정에서 LazyConnectionDataSourceProxy의 도움이 필요했기 때문입니다! LazyConnectionDataSourceProxy가 없으면 `@Transactional(readOnly=true)`를 확인하기 전에 DataSource를 결정해야하므로 의도한대로 DataSource를 맵핑시키기 어려운 것으로 알고 있습니다!

2024-10-24 03:54 UTC, devhoya97 commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +        Map<Object, Object> dataSources = new HashMap<>();
Map<DataSourceType, DataSource>과 같이 구체적인 타입을 명시해달라는 말씀이겠죠?! 시도해봤는데 아래 메서드를 사용할 때 매개변수로 해당 맵을 넘겨주게 되는데, 매개변수의 타입이 Map<Object, Object> 를 받고 있어서 컴파일오류가 발생하네요...! 

```java
	public void setTargetDataSources(Map<Object, Object> targetDataSources) {
		this.targetDataSources = targetDataSources;
	}
```

2024-10-24 08:22 UTC, devhoya97 commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +    @DependsOn({"writerDataSource", "readerDataSource"})
참고한 블로그에 `@DependsOn`이 달려있길래 쓰기전에 잠깐 고민했는데요, DataSource라는 같은 타입의 빈을 writerDataSource, readerDataSource, routingDataSource, dataSource라는 이름으로 총 4개나 등록하고 있으니, 스프링컨테이너에서 각 빈을 생성할 때 어떤 빈을 먼저 생성해야 DI 과정에서 문제가 발생하지 않는지 판단하기 어렵나? 생각했어요.

근데 말씀해주신 것처럼 `@DependsOn`을 떼고 테스트코드를 돌려도 돌아가는걸 보니, 없어도 되나보네요 😅

2024-10-24 08:35 UTC, devhoya97 commented on src/main/java/coupon/domain/DiscountAmount.java
> +    }
String.format을 사용해서 개선했습니다!

2024-10-24 08:40 UTC, devhoya97 commented on src/test/java/coupon/domain/DiscountAmountTest.java
> +    }
좋은 의견인 것 같습니다! 도메인 특성상 할인 금액의 최소, 최댓값은 변경될 가능성이 꽤 높을 것 같네요. 도메인 조건에서 변경이 생겼을 때 코드에 변경지점이 적어질 수 있다는 관점에서 동의합니다!

2024-10-24 08:43 UTC, devhoya97 commented on src/main/java/coupon/service/CouponService.java
>          return couponRepository.findById(id)
앗 사실 아래처럼 클래스 레벨에 readyOnly = true를 적용하다보니, 빠졌어요 ㅎㅎ

```java
@Service
@Transactional(readOnly = true)
public class CouponService {
```

2024-10-24 08:43 UTC, devhoya97 commented on src/main/java/coupon/service/CouponService.java
> +        return couponRepository.save(coupon);
저도 이번에 처음 학습해보았습니다 😄

2024-10-24 08:47 UTC, devhoya97 commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +        router.setDefaultTargetDataSource(writerDataSource);
사실 클래스명의 의도는 readOnly = true가 달려있는 메서드와 그렇지 않은 메서드를 라우팅하는 라우터인데요, 다시 읽어보니 리뷰어가 헷갈릴 수 있는 클래스명을 사용해버린 것 같네요..!

`DataSourceRouter`라는 이름으로 클래스명을 변경했습니다!

2024-10-24 09:06 UTC, devhoya97 commented on src/main/java/coupon/CouponApplication.java
>      public static void main(String[] args) {
> 이 시스템의 인프라 구조는 'reader' 와 'writer' DB를 따로 둘 만큼 규모가 큰 서비스예요.
따라서 여러개의 서버가 존재하는 것은 필연적일 것 같아요.

사실 reader와 writer DB가 따로 있는 것은 SPOF 때문이라고 생각했어요. 서비스 규모가 커서 명시적으로 여러개의 서버를 사용하고 있다는 요구사항이 있었다면, 복제지연 문제를 해결하기 위해 in memory cache는 고려하지 않았을 것 같습니다..!

> 모든 읽기 요청에 대해서 외부 캐시 서버와 통신하기 위한 네트워크 오버헤드가 발생할 수 있어요.
카고는 이에 대해서 어떻게 생각하시나요?

모든 읽기 요청이 외부 서버와 통신하기 위한 네트워크 오버헤드가 발생한다는게 무슨 뜻인지 잘 이해하지 못했어요. in memory cache를 사용하지 않는 이상 읽기 요청은 외부 캐시서버 또는 외부 DB서버로 가야하니까 네트워크를 타야하는 것은 어쩔 수 없다고 생각합니다. 혹시 제가 질문을 잘못 이해했을까요...?!

2024-10-26 15:46 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +}
잘 학습해주셨네요👏👏

2024-10-26 15:49 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +        Map<Object, Object> dataSources = new HashMap<>();
아하 그렇네요😅 지금처럼 하는게 맞는 것 같습니다~

2024-10-26 16:10 UTC, nayonsoso commented on src/main/java/coupon/config/datasource/DataSourceConfig.java
> +    @DependsOn({"writerDataSource", "readerDataSource"})
> DataSource라는 같은 타입의 빈을 writerDataSource, readerDataSource, routingDataSource, dataSource라는 이름으로 총 4개나 등록하고 있으니, 스프링컨테이너에서 각 빈을 생성할 때 어떤 빈을 먼저 생성해야 DI 과정에서 문제가 발생하지 않는지 판단하기 어렵나?

스프링에서 빈의 등록 순서는, 'A가 생성자의 인자로 B를 받고 있으면, B를 생성 후 A를 생성' 하는 식이라 알고 있어요.
그런데 이렇게 명시적인 의존관계가 없음에도, 빈의 생성 순서를 강제하고 싶을 때 쓰는 것이 `@DependsOn` 입니다.

그래서 위 코드의 경우에는
1/`@Qualifier`가 있어서 빈의 이름이 명시되지 않는 상황도 아니고
2/ 인자로 받고 있어서 빈의 생성 순서가 보장되기 때문에
`@DependsOn`을 제거해도 잘 돌아가는 것 같아요~ 👍

2024-10-26 16:12 UTC, nayonsoso commented on src/main/java/coupon/service/CouponService.java
>          return couponRepository.findById(id)
앗 ㅋㅋ 확인했습니다🙆🏻‍♀️

2024-10-26 16:14 UTC, nayonsoso commented on src/main/java/coupon/domain/DiscountAmount.java
> +    }
앗 그런데 수정 과정에서 테스트가 깨진 것 같아요🥲

![image](https://github.com/user-attachments/assets/1918d33c-bee4-4e66-bdf2-4976e33e9b94)

2024-10-26 16:33 UTC, nayonsoso commented on src/main/java/coupon/CouponApplication.java
>      public static void main(String[] args) {
이 부분은 제가 '모든 읽기 요청'을 강조해서, 헷갈리게 질문을 드렸던 것 같아요😅
(스미마셍..)

제 질문의 의도는, 
'로컬 캐시 → 리모트 캐시로 바뀌게 되면 추가적인 네트워크 오버헤드가 발생할텐데 그럼에도 현 구조를 유지할 것인가?'
에 대한 내용이었습니다 ㅎㅎ
로컬 캐시에서 얻는 '빠르다'는 이점이, 리모트 캐시에서는 흐려질 수 있으니깐요.

그리고 이 질문에 대해서는 카고가 답변을 이미 해주신 것 같아 넘어갑니다👍👍
> 명시적으로 여러개의 서버를 사용하고 있다는 요구사항이 있었다면, 복제지연 문제를 해결하기 위해 in memory cache는 고려하지 않았을 것 같습니다..!

2024-10-26 16:38 UTC, nayonsoso requested changes
안녕하세요 카고 🐈 데모데이 준비하시느라 수고 많으셨습니다. 데모데이가 끝나고 한가로운 주말 보내고 있으시길 바랍니다 ㅎㅎ 이번에 바로 머지를 하려 했는데요, 테스트가 깨지는 부분이 있네요..!😵 테스트 고치고 다시 리뷰 요청 주시면 머지하겠습니다~

2024-10-27 04:07 UTC, devhoya97 commented on src/main/java/coupon/domain/DiscountAmount.java
> +    }
헉 그렇네요.. `%,d`를 사용해서 1000단위로 ,가 붙도록 변경하여 테스트 코드 통과시켰습니다!

2024-10-27 06:28 UTC, nayonsoso approved these changes
테스트 통과 확인했습니다😊
이번 단계에서 이야기할 부분은 다 한 것 같아서, 이만 approve & merge 합니다.
다음 단계도 파이팅입니다!!

2024-10-27 06:28 UTC, merged