[1단계 - DB 복제와 캐시] 뽀로로(조경찬) 미션 제출합니다.
woowacourse/java-coupon pull request #70
Opened 2024-10-18 08:53 UTC by jcoding-play

아루.. 프로젝트 준비로 시간이 좀 모자라 서둘러 했습니다.ㅎㅎ  
커멘트 추후 작성할게요 리뷰 요청 먼저 하겠습니다!

2024-10-18 11:32 UTC, donghoony requested changes
안녕하세요 뽀로로~ 아루입니다 😁

이번 미션을 진행하면서 참 놀랐던 게 바닥부터 짜야했던 점이었는데요, 그래서 도메인 설계부터 서비스 및 복제 지연 문제까지 커밋을 보면서 함께 달려가는 느낌을 받았습니다.
뽀로로가 도메인에서 검증, 책임을 잘 나누려고 노력하는 모습을 보인 것 같아 이와 관련된 리뷰를 우선 주로 달아 두었어요. 레벨 1, 2에서 많이 했지만 아직도 어렵습니다 ㅎㅎ

도메인 위주의 피드백이지만, 아시다시피 해결해야하는 문제는 복제 지연에 대한 문제이고 이를 탐구하는 게 목적입니다. 해당 피드백은 가볍게 소화해보시고 이해 안 되는 부분이 있다면 DM이나 따로 댓글을 남겨 주세요. 물론 복제 쪽 피드백도 있습니다 👍🏻 

다음 리뷰 요청 때에는 반영과 더불어 디스크립션에 선택하게 된 이유도 함께 적어주시면 감사하겠습니다 🙇🏻 데모데이가 다가오는데 잘 준비하고 잠실에서 봅시다 🫰 

(이전에 [코레아 팀 PR](https://github.com/woowacourse-teams/2024-corea/pull/610#discussion_r1801315976)에서도 이야기했던 내용이 있었네요! 재밌게 읽었습니다 💯)

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/Name.java
>  public class Name {
예외 메시지 등에서는 쿠폰이라는 이름이 등장하네요? `CouponName`과 같이 사용처에 따른 네이밍을 해보면 어떨까요?

2024-10-18 11:32 UTC, donghoony commented on src/test/java/coupon/domain/NameTest.java
> +        assertThatThrownBy(() -> new Name("1234567890123456789012345678901"))
`"a".repeat(31)` 👍🏻

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/DiscountAmount.java
> +    private static final int MAX_DISCOUNT_AMOUNT = 10_000;
한 번 생각해볼만한 점:
도메인 규칙과 서비스 정책을 다르게 생각해보면 어떨까요? 도메인은 변하지 않는 성질을 가지고, 재사용성이 뛰어나야 한다고 생각해요. 만약 다른 곳에서 최소 할인 금액을 서로 다르게 설정한다면, 도메인에서부터 수정 사항이 발생할 수 있겠습니다. 아래는 제가 재미있게 읽었던 <실용주의 프로그래머>를 발췌해 보았어요.

---

>신규 인사 관리 시스템에 대하여 상의하는 도중 의뢰인이 다음과 같이 말했다고 해 보자. “직원의 기록은 해당 직원의 관리자와 인사팀만 열람할 수 있습니다.” 이 진술이 진짜로 요구 사항일까? 오늘은 그럴 수도 있다. 하지만 이 단언하는 진술 속엔 사업 정책이 포함되어 있다.

>사업 정책인가, 요구 사항인가? 그 차이는 비교적 미묘하다. 하지만 이 차이가 개발자에게는 중대한 의미가 있다. 만약 요구 사항이 “인사팀에서만 직원 기록을 열람할 수 있다.”는 식으로 되어 있다면 개발자는 애플리케이션이 이 데이터에 접근할 때마다 인사팀인지 확인하는 코드를 작성할 것이다.
하지만 요구 사항이 “권한이 있는 사용자만이 직원 기록에 접근할 수 있다.”는 식이라면 개발자는 아마도 일종의 접근 관리 시스템을 설계하고 구현할 것이다. 그러면 **정책이 바뀔 때(실제로 바뀐다) 시스템의 메타데이터만 업데이트하면 된다**. 실제로 이런 식으로 요구 사항을 수집하면 자연스럽게 메타데이터를 지원하는 잘 분리된 시스템이 만들어질 것이다. 사실 여기엔 일반 원칙이 있다.

>정책은 메타데이터다.

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/OrderAmount.java
> +    private static final int MAX_ORDER_AMOUNT = 100_000;
ditto, 하지만 도메인을 유연하게 작성하는 게 이번 미션에서의 핵심 목표는 아니니 생각만 하는 것으로도 충분합니다 😁

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/MinOrderAmount.java
> +    private final int minOrderAmount;
상수와 인스턴스 필드 사이 개행해 주세요~!

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/DiscountAmount.java
> +    private static final int MAX_DISCOUNT_AMOUNT = 10_000;
이 클래스에서 도메인의 역할은 어떤 것이 할 수 있을까요? 정말 도메인이 될 정도의 역할일까요? 도 하나의 생각해볼 점이겠습니다. `돈은 음수가 될 수 없다`는 정책에 따라 변하는 명제일까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/Period.java
> +public class Period {
기간 객체 도출 좋네요! 💯

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/domain/Period.java
> +        }
이런 부분은 정책에 따라서 절대 변하지 않는 불변성을 띠고 있죠 👍🏻

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/member/domain/Member.java
> +@AllArgsConstructor
작성하신 엔티티에 대한 전반적인 리뷰입니다:
1. 전체 인자 생성자가 필요한가요?
2. Id가 같은 서로 다른 엔티티는 같은 것으로 보아야 할까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/coupon/domain/DiscountAmount.java
> +    private int discountAmount;
`final`을 붙이는 게 좋다면.. 도메인과 엔티티를 분리하는 것도 하나의 방법이겠죠 👍🏻

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/config/DataSourceConfig.java
> +    protected static final String READ = "read";
`protected`라면 상속받아 사용하는 클래스가 존재할까요? 😮

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/config/DataSourceConfig.java
> +        DataSource readDataSource = readDataSource();
`@DependsOn`과 같은 명시적 순서 지정이 좋을까요, 아니면 의존성 주입에서의 자동 순서 지정이 좋을까요? `@Qualifier`를 통해 어떤 이름의 빈을 가져올지 정할 수 있고, 그렇게 한다면 해당 빈이 등록된 뒤에 주입이 일어나게 됩니다. 개발자가 순서를 신경쓰면 인지부하가 커진다고 생각해서요!

```suggestion

    public DataSource routeDataSource(@Qualifier("writeDataSource") DataSource writeDataSource,
   // ...
```

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/config/DataSourceConfig.java
> +        return Map.of(WRITE, writeDataSource, READ, readDataSource);
`Map.of()` 내부 개행을 통해 Key-Value를 보다 잘 보여주면 어떨까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/resources/application.yml
> +        hbm2ddl.auto: update
`validate`로 그대로 두고 사용할 수는 없었을까요? 😉

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/coupon/service/CouponService.java
> +@Transactional(readOnly = true)
읽을 때 살~짝 헷갈렸는데요, 전체 `readOnly`가 걸려있긴 하지만 읽다가 한 번 메서드 위를 슥 보게 되는 듯했어요. 메서드에 달리는 `Transactional` 상태에 따라 `DataSource`가 달라질 테니, 메서드마다 명시해보는 건 어떨까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/membercoupon/domain/MemberCoupon.java
> +    private Member member;
(생각해볼 점) 
1. `MemberCoupon`에서 `Coupon`을 얼마나 많이 알아야 할까요?
2. `MemberCoupon`에서 `member`를 얼마나 많이 알아야 할까요? 
3. 누구와 더 연관있는지에 대한 경중을 따져볼 수 있을까요?
4. `MemberCoupon`에게 `Member`로 향하는 영구적인 통로를 열어두어도 괜찮을까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/coupon/service/CouponReader.java
> +@Transactional(readOnly = true)
메서드가 하나 뿐이고, 하나의 메서드가 `readOnly = false`이니 이 어노테이션은 불필요하지 않을까요?

2024-10-18 11:32 UTC, donghoony commented on src/main/java/coupon/coupon/service/CouponService.java
>      }
Read DB를 조회하고 존재하지 않는다면 Write DB를 조회하는 전략을 선택하셨네요!

1. 왜 이런 전략을 선택했나요?
2. 업데이트가 일어나는 경우에는 ReadDB에 이미 존재하기 때문에 업데이트 전 값을 가져오게 될 듯한데, 이 경우에는 어떻게 해결할 수 있을까요?
3. 다른 전략은 무엇이 있었을까요?

2024-10-18 11:32 UTC, donghoony commented on src/test/java/coupon/coupon/service/CouponServiceTest.java
> +        assertThat(savedCoupon).isNotNull();
```java
@Slf4j
public class ReadOnlyDataSourceRouter extends AbstractRoutingDataSource {

    @Override
    protected Object determineCurrentLookupKey() {
        if (TransactionSynchronizationManager.isCurrentTransactionReadOnly()) {
            log.info("[ROUTING] Routing to read database.");
            return DataSourceConfig.READ;
        }
        log.info("[ROUTING] Routing to write database.");
        return DataSourceConfig.WRITE;
    }
}
```

```java
@ExtendWith(OutputCaptureExtension.class)
class CouponServiceTest {
    private static final Logger log = LoggerFactory.getLogger(CouponServiceTest.class);

    @Test
    void 복제지연테스트(CapturedOutput output) {
        log.info("Test start");
        CouponRequest request = CouponFixture.COUPON_CREATE_REQUEST();

        log.info("[TEST] Save");
        CouponResponse response = couponService.create(request);

        log.info("[TEST] Read 1");
        Coupon savedCoupon = couponService.getCoupon(response.id());

        log.info("[TEST] Read 2");
        couponService.getCoupon(response.id());

        assertThat(savedCoupon).isNotNull();
    }
    // ...
}
```
위와 같이 테스트를 변형하고, 로그를 살펴보면 아래와 같습니다:
```
2024-10-18T20:29:46.932+09:00  INFO 28710 --- [    Test worker] c.coupon.service.CouponServiceTest       : Test start
2024-10-18T20:29:46.932+09:00  INFO 28710 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Save
2024-10-18T20:29:46.946+09:00  INFO 28710 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to write database.
2024-10-18T20:29:46.957+09:00  INFO 28710 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Read 1
2024-10-18T20:29:46.972+09:00  INFO 28710 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to read database.
2024-10-18T20:29:46.990+09:00  INFO 28710 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to write database.
2024-10-18T20:29:46.997+09:00  INFO 28710 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Read 2
2024-10-18T20:29:46.998+09:00  INFO 28710 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to read database.
2024-10-18T20:29:46.999+09:00  INFO 28710 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to write database.
```

매번 Read DB로 찌르더라도 Write를 한 번 더 찌르네요. 이유를 찾아보고 해결해 볼까요?

2024-10-30 09:23 UTC, jcoding-play commented on src/main/java/coupon/domain/Name.java
>  public class Name {
패키지명에서 이미 coupon의 사용처가 드러나기 때문에 코드 내에서 coupon을 반복적으로 언급하는 것이 중복으로 느껴졌습니다. 
하지만 나중에 Member의 이름도 원시값으로 포장하게 된다면, CouponName처럼 구체적으로 네이밍하는 것이 유지보수에 더 도움이 될 것 같습니다.

말씀 주신 대로 수정하겠습니다! 👍

2024-10-30 09:24 UTC, jcoding-play commented on src/test/java/coupon/domain/NameTest.java
> +        assertThatThrownBy(() -> new Name("1234567890123456789012345678901"))
오 까먹었던 함수... 👍
감사합니다!

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/domain/DiscountAmount.java
> +    private static final int MAX_DISCOUNT_AMOUNT = 10_000;
정말 중요한 포인트를 짚어주신 것 같아요! 
할인 금액이나 최소 주문 금액, 할인율 등은 도메인 정책이라기보다 서비스 정책에 가까운 부분이네요! 👍👍

아무 생각 없이 이 정책들을 도메인 내부 검증 로직에 넣었는데, 앞으로는 이런 부분들을 잘 구분하는 것이 중요할 것 같습니다. 
좋은 리뷰 감사드립니다!

>`돈은 음수가 될 수 없다`는 정책에 따라 변하는 명제일까요?

👍 변하지 않는 명제입니다. 수정했습니다!~~

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/domain/OrderAmount.java
> +    private static final int MAX_ORDER_AMOUNT = 100_000;
이 부분도 같이 수정했어요~! 👍

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/domain/Period.java
> +        }
맞아요~! 덕분에 배워갑니당~

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/member/domain/Member.java
> +@AllArgsConstructor
>1. 전체 인자 생성자가 필요한가요?

이 부분은 저희 코레아 팀의 컨벤션에 맞춰 전체 인자 생성자를 사용하고 있습니다. 
꼭 필요한 것은 아니지만, 엔티티 필드가 많아질 경우 this() 생성자 체이닝을 통해 코드를 간략하게 유지할 수 있어 장점이 있다 느껴져서 항상 포함하고 있어요~! 😀

>2. Id가 같은 서로 다른 엔티티는 같은 것으로 보아야 할까요?

Id가 같은 엔티티는 동일한 것으로 보는 게 맞다고 생각합니다. 

근데 프로젝트를 진행하면서 Id 기반으로 동등성을 비교할 때 예상치 못한 문제가 생긴 경험이 있습니다. 아루도 혹시 이와 비슷한 경험이 있으신가요?

기본 equals와 hashCode는 getClass() 메서드를 사용하는데, JPA에서 성능 최적화를 위해 지연 로딩(lazy loading)을 사용할 때 프록시 객체가 생성되어 getClass() 메서드 결과가 달라질 수 있다는 문제를 확인했었습니다.
[관련 블로그 글](https://ksh-dev.tistory.com/78)

instanceof를 사용하여 해결할 수도 있지만, 이로 인해 엔티티 간 동등성 비교를 되도록 피하게 되었습니다. 필요하지 않다면 equals를 재정의하지 않는 편입니다. 아루는 이 부분에 대해 어떻게 생각하시는지 궁금합니다! 🧐

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/config/DataSourceConfig.java
> +    protected static final String READ = "read";
```java
public class ReadOnlyDataSourceRouter extends AbstractRoutingDataSource {

    @Override
    protected Object determineCurrentLookupKey() {
        if (TransactionSynchronizationManager.isCurrentTransactionReadOnly()) {
            return DataSourceConfig.READ;
        }
        return DataSourceConfig.WRITE;
    }
}
```

같은 패키지 내부에 있는 ReadOnlyDataSourceRouter에서 사용하고 있어서 protected로 정의해두었어요~!

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/config/DataSourceConfig.java
> +        DataSource readDataSource = readDataSource();
수정했습니다!~ 👍

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/config/DataSourceConfig.java
> +        return Map.of(WRITE, writeDataSource, READ, readDataSource);
코드 라인을 너무 줄이려고만 했네요~ 수정했습니다! 😀

2024-10-30 09:24 UTC, gyungchan-jo commented on src/main/java/coupon/coupon/service/CouponService.java
> +@Transactional(readOnly = true)
>메서드에 달리는 Transactional 상태에 따라 DataSource가 달라질 테니, 메서드마다 명시해보는 건 어떨까요?

좋은 것 같습니다~! 😀

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/membercoupon/domain/MemberCoupon.java
> +    private Member member;
오... 👍 제가 아루의 의도를 제대로 이해한 건지는 모르겠지만, 제가 이해한 바로는 MemberCoupon이 회원에게 발급된 하나의 쿠폰을 의미하므로, @ManyToOne 관계가 아니라는 뜻으로 해석했습니다. 혹시 맞을까요?

이렇게 이해한 바를 토대로 한번 작성해보겠습니다!

회원에게 발급된 쿠폰이라면 하나의 쿠폰은 여러 회원에게 발급될 수 있기 때문에 `@ManyToOne` 관계가 적절해 보입니다. 그러나 회원은 발급된 하나의 쿠폰과만 연관이 있으므로 `OneToOne` 관계로 설정하는 것이 맞겠네요.

또한, 현재 Member 엔티티 값을 그대로 포함하고 있어 MemberCoupon과 Member 간에 강한 결합이 형성된 상태입니다. 이를 해결하기 위해 memberId만 포함하도록 수정했습니다!

>누구와 더 연관있는지에 대한 경중을 따져볼 수 있을까요?

이 부분에 대해서는 잘 이해가 되지 않아 혹시 질문의 의도가 무엇인지 알려줄 수 있나요?? 🧐

2024-10-30 09:24 UTC, jcoding-play commented on src/main/java/coupon/coupon/service/CouponReader.java
> +@Transactional(readOnly = true)
사실 이 부분도 저희 코레아팀의 컨벤션이였는데요.
Writer 클래스만을 분리하지 않는 이상 Service 레이어에서는 `@Transactional(readOnly = true)`을 기본적으로 작성하기로 정해서, 자연스레 적게 되었습니다ㅎㅎ 😃

아루 말대로 현재 코드에서 불필요한 부분이니 제거하도록 할게요!~

2024-10-30 16:41 UTC, jcoding-play commented on src/test/java/coupon/coupon/service/CouponServiceTest.java
> +        assertThat(savedCoupon).isNotNull();
```
2024-10-31T01:18:37.501+09:00  INFO 37417 --- [    Test worker] c.coupon.service.CouponServiceTest       : Test start
2024-10-31T01:18:37.502+09:00  INFO 37417 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Save
2024-10-31T01:18:37.522+09:00  INFO 37417 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to write database.
2024-10-31T01:18:37.541+09:00  INFO 37417 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Read 1
2024-10-31T01:18:37.565+09:00  INFO 37417 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to read database.
2024-10-31T01:18:37.598+09:00  INFO 37417 --- [    Test worker] c.coupon.service.CouponServiceTest       : [TEST] Read 2
2024-10-31T01:18:37.598+09:00  INFO 37417 --- [    Test worker] coupon.config.ReadOnlyDataSourceRouter   : [ROUTING] Routing to read database.
```

저는 근데 정상적으로 read db에서만 호출하고 있어요..
혹시 이 부분에 대한 이유를 아시나요?? 😭😭😭

2024-10-30 17:21 UTC, jcoding-play commented on src/main/java/coupon/coupon/service/CouponService.java
>      }
>1. 왜 이런 전략을 선택했나요?

밑에서 다시 설명드리겠지만, 데이터의 일관성과 성능을 고려하여 선택하였습니다. 
Write DB와 Read DB를 분리하여 읽기 성능을 최적화하면서도, 동기화 지연으로 인해 발생할 수 있는 문제를 최소화하려고 하였습니다. 이렇게 함으로써 데이터 조회 시 최신 정보를 보장하면서도 시스템의 전반적인 성능을 향상시킬 수 있다 생각했어요!

>2. 업데이트가 일어나는 경우에는 ReadDB에 이미 존재하기 때문에 업데이트 전 값을 가져오게 될 듯한데, 이 경우에는 어떻게 해결할 수 있을까요?

이러한 경우 생각해볼 수 있는 해결방법으로는 업데이트가 일어났을 경우, 일정 시간동안(현재 저희의 미션에선 1초 이상)은 WriteDB에서 읽도록 코드를 수정해볼 수 있을 것 같아요! 

```java
@Service
@RequiredArgsConstructor
public class CouponService {
    ....
    private LocalTime lastUpdatedTime;

    @Transactional
    public void update(CouponUpdateRequest request) {
        ... // 업데이트 로직 수행
        lastUpdatedTime = LocalTime.now(); // 업데이트한 시간 기록
    }

    @Transactional(readOnly = true)
    public Coupon getCoupon(long couponId) {
        // 업데이트 후 일정 시간이 지나지 않았으면 WriteDB에서 조회
        if (LocalTime.now().isBefore(lastUpdatedTime.plusSeconds(1))) {
            return couponReader.getCouponFromWriteDb(couponId);
        }

        return couponRepository.findById(couponId)
                .orElseGet(() -> couponReader.getCouponFromWriteDb(couponId));
    }
```
대강 생각난대로 코드를 구현해보았는데 틀린 부분이 있을 수 있어요...ㅎㅎ 🤣
아니면 비슷하게 일정 시간동안 데이터를 캐시에 저장하여 조회하는 방법도 있다 생각합니다.

>3. 다른 전략은 무엇이 있었을까요?

다른 전략으로는 모든 조회를 Write DB에서 처리하는 방법이 있습니다. 하지만 이 경우 Write DB의 부하가 증가하고 성능이 저하될 수 있기 때문에 효율적이지 않다 느껴졌습니다.

또한, 다른 방법으로는 동기화 지연 문제를 해결하는 거라 생각했습니다. 저희 미션에서는 `docker/reader/docker-entrypoint.sh 파일`을 수정하는 것이겠네요~ 사실 가장 좋은 방법이라 생각하긴 했고, 실제 동기화 지연 문제가 현업에서 잘 일어날까라는 고민도 있었어요. 의심이 되어 실제 인터넷에 찾아본 결과, 실제로 동기화 지연 문제가 빈번하게 발생한다는 점을 확인하여, 이 방식을 선택하지 않기로 했습니다.

마지막으로 생각해볼 수 있는 다른 전략은 캐시를 이용하는 것인데, 캐시를 이용할만큼 생성된 쿠폰을 바로 조회하는 경우가 드물다 판단하고, 이점이 그다지 크지 않다고 느껴졌어요. 

결론적으로, Read DB에서 데이터를 조회하지 못할 경우 Write DB에서 조회하는 방식을 선택하여 조회 성능을 최적화하고, Write DB의 부하 문제를 해결할 수 있다 생각했습니다~!

2024-10-31 00:55 UTC, donghoony commented on src/main/java/coupon/member/domain/Member.java
> +@AllArgsConstructor
이건 별개의 이야기 아닐까요? 두 개의 엔티티는 내부 속성이 다르더라도 id가 같으면 같은 객체로 보아야 합니다. id는 `identifier`, 식별자와 같기 때문이예요 (주민등록번호와 같은 개념)

만약 내부 값을 비교하고 싶다면, 엔티티와 도메인의 분리 신호가 아닐까요? 혹은 `equals`가 아닌 다른 메서드를 열어야 하지 않을까요? 🤔

2024-10-31 00:56 UTC, donghoony commented on src/main/java/coupon/member/domain/Member.java
> +@AllArgsConstructor
저는 Hibernate의 상속을 통한 엔티티 Lazy Loading을 피하기 위해 `instanceof`를 활용합니다 😁

2024-10-31 01:03 UTC, donghoony commented on src/main/java/coupon/membercoupon/domain/MemberCoupon.java
> +    private Member member;
관계 자체를 정의할 필요가 있는가? 에 대한 이야기였습니다. 객체로 참조하는 순간 클래스 간 강한 결합이 이루어지고, 이는 결국 하나의 변화가 다른 쪽으로 전파됨을 의미해요.
저는 생명 주기가 온전히 일치하지 않는다면 id로 참조하는 편이예요. 그 맥락에서 제 질문에 자답하자면:

> MemberCoupon에서 Coupon을 얼마나 많이 알아야 할까요? MemberCoupon에서 member를 얼마나 많이 알아야 할까요?

쿠폰의 생성과 소멸, 회원의 생명과 소멸, 그리고 회원이 발급한 쿠폰의 생성과 소멸은 모두 생명주기를 다르게 합니다. 따라서 `MemberCoupon`에서 `Member`와 `Coupon`을 알 필요가 없습니다. 아래와 같이 `id`로만 참조해도 충분합니다.

```java
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "coupon_id", nullable = false)
    private Long couponId;

    @Column(name = "member_id", nullable = false)
    private Long memberId;
```

> 누구와 더 연관있는지에 대한 경중을 따져볼 수 있을까요?

처음에 질문했을 때에는, 멤버보다는 쿠폰이 더 `MemberCoupon` 성격에 가깝다고 생각했어요. 회원이 발급한 쿠폰에서 회원의 이름, 가입 일시 등을 알아내는 것이 일반적이지는 않다고 생각했어요.

> MemberCoupon에게 Member로 향하는 영구적인 통로를 열어두어도 괜찮을까요?

변경에 대한 전파가 필드를 통한다는 걸 생각해보아도 좋겠습니다 😁

2024-10-31 01:03 UTC, donghoony commented on src/main/java/coupon/membercoupon/domain/MemberCoupon.java
> +    private Member member;
2단계에서는 `쿠폰과 회원에게 발급된 쿠폰의 저장소가 분리될 예정이므로, 두 테이블을 조인할 수 없다.`라는 조건이 있으니 한 번 잘 생각해 보세요 !

2024-10-31 01:05 UTC, donghoony commented on src/main/java/coupon/coupon/service/CouponService.java
>      }
ㅎㅎㅎ Service는 싱글톤으로 작동할 텐데, 내부에 변수를 두어도 될 지는 생각해보아야할 점이겠습니다, 상태를 가지는 순간 동시성부터 생각할 게 많아질 거니깐요

👍🏻

2024-10-31 08:10 UTC, donghoony approved these changes
뽀로로 수고했어요~ 이번 단계 요구사항은 모두 갖췄으니 머지하겠습니다. 2단계에 새로 들어오는 요구사항 잘 확인해서 구현해주세요 😉

2024-10-31 08:10 UTC, merged