[1단계 - DB 복제와 캐시] 망쵸(김주환) 미션 제출합니다.
woowacourse/java-coupon pull request #74
Opened 2024-10-18 08:55 UTC by 3Juhwan

커비, 안녕하세요! 망쵸입니다 😀

2024-10-21 01:20 UTC, skylar1220 requested changes
안녕하세요 망쵸! 리뷰어 커비입니다~
여러 방식을 고민하고 구현하면서 비교해주셨네요👍

1. 중간에 방식을 변경하였는데 이전 방식의 어떤 단점을 느껴서 현재 방식으로 변경했는지가 궁금해요~
2. 또한 해당 방식에 단점이 있다면 어떤 것이 있는지, 그럼에도 선택한 이유가 무엇인지 함께 알려주시면 좋겠어요. 단점이 있더라도 인지하고 이유가 있다면 괜찮다고 생각해서요~

2024-10-21 01:20 UTC, hyeonji1220 commented on src/main/java/coupon/config/DataSourceConfig.java
> +            @Qualifier("readerDataSource") DataSource reader) {
빈 이름을 상수로 관리해도 좋겠네요!

2024-10-21 01:20 UTC, skylar1220 commented on src/main/java/coupon/domain/Coupon.java
1. 객체를 분리하지 않은 이유가 있을까요?
2. 검증이 있는만큼 테스트가 필요할 것 같아요~

2024-10-21 01:20 UTC, skylar1220 commented on src/main/java/coupon/domain/Coupon.java
> +    private Integer minimumOrderAmount;
int가 아닌 Intger로 관리하는 이유가 궁금해요~

2024-10-21 11:45 UTC, 3Juhwan commented on src/main/java/coupon/domain/Coupon.java
> +    private Integer minimumOrderAmount;
도메인 전반에 통일성을 위해 Wrapper Type을 사용했어요. 이외에 의미는 담지 않았어요! 

int로 하면 null이 불가능한 반면에, Integer은 null이 가능해요. `discountAmount`과 `minimumOrderAmount`이 절대 null이면 안된다면 int로 하는 것이 좋을 것 같아요. 지금은 크게 제약이 없어서 Integer로 두었어요.

2024-10-21 11:46 UTC, 3Juhwan commented on src/main/java/coupon/domain/Coupon.java
검증 로직을 분리할 수도, VO로 분리할 수 있을 것 같아요. 분리를 고민하기도 했지만, 아직은 볼륨이 크지 않아서 분리하지 않았어요! 

테스트를 추가했어요~!

2024-10-21 11:58 UTC, 3Juhwan commented
커비 안녕하세요 😀 

> 중간에 방식을 변경하였는데 이전 방식의 어떤 단점을 느껴서 현재 방식으로 변경했는지가 궁금해요~

이전 방식에 단점을 느끼진 않았어요! 이전 방식이 동작하는지 구현해 보았고, 구현한 김에 커밋을 남겨보았어요. 현재 방식을 택한 건, 이것이 실제와 더 유사하다고 생각해서에요. 관리자가 쿠폰을 등록하고 조회하기까지 2초의 텀은 발생하지 않을까요? 

> 또한 해당 방식에 단점이 있다면 어떤 것이 있는지, 그럼에도 선택한 이유가 무엇인지 함께 알려주시면 좋겠어요. 단점이 있더라도 인지하고 이유가 있다면 괜찮다고 생각해서요~

현재 방식에 단점이 없을 거라 생각해서 테스트에 `Sleep()`을 걸었는데요. 생각해보니, 쿠폰을 생성하는 API에서 생성한 쿠폰 id를 반환하면서 해당 쿠폰 정보를 응답하는 api를 호출할 수 있을 것 같아요. PRG 패턴 같이요. 그럼 사용자가 클릭하지 않아도 복제 지연이 끝나기 전에 조회가 일어날 수 있겠어요. 

그래서,,, 관리자 페이지에서는 source DB를 읽도록 다시 수정했어요 😀

2024-10-22 00:15 UTC, skylar1220 approved these changes
> 생각해보니, 쿠폰을 생성하는 API에서 생성한 쿠폰 id를 반환하면서 해당 쿠폰 정보를 응답하는 api를 호출할 수 있을 것 같아요. PRG 패턴 같이요. 그럼 사용자가 클릭하지 않아도 복제 지연이 끝나기 전에 조회가 일어날 수 있겠어요.

문제를 찾았고 방식을 다시 적용한 부분이 충분히 이해가 되네요👍
더불어 요구사항을 모두 만족했다고 생각합니다~ 수고 많았습니다 다음 단계에서 봐요🚀🚀

2024-10-22 00:15 UTC, hyeonji1220 commented on src/test/java/coupon/domain/CouponTest.java
경계값과 주석으로 테스트 가독성이 정말 좋네요👍

2024-10-22 00:15 UTC, skylar1220 commented on src/main/java/coupon/config/DataSourceHelper.java
> +    }
외부에서 트랜잭션을 시작하면 내부 트랜잭션이 참여되는 속성 이용할 수 있겠군요👍

2024-10-22 00:15 UTC, merged