[2단계 - DB 복제와 캐시] 백호(전호건) 미션 제출합니다.
woowacourse/java-coupon pull request #80
Opened 2024-10-22 13:42 UTC by Arachneee

안녕하세요 애쉬~

제가 선택한 캐시전략은 다음과 같아요

1. 쿠폰 목록 조회가 많이 일어나기 때문에 쿠폰을 캐싱해둔다.
2. 캐시의 TTL은 일주일로 설정을 했습니다.  그 이유는 쿠폰의 사용기간이 일주일로 사용자가 쿠폰 등록 후 일주일동안은 조회를 자주 할 것으로 예상했습니다.
3. 로컬 캐시를 사용할 경우 여러대의 서버가 존재할 때 정합성이 맞지 않을 수 있기 때문에 별도의 캐시서버인 레디스를 운영할 수 있도록 했습니다.

TTL은 사용자의 행동패턴을 분석해서 설정하는 것이 좋을 것 같아요.

2024-10-24 02:00 UTC, ashsty requested changes
안녕하세요, 백호!
2단계 미션도 빠르게 구현해주셨네요 ☺️

아직 제가 해당 미션을 시작하지 않아 캐시에 대한 이해도가 낮기도 하고(🥲)
그 외 부분에서 크게 수정이 필요한 코드는 없을 것 같아 우선 간단한 질문만 남겨두었어요. 

데모데이 준비로 바쁘실 것 같은데 화이팅입니다~^_^

2024-10-24 02:00 UTC, ashsty commented on src/main/java/coupon/dto/MemberCouponResponse.java
> +    public static MemberCouponResponse from(MemberCoupon memberCoupon, CouponResponse couponResponse) {
정적 팩토리 메서드 네이밍을 따르신 걸까요?
`of`와 `from`은 각각 어떤 상황에서 쓰일까요?

2024-10-24 02:00 UTC, ashsty commented on src/main/java/coupon/domain/CouponCache.java
> +    public Optional<Coupon> findById(Long couponId) {
`Optional()` 👍

2024-10-24 02:00 UTC, ashsty commented on src/main/java/coupon/application/CouponService.java
> +    @Cacheable(value = "coupons", key = "#couponId")
커스텀 어노테이션과 `redis` 캐시가 함께 적용되어 있네요!

해당 메서도 `getCoupon`이 호출될 때 각 방식이 어떤 우선순위로 실행되는지,
어떤 전략을 취하고 있는지 설명해주실 수 있을까요?

2024-10-24 02:00 UTC, ashsty commented on src/main/java/coupon/config/RedisCacheConfig.java
> +    public static final Duration TTL = Duration.ofDays(7L);
캐시 TTL에 대해 조금 더 고민해보고 싶어요 🤔

캐시 서버에도 용량이 있을 텐데,
저장 기간이 일주일이라면 저장할 수 있는 캐시 한도가 너무 빠르게 차지 않을까요?

보통 권장되는 최대 TTL 길이는 하루 정도라고 하는데요.
[이 글](https://dev.acquia.com/blog/how-choose-right-cache-expiry-lifetime)을 참고해보셔도 좋을 것 같아요! ☺️

2024-10-24 10:06 UTC, Arachneee commented on src/main/java/coupon/dto/MemberCouponResponse.java
> +    public static MemberCouponResponse from(MemberCoupon memberCoupon, CouponResponse couponResponse) {
인자가 1개일때는 from 2개이상은 of를 쓰곤 하는데 from으로 잘못 작성했네요! of로 수정하겠습니다.

2024-10-24 10:14 UTC, Arachneee commented on src/main/java/coupon/application/CouponService.java
> +    @Cacheable(value = "coupons", key = "#couponId")
`@Cacheable` 어노테이션은 key에 해당하는 캐시가 존재할 때는 반환값을 캐시에서 가져옵니다.
 존재하지 않을 때는 메소드를 실행하여 응답을 캐싱해둡니다.

Redis 설정을 하지 않을 경우에는 로컬 캐시로 동작하는데 Redis를 설정할 경우 Redis cache에 캐싱합니다.

그래서 첫 조회는 레포지토리에서 읽지만 이후 요청들은 Redis에서 캐싱된 값을 읽습니다.

2024-10-24 11:00 UTC, Arachneee commented on src/main/java/coupon/config/RedisCacheConfig.java
> +    public static final Duration TTL = Duration.ofDays(7L);
쿠폰 key-value 1개의 용량은 대략 300바이트 정도 됩니다.
EC2 mirco 기준으로 메모리가 1G라고 한다면 쿠폰은 대략 357만건 (1GB/ 300B) 이 캐싱될 수 있습니다.
일주일동안 357만건의 쿠폰이 생성되지는 않을 것으로 생각하여 용량은 충분하다고 생각합니다.

쿠폰의 일반적인 발급기간이 주어진다면 해당 기간동안 캐싱을 하는 것이 효율적이라고 생각합니다.
애쉬는 TTL을 어떻게 설정하는 것이 좋다고 생각하시나요?

2024-10-24 11:06 UTC, Arachneee commented
천천히 리뷰주셔도 괜찮아요~

2024-10-30 02:12 UTC, ashsty commented on src/main/java/coupon/config/RedisCacheConfig.java
> +    public static final Duration TTL = Duration.ofDays(7L);
캐시 서버에 저장되는 게 쿠폰 정보 뿐이라면 저도 백호의 의견에 동의해요.

하지만 다른 정보들도 함께 저장되어야 하고, 해당 정보들의 크기가 크다면

- 캐싱이 필수적이고
- 자주 불리는 값들을 우선으로 저장할 것 같습니다.

저는 상품 관련 정보(사진, 상품 정보, 기타 등등...)도 캐싱된다는 가정 하에 TTL을 하루 정도로만 둬도 괜찮지 않을까 싶었어요.

근데 사실 도메인에 따라서 TTL을 한 달, 혹은 1년 단위로 잡는 경우도 있다고 하긴 하더라고요. ☺️
뭐든 정답은 없는 것 같습니다 ^__^

2024-10-30 02:13 UTC, ashsty commented
안녕하세요 백호! 늦어도 괜찮다고는 하셨지만 이렇게 늦을 줄은 모르셨겠죠...? ㅎㅎ 죄송합니다...

이번 단계 요구사항은 모두 만족한 것 같아서 이만 머지해보려고 해요!
우테코 마지막 미션 고생하셨습니다~~!

2024-10-30 02:13 UTC, merged