[2단계 - DB 복제와 캐시] 새양(양경호) 미션 제출합니다.
woowacourse/java-coupon pull request #84
Opened 2024-10-24 00:53 UTC by geoje

안녕하세요 시소!

이번 단계에서는 `Redis` 를 사용하여 캐싱을 진행해보았고, 과정 중 겪었던 문제점이나 저의 생각 그리고 해결 방안 등을 아래에 정리해 보았어요!

### 1. 회원에게 쿠폰을 발급하는 기능 구현
> 한 명의 회원은 동일한 쿠폰을 사용한 쿠폰을 포함하여 최대 5장까지 발급할 수 있다.

- 먼저, DB 에서 특정 멤버에게 발급된 특정 쿠폰 개수를 반환하는 메서드를 JPA 네이밍 메서드 `MemberCouponRepository.countByMemberIdAndCouponId(long memberId, long couponId)` 로 두었습니다.
- 주어진 요구사항은 중요한 비지니스 로직이기 때문에 이전 단계에서 구현한 ` Writer DB` 를 조회하도록 `TransactionExecutor.executeOnWriter(Supplier<T> supplier)` 메서드를 사용하여 호출하도록 하였습니다.
- 하지만 **성능 향상** 또한 캐싱으로 해결하자는 이번 단계의 요구사항인 만큼, 현재 읽으려는 값(사용자에게 발급된 특정 쿠폰 개수) 는 캐싱을 사용하려고 했습니다.
- 캐싱으로 `ConcurrentHashMap<String, Long>` 을 사용하려다, 멀티 애플리케이션 환경도 고려하여 `Redis` 를 사용하겠다 생각하였습니다.
- 조회 캐싱 전략으로는 `cache miss` 일 때, `DB` 조회 후 캐시에 저장, 이후 반환 하는 `Look Aside` 방식을 채택하였습니다.

### 2. 회원의 쿠폰 목록 조회 기능 구현
> [미션 설명](https://techcourse.woowahan.com/s/Cjiz6fNL/lt/R6TAnPXF)에 있는 것처럼 쿠폰과 회원에게 발급된 쿠폰의 저장소가 분리될 예정이므로, 두 테이블을 조인할 수 없다.
회원의 쿠폰 목록 조회 시 쿠폰, 회원에게 발급된 쿠폰의 정보를 모두 보여줄 수 있어야 한다.

- 기존에 존재하던 `MemberCoupon` 도메인에 

### 3. 쿠폰 캐싱
> 성능을 위해 쿠폰을 캐싱하고, 회원의 쿠폰 목록 조회 시 쿠폰 정보는 캐시를 통해 조회하도록 수정한다.

2024-10-28 06:05 UTC, shin-jisong requested changes
안녕하세요 새양!
제가 아직 레디스에 대한 학습을 완료하지 못해서 간단한 질문만 남기고 갈게요
전체적으로 잘 작성해 주신 것 같습니다 👍
다음 리뷰에서 좀 더 상세한 리뷰를 남길 수 있을 것 같아요!

(늦어졌는데 기다려 주셔서 감사합니다...)

2024-10-28 06:05 UTC, shin-jisong commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
여러 캐싱 전략 중 `Look Aside` 전략을 택한 이유가 궁금해요!
고려했던 다른 전략은 어떤 것이 있나요?

2024-10-28 06:05 UTC, shin-jisong commented on src/main/java/coupon/config/RedisConfig.java
> +                .entryTtl(Duration.ofMinutes(10));
현재 캐시의 TTL은 어떻게 되고 그 값을 사용하신 이유가 궁금해요!

2024-10-28 06:05 UTC, shin-jisong commented on src/test/java/coupon/service/MemberServiceTest.java
> +        CountDownLatch latch = new CountDownLatch(nThreads);
스레드에 관해서도 테스트를 해 주셨네요! 👍
CountDownLatch를 왜 쓰셨는지, 어떻게 동작하는지 궁금해요~

2024-10-29 01:03 UTC, geoje commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
우선 `Write Through` 방식과 `Write Back` 방식을 사전에 알고 있었으며, 이 2개 모두 사용해도 좋다 생각하였습니다!
하지만 조금 더 찾아본 결과, `Look Aside` 방식을 발견하게 되었고, 기존에 생각했던 방식이었지만 장점과 단점을 더욱 고려할 수 있었습니다.

- **장점:** 불필요한 캐시 사용을 줄이고, 캐시가 필요한 데이터만 유지합니다.
- **단점:** 캐시에 데이터가 없을 경우 매번 데이터베이스 조회 이후 캐시에 저장까지 해야하므로 리소스가 들긴 합니다.

하지만 해당 멤버 쿠폰을 모두 캐시에 올려놓는 것을 불필요하다고 생각하였고, `Look Aside` 가 충분히 좋다고 판단하였습니다.

2024-10-29 01:05 UTC, geoje commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
코멘트 덕분에 제가 조금 더 찾아 보니 캐시된 데이터가 만료될 때 백그라운드에서 미리 캐시를 갱신하는 `Refresh-Ahead Cache` 도 있는 것을 알게 되었어요!

추후 필요한 상황이 있을 때 이 부분도 좋을 것 같아요~

2024-10-29 06:52 UTC, geoje commented on src/main/java/coupon/config/RedisConfig.java
> +                .entryTtl(Duration.ofMinutes(10));
TTL은 기본 10분으로 두었습니다.
필요 시 특정 `Key` 마다 TTL을 변경할 수도 있더라구요! [TtlFunction](https://docs.spring.io/spring-data/redis/reference/redis/redis-cache.html#redis:support:cache-abstraction:expiration:tti)

TTL을 두지 않게 되면 제한이 있는 메모리 용량을 너무 많이 사용하여 `Memory Leak` 이 발생할 수도 있고, 무엇보다 간혹 사용되는 값의 경우 오랫 동안 유지 할 필요가 없다 라고 판단하였습니다.

10분의 선택 기준은 일반적으로 제가 느꼈을 때 평균치라고 생각하였으며, 실제 쿠폰 서비스를 만들 때에는 `Cache Hit` 과 `Cache Miss` 의 데이터를 모니터링 툴 등으로 활용하여 관리한 후 분석해서 적절한 TTL 값을 찾아야 한다고 생각합니다.

2024-10-29 06:54 UTC, geoje commented on src/test/java/coupon/service/MemberServiceTest.java
> +        CountDownLatch latch = new CountDownLatch(nThreads);
스레드의 작업을 요청하는 것은 작업 종료를 기다리지 않게 때문에 `CountDownLatch` 를 사용하여 값이 0이 될 때 까지 테스트를 수행하고 있는 메인 스레드가 대기할 수 있도록 구성하였습니다!

2024-10-29 07:46 UTC, shin-jisong requested changes
안녕하세요 새양!
잘 남겨 주셨네요 👍
아마 다음 타임에는 머지로 갈 것 같습니닷

따로 할 말이 있으시면 디엠 주세요~!

2024-10-29 07:46 UTC, shin-jisong commented on src/main/java/coupon/service/CouponService.java
> +    @CachePut(value = CACHE_KEY_COUPON, key = "#result.id")
해당 어노테이션은 뭘 의미하고 어떻게 동작하나요?
아래에 사용한 Cacheable 또한 뭘 의미하고 어떻게 동작하는지 설명해 주세요!
(AOP 기반으로 동작하는데 이것을 중심으로 공부한 내용을 정리해 보면 좋을 듯하네요!)

2024-10-29 07:46 UTC, shin-jisong commented on src/main/java/coupon/config/RedisConfig.java
> +    public ObjectMapper objectMapper() {
해당 문제를 직렬화 문제 때문에 작성해 주신 것 같은데요!
어떤 문제가 말생하였고 해결책으로 뭘 적용하였는지 설명해 주세요 👀

2024-10-29 07:46 UTC, shin-jisong commented on src/main/resources/application.yml
> +        enabled: false
이 부분을 true로 하는 것과 false로 하는 것은 어떤 차이점이 있을까요?

2024-10-30 00:47 UTC, geoje commented on src/main/java/coupon/service/CouponService.java
> +    @CachePut(value = CACHE_KEY_COUPON, key = "#result.id")
오.. 신기하네요! 해당 부분의 동작 원리를 파악하기 위해 걸어주신 메서드의 실행에 대해 디버그를 찍고 하나씩 `Step Over` 해보았어요.
`@Transactional` 에 대해서는 `AopUtils > ReflectiveMethodInvocation > CglibAopProxy > TransactionInterceptor > TransactionAspectSupport` 정도로 실행이 된 것으로 확인하였습니다!
`@CachePut` 은 `CacheInterpertor > CacheAspectSupport` 순으로 실행되는데 분석 도중 `cacheHit` 여부에 따라 동작이 달라지더군요.
AOP 를 디버깅 할 생각을 못해봤었는데 시소 덕분에 재밌는 분석을 할 수 있었습니다!!

![image](https://github.com/user-attachments/assets/7a2449b5-481f-4e3d-a964-7b6d77c4d19c)

2024-10-30 00:49 UTC, geoje commented on src/main/java/coupon/config/RedisConfig.java
> +    public ObjectMapper objectMapper() {
```java
objectMapper.registerModule(new JavaTimeModule());
objectMapper.activateDefaultTyping(
        LaissezFaireSubTypeValidator.instance,
        ObjectMapper.DefaultTyping.NON_FINAL,
        JsonTypeInfo.As.PROPERTY
);
```

부분에서 첫 줄은 `JSR 310` 을 사용하기 위해 하였고, 다음 줄은 `JSON` 변환 이후 `value `값에 `class` 타입 명까지 저장되는 문제를 값만 저장할 수 있도록 하였습니다.

2024-10-30 00:52 UTC, geoje commented on src/main/resources/application.yml
> +        enabled: false
해당 부분을 `true` 로 하면 `RedisRepository` 가 활성화 되며 스프링은 `JPA Repository` 와 함 께 `Redis Repository` 도 찾으려 할 것입니다.
그럼 해당 부분을 분리하기 위해 `SpringApplication` 쪽에 이를 분리 하며 스캔 할 수 있도록 basePackage 를 어노테이션으로 붙여줘야하는데 `RedisRepository` 는 사용하지 않을 것이고 생성해둔 `JPA Repository` 들이 `Redis Repository` 인지 스캔하는 것을 없애기 위해서입니다.

또한 이를 없애면 로그에서 찍히는 경고를 보지 않을 수 있습니다.

2024-10-30 01:04 UTC, shin-jisong approved these changes
질문에 찰떡으로 답해주시는 새양 덕분에 리뷰가 즐거웠어요~!
마지막 미션 너무 수고하셨습니다
수료까지 가까워졌어요 👊

2024-10-30 01:04 UTC, merged