[2단계 - DB 복제와 캐시] 망쵸(김주환) 미션 제출합니다.
woowacourse/java-coupon pull request #86
Opened 2024-10-24 11:33 UTC by 3Juhwan

커비, 안녕하세요. 망쵸에요 😀 
2단계를 구현했어요. 이번 미션은 캐시를 적용해서 성능 최적화하는 것인데요. 제가 구현한 사항은 다음과 같아요. 

- 날짜 관련 버그 픽스 (커밋 초반)
- Entity 객체와 Domain 객체 분리
- RedisManager와 Cachable을 사용해서 캐시 적용

캐시는 TTL 7일로 쿠폰을 조회할 때 저장하게 했어요! 만료 기간에 대해 쿠폰 자체의 만료 기한이 있다면, 그렇게 두면 좋을 것 같아요. 관련된 명확한 정책이 없어서, 만료 기간과 멤버 쿠폰의 만료 기간과 동일하게 두었어요. 멤버 쿠폰이 유효한 기간 동안은 멤버 쿠폰과 연관되어 있는 쿠폰의 조회가 빈번할 거라 생각하기 때문이에요. 메모리에 여유가 있다면 쿠폰 만료 시간을 더 늘려도 좋겠어요. 

고려할 사항으로, 쿠폰에 삭제나 업데이트가 발생하면 캐시 무효화가 필요할 것 같아요! 하지만 삭제나 업데이트 로직이 아직 없네요. 

또, 핫키가 만료되는 경우에는 데이터베이스에 접근이 폭주할 수 있어요. 이 상황을 어떻게 방지할지 고민해 보았는데요. 캐싱된 쿠폰을 재조회할 때마다 ttl 초기화, 캐시를 조회하는 스레드에 락 걸기 등을 고민하였고, `@Cachable`에 `sync`를 적용하기로 결정했어요. `sync`는 동일한 키에 접근하려고 하는 여러 스레드가 있으면 캐시 연산이 끝날 때까지 다른 스레드를 기다리게 하는 옵션이에요. 스프링이 추상화를 잘해둔 덕분에 캐시를 적용하기 편하네요 😀 

코드 리뷰 잘 부탁드려요!

2024-10-24 11:41 UTC, 3Juhwan commented on build.gradle
> +    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
LocalDateTime이 역직렬화가 되지 않아서 추가했어요 :)

2024-10-30 12:07 UTC, skylar1220 requested changes
안녕하세요 망쵸!
정말 늦은 리뷰 죄송합니다😂
고민을 많이 한 게 느껴지는 코드였습니다! ttl까지 함께 고려해주어서 저도 생각해볼 수 있어 좋았어요!
질문 몇가지 남겼으니 함께 이야기 나눠봐요!

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/domain/Coupon.java
> +@EqualsAndHashCode(of = "id")
id 기반 동등성이라면 id가 지정되기 전의 coupon 객체는 모두 동등한 객체로 간주되지 않을까요? id 기반 동등성이 필요한 이유가 궁금해요!
```java
// 둘은 같은 객체인가?
new Coupon("망쵸 쿠폰1", discountAmount, minimumOrderAmount)
new Coupon("망쵸 쿠폰2", discountAmount, minimumOrderAmount)
```

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/domain/MemberCoupon.java
> +                .truncatedTo(ChronoUnit.MICROS);
쿠폰 만료 기한은 비즈니스적인 속성이라고 생각했는데 도메인에서 관리하는 점이 특이했어요!
혹시 이유가 있을까요?

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/service/MemberCouponService.java
> +        MemberCoupon memberCoupon = MemberCoupon.issue(member, coupon);
위의 비즈니스적인 속성 - 도메인 속성과 비슷한 맥락으로, 발급을 위한 검증은 서비스에서 하고, 발급 로직은 도메인 안에 있는 것이 눈에 들어왔어요! 둘 다 회원 쿠폰 발급과 관련된 로직인데 어떤 기준으로 나뉘어져있는건지 궁금합니다~

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/service/MemberCouponService.java
> +    public List<MemberCoupon> findAllByMember(Member member) {
테스트에서만 사용되고 있는데 어떤 역할인지 궁금합니다~

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/service/support/CacheService.java
> +public class CacheService {
couponRepository의 메서드들에 @Cacheable을 바로 적용해도 되는데 따로 CacheService를 뺀 이유가 궁금해요!

2024-10-30 12:07 UTC, hyeonji1220 commented on src/test/java/coupon/service/support/CacheServiceTest.java
> +    }
👍캐시를 어떻게 테스트하나 했는데 db를 비우고 조회하는 방식 재밌네요!

2024-10-30 12:07 UTC, hyeonji1220 commented on src/main/java/coupon/config/CacheConfig.java
> +    }
cacheConfig와 redisConfig에 각각 역할을 나눈 기준이 궁금해요~
redisCache의 TTL을 정하는 일은 cache 범용적인 설정이라기 보단 Redis의 설정이라는 생각이 들어서요!

2024-10-30 12:07 UTC, skylar1220 commented on src/main/java/coupon/config/RedisConfig.java
여러 캐싱 구현 중에 Redis를 사용한 이유가 궁금해요!

2024-11-01 06:04 UTC, 3Juhwan commented on src/main/java/coupon/domain/Coupon.java
> +@EqualsAndHashCode(of = "id")
맞아요! id가 null인 서로 다른 객체에 대하여 동등성 비교는 true가 반환돼요. equals 재정의로 좀더 세밀하게 동등성 비교한다면 좋을 것 같아요. id가 null인 경우에 equals는 false를 반환하는 식으로요! 

다만, 엔티티 객체이기에 식별자 역할의 id필드로 동등성 비교하는 것이 명확하다고 생각했어요. 그리고 대부분의 상황에서 애플리케이션 코드에서는 영속화된 객체를 대상으로 비교할테고 id가 할당되지 않는 경우는 없다고 생각해요.

2024-11-01 06:19 UTC, 3Juhwan commented on src/main/java/coupon/service/MemberCouponService.java
> +    public List<MemberCoupon> findAllByMember(Member member) {
코드를 빈번하게 수정하며 포함되었네요! 해당 메서드와 관련 테스트 삭제했어요 :)

2024-11-01 06:27 UTC, 3Juhwan commented on src/main/java/coupon/service/support/CacheService.java
> +public class CacheService {
아 맞아요! couponRepository에 바로 적용해도 되는데, 조금의 확장성을 고려했어요. 

Repository 메서드에 `@Cacheable` 적용하면 해당 메서드는 항상 캐싱을 시도할거에요. 만약 캐싱이 필요하지 않는 다른 서비스에서 해당 메서드를 사용하면 의도치 않게 캐싱을 사용하게 돼요. 캐싱을 사용하지도 모르게 사용할 수 있는 거죠!

2024-11-01 06:36 UTC, 3Juhwan commented on src/main/java/coupon/config/CacheConfig.java
> +    }
레디스는 저장소이고, 캐시는 임시 저장소로 역할을 두었어요. 그래서 캐시의 TTL은 cacheConfig에서 설정하는 것이 좋다고 생각했어요. 

이런 의도였는데 yml에는 redis cache의 ttl을 설정해두었네요 😓 RedisCache가 아닌 Cache의 ttl을 설정하거나, 아니면 Redis로 통합하는 것이 좋다고 생각해요. RedisConfig에서 ttl을 설정하게 수정했어요.

2024-11-01 06:40 UTC, 3Juhwan commented on src/main/java/coupon/config/RedisConfig.java
오... 깊게 생각하지 않는 부분인데, 질문 감사해요 :)

일단, 미션에 Redis가 주어져서 자연스럽게 사용했어요. 다른 대안으로 인메모리 캐시를 고려했었는데요. 서버가 다중화된 상황에서는 유효하지 않은 방법이에요. 

근데 만약 실제 애플리케이션을 만든다면 Redis보다는 mysql 의 named lock을 사용할 것 같아요. 이미 Mysql 을 사용하기에 추가 장비 도입과 유지보수 없이 동시성 문제를 해결할 수 있으니깐요.

2024-11-01 06:46 UTC, 3Juhwan commented on src/main/java/coupon/domain/MemberCoupon.java
> +                .truncatedTo(ChronoUnit.MICROS);
저도 이 부분 고민해 보았고, 도메인에서 관리하는 것이 응집도를 높인다고 결론을 내렸어요! 

고민해 보았는데, 비지니스적인 속성 같기도, 도메인 속성 같기도, 해요. 제가 느끼기에는 뭔가 명확하지 않은 느낌이 들어요. 비지니스 속성이라는 명확한 근거가 떠오르지 않는데, 커비의 생각을 공유해 주면 감사할 것 같아요! 

도메인에 둔 이유는 위에 언급한 대로 응집도 측면에서에요. 2개 이상의 서비스에서 쿠폰 만료 기한이 필요하다면 서비스마다 정의해 두어야 해요. 관리 지점이 늘어나면서 에러를 발생하기 취약한 코드라 생각해요.

2024-11-01 06:47 UTC, 3Juhwan commented on src/main/java/coupon/service/MemberCouponService.java
> +        MemberCoupon memberCoupon = MemberCoupon.issue(member, coupon);
이 부분이 통일성이 부족했네요! 위 코멘트에 언급한 근거대로 도메인 내부로 옮겼어요 :)

2024-11-01 07:19 UTC, skylar1220 commented on src/main/java/coupon/domain/MemberCoupon.java
> +                .truncatedTo(ChronoUnit.MICROS);
> 2개 이상의 서비스에서 쿠폰 만료 기한이 필요하다면

이것 역시 비즈니스 로직이라고 생각했습니다! 하지만 망초가 제시한 관리지점 문제도 충분히 이해가 가네요☺️

>  비지니스 속성이라는 명확한 근거가 떠오르지 않는데, 커비의 생각을 공유해 주면 감사할 것 같아요!

예를들어, 만약 회원쿠폰을 등록할 때 지정된 발행시간으로 등록해야한다는 이벤트나 정책이 생긴다면 도메인 내에 있는 issue 메서드를 재사용할 수 없을 것 같아요. 이런 추가 요구사항은 정책이나 이벤트적으로 생길 수 있는것, 즉 변경 가능성이 높은 부분이기에 비지니스 속성이라고 생각했고, 도메인에 있으면 변경에 대응하기 어렵다고 생각했어요!

2024-11-01 07:22 UTC, skylar1220 approved these changes
망쵸 마지막 미션 수고 많았어요!
다양한 방법에 대해 고민해주고 공유해주어서 제가 되려 공부가 되었어요👍👍
답코멘트 하나와 함께 머지하겠습니다!!

2024-11-01 07:22 UTC, merged