[1단계 - DB 복제와 캐시] 리브(김민주) 미션 제출합니다.
woowacourse/java-coupon pull request #9
Opened 2024-10-17 11:06 UTC by Minjoo522

안녕하세요, 안나! 리브입니다.
오랜만에 1, 2 레벨처럼 처음부터 구현하면서 재밌게 했네요. 안나는 어땠나요? 😆
`복제 지연`을 어떻게 해결할까 고민했던 것들을 아래에 정리해 두었습니다! 참고해주세요. 👍

1. 반동기
	- 비동기 복제 + 동기적 확인 절차 결합한 방식
	- 복제 완료를 확인 받은 후에만 읽기 작업을 허용한다.
	- 복제 완료를 확인 받을 때까지 기다려야하기 때문에 복제까지 시간이 오래 걸리면 성능에 영향을 미칠 수 있다.
1. 쓰기 직후 일정 시간은 쓰기 DB에서 읽도록 설정
	- 일정 시간이라는 기준이 너무 애매하고 상황에 따라 읽기 DB에 복제가 되지 않은 경우도 있을 수 있다.
2. 쓰기 작업 후 복제 완료될 때까지 대기
	- 복제까지 시간이 오래 걸리면 성능에 영향을 미칠 수 있다.
3. 캐시
	- 쓰기 후 캐시에 저장하고, 복제 지연이 발생할 수 있는 짧은 시간 동안은 캐시에서 데이터를 읽는다.
	- 캐시가 만료되면 읽기 DB에서 읽게된다.
	1. 스프링에서 제공하는 기본 캐시 사용
		- 애플리케이션의 메모리 내에서 동작하는 인메모리 캐시를 사용한다.
		- 메모리 기반 캐시로 네트워크 통신할 필요가 없기 때문에 응답 시간이 빠르다.
		- 애플리케이션을 재시작하거나 다중 서버인 경우 사용할 수 없겠지만 현재는 서버가 하나이기 때문에 가장 간단하게 복제 지연을 해결할 수 있는 방법이라고 생각했다.
	2. 외부 캐시 사용(레디스 등...)
		- 캐시 서버 분리되기 때문에 다중 서버에서 데이터 공유가 쉽다.
		- 추가 리소스가 발생한다(네트워크 통신 필요)

> 결론 : 우선 내부 캐시를 통해 복제 지연을 해결하고 추후 서버가 확장되거나 대규모 트래픽을 처리해야 하는 경우 외부 캐시를 사용한다. 로 결론을 내렸었지만 미션 설명에서 `쇼핑몰의 사용자가 점점 늘어나`라고 되어있어서 다중 서버로 확장될 여지가 매우 크다(or 이미 다중 서버일 가능성이 높다)고 생각해 레디스를 적용했습니다.

+) 외부 캐시 중에서도 레디스를 사용한 이유는 다음과 같아요!
1. 스프링에서 공식적으로 지원하는 provider
2. 파티셔닝 지원
3. 트랜잭션 기능 지원

2024-10-18 11:45 UTC, Mingyum-Kim requested changes
안녕하세요 리브 😺
리뷰어 안나입니다.

잘 구현해주셨어요! 저는 떠올리지 못했는데 캐시를 사용해서 복제 지연에 의한 문제를 해결하신 점이 인상 깊어요. 
캐시 사용이 어떻게 보면 복제용 DB가 한 개 더 생기는 느낌이 드는데, 캐시 역시 복제 지연이 생길 가능성은 없을까요? 복제 지연이 어떤 상황에서 발생하는 지 설명해주시면 캐시 사용이 더 납득될 것 같아요 😀
추가적으로 레디스에서 캐시가 만료되면 데이터가 완전히 삭제되는 건지도 궁금해요. 

다음 리뷰 때 뵐게요 리브 👨‍💻 !!

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    }
여기서 `type(HikariDataSource.class)`를 설정한 이유가 무엇일까요?

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    ) {
`@Qualifier`로 빈 이름을 사용해 파라미터 주입이 되고 있는 상황에서도 `@DependsOn`을 사용해야하나요? 😀

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    @Primary
`@Primary`는 여기서 어떤 역할을 해주나요?

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceRouter.java
> +        return DataSourceType.WRITER;
여기서 반환한 DataSource는 어떻게 사용되어 데이터베이스 연결을 담당할까요?

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceRouter.java
> +    protected Object determineCurrentLookupKey() {
LookupKey라고 이름을 지은 이유가 있나요?

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
`@Cacheable`과 `@CachePut`의 key는 무슨 역할을 하나요? `id`와 `coupon.id`를 지정한 기준이 궁금합니다 😀

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/RedisCacheConfig.java
> +}
1. Object 하위 타입으로 제한한다.
2. 직렬화를 수행할 Serializer를 생성한다.
3. Key의 경우 `StringRedisSerializer()`를 사용하고 Value의 경우 `redisSerializer`를 사용한다.

정도를 설정하신 것 같네요.

> 쓰기 후 캐시에 저장하고, 복제 지연이 발생할 수 있는 짧은 시간 동안은 캐시에서 데이터를 읽는다.
> 캐시가 만료되면 읽기 DB에서 읽게된다.

라고 적어주셨는데, 레디스를 사용해서 해당 비즈니스 요구사항이 어떻게 구현되고 있는 건지 궁금해요. 이 역할은 `CacheManager`가 하는 것이 아닌가요?

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final BigDecimal DISCOUNT_UNIT = BigDecimal.valueOf(500);
오 BigDecimal이라는 타입을 사용해주셨네요 😀 선택 이유가 궁금합니다!

2024-10-18 11:45 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/RedisCacheConfig.java
> +                .entryTtl(Duration.ofMinutes(30))
30분을 저장 기간으로 설정한 이유가 있나요?

2024-10-19 07:04 UTC, Minjoo522 commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    ) {
`@Qualifier`를 사용하면 특정 빈을 주입받을 수 있지만, 그 빈이 언제 초기화되는지 보장하지는 않습니다.
하지만 `@DependsOn`을 사용하면 해당 빈이 항상 먼저 초기화되도록 보장할 수 있습니다.

writer와, read의 데이터 소스가 같은 `DataSource`라는 타입을 갖고 있기 때문에 @Qualifier로 원하는 데이터 소스를 주입받을 수 있게 명시했습니다. 그리고 `routeDataSource`는 `writeDataSource`, `readDataSource`에 의존성을 갖고 있기 때문에 `writeDataSource`, `readDataSource`가 먼저 초기화되고 `routeDataSource`가 초기화되기를 원해서 `@DependsOn`을 사용했습니다!

2024-10-19 07:10 UTC, Minjoo522 commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    @Primary
`@Primary`는 스프링 컨테이너 내에서 같은 타입의 빈이 여러개 존재할 때, 특정 빈을 기본으로 선택하도록 지정해줍니다.
지연 로딩을 위해 `LazyConnectionDataSourceProxy` 안에 `routeDataSource`를 감싸서 실행되어야 하기 때문에 `DataSource`를 호출할 때 기본으로 선택되도록 `@Primary`를 사용했습니다.

2024-10-19 07:39 UTC, Minjoo522 commented on src/main/java/coupon/infra/DataSourceRouter.java
> +    protected Object determineCurrentLookupKey() {
`AbstractRoutingDataSource`에 정의되어 있는 `determineCurrentLookupKey` 메서드를 오버라이드 한거라 왜 그런 이름을 지었을지 정확하게는 모르겠지만 `LookupKey`라는 네이밍이 데이터 소스 라우팅 패턴에서 일반적으로 사용되는 용어라고 합니다.

2024-10-21 05:56 UTC, Minjoo522 commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    }
<img width="672" alt="image" src="https://github.com/user-attachments/assets/12aff912-0daf-4c58-9604-925b4dd94f5b">

type을 지정하지 않으면 위 네가지 데이터베이스 커넥션 풀 중 첫 번째로 가능한 풀을 선택합니다. 물론 Hikari를 우선적으로 선택하게 되기 때문에 굳이 명시하지 않아도 기본적으로는 Hikari를 사용하게 됩니다.
하지만 명시하면 HikariCP 라이브러리가 프로젝트에 포함되지 않았거나, 클래스패스에 존재하지 않는 경우 예외가 발생합니다. `HikariCP를 사용해야 한다`는 의도를 명확히 표현하고, HikariCP가 프로젝트에 추가되지 않은 경우 문제가 발생할 수 있다는 사실을 명확히 알려줄 수 있습니다.

2024-10-21 06:06 UTC, Minjoo522 commented on src/main/java/coupon/infra/DataSourceRouter.java
> +        return DataSourceType.WRITER;
`determineCurrentLookupKey `에서는 읽기 전용 (`@Transactional(readOnly = true)`)일 때 `READER`를 반환하고, 아니면 `WRITER`를 반환합니다.

그리고 `DataSourceConfig` 클래스에서 데이터 소스 설정을 하는데 이 때 커스텀한 `DataSourceRouter`를 생성한 뒤 `setTargetDataSources` 메서드를 통해 라우터에서 리턴하는 값에 따라 어떤 데이터 소스를 사용할지 지정합니다.

```java
    @Bean
    @DependsOn({WRITE_DATA_SOURCE, READ_DATA_SOURCE})
    public DataSource routeDataSource(
            @Qualifier(WRITE_DATA_SOURCE) DataSource writeDataSource,
            @Qualifier(READ_DATA_SOURCE) DataSource readDataSource
    ) {
        DataSourceRouter dataSourceRouter = new DataSourceRouter();
        Map<Object, Object> dataSourceMap = Map.of(
                DataSourceType.WRITER, writeDataSource,
                DataSourceType.READER, readDataSource
        );
        dataSourceRouter.setTargetDataSources(dataSourceMap);
        dataSourceRouter.setDefaultTargetDataSource(writeDataSource);

        return dataSourceRouter;
    }
``


트랜잭션이 시작될 때, determineCurrentLookupKey()가 호출되고 트랜잭션이 읽기 전용이면 READER, 아니면 WRITER 키가 반환됩니다. DataSourceRouter는 반환된 키(READER 또는 WRITER)에 따라 설정된 데이터 소스 맵에서 적절한 데이터 소스를 선택해 사용합니다. 😊

2024-10-21 06:13 UTC, Minjoo522 commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
`@Cacheable`과 `@CachePut`의 key는 캐시의 항목을 식별하기 위해 사용되는 캐시 키를 지정합니다.
즉, `@Cacheable`의 key는 캐시에서 값을 찾을 때 사용할 캐시 키이고, `@CachePut`의 key는 캐시를 업데이트할 때 사용할 캐시 키를 뜻합니다.
key를 따로 지정하지 않으면 기본값은 `""`이고 해당 메서드의 모든 파라미터가 key가 됩니다. coupon 테이블에서 유일한 값은 id이기 때문에 id로 저장하고 id로 값을 찾아오기를 원했기 때문에 파라미터로 들어온 `id`를 이용해 캐시를 조회하고 `coupon.id`를 이용해 저장하도록 지정했습니다.

`@Cacheable`에서는 메서드 파라미터가 id밖에 없기 때문에 명시하지 않아도 되겠지만, 혹시나 다른 파라미터가 추가되는 경우에도 문제없이 작동하도록 + 다른 개발자가 id를 통해서 캐시를 조회한 다는 것을 바로 알 수 있도록 명시했습니다.

2024-10-21 06:35 UTC, Minjoo522 commented on src/main/java/coupon/infra/RedisCacheConfig.java
> +}
`allowIfSubType ` 설정은 `Object`의 하위 타입인 모든 클래스에 대해 직렬화를 허용하는 설정입니다. `Object`의 모든 서브 타입이 직렬화 및 역직렬화 과정에서 문제 없이 처리 될 수 있도록 추가했습니다.

```java
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.activateDefaultTyping(typeValidator, ObjectMapper.DefaultTyping.NON_FINAL);
        GenericJackson2JsonRedisSerializer redisSerializer = new GenericJackson2JsonRedisSerializer(objectMapper);
```
이 부분은 JSON으로 직렬화 할 때 Jackson에서 Java의 LocalDateTime과 같은 Java 8 날짜 및 시간 API 직렬화를 지원하지 않기 때문에 추가로 설정했습니다. 해당하는 컬럼에 대해서 엔티티의 필드에 `@JsonSerialize(using = LocalDateTimeSerializer.class)` 이런식으로 설정해주어도 되지만 전부 설정하기 번거롭기도하고 놓치게될 가능성도 있어서 전역적으로 설정했습니다.

```java
                .serializeKeysWith(RedisSerializationContext.SerializationPair.fromSerializer(new StringRedisSerializer()))
                .serializeValuesWith(RedisSerializationContext.SerializationPair.fromSerializer(redisSerializer))
```
이 부분은 레디스의 직렬화 방법을 설정하는 부분입니다. Jackson을 사용하지 않으면 바이트 형태로 직렬화되는데 사람이 읽기 어렵고 크기가 큽니다.  사람이 읽기 쉬운 JSON 형태로 저장하는 것을 원해서 값을 JSON으로 직렬화 했습니다. 하지만 key의 경우 단일 값이기 때문에 JSON으로 직렬화가 안되기도 하고 그럴 필요도 없어서 String으로 직렬화 했습니다.

그리고 이 클래스의 설정은 기본적인 `CacheManager`를 레디스로 지정하는 설정입니다!

```java
    @Transactional(readOnly = true)
    @Cacheable(value = COUPON_CACHE_NAME, key = "#id")
    public Coupon getCoupon(Long id) {
        return couponRepository.findById(id)
                .orElseThrow(() -> new CouponException(ExceptionType.COUPON_NOT_FOUND));
    }

    @CachePut(value = COUPON_CACHE_NAME, key = "#coupon.id")
    public Coupon create(Coupon coupon) {
        return couponRepository.save(coupon);
    }
```
그래서 `CouponService`에서 `@Cacheable(캐시에서 읽어오기)`와 `@CachePut(캐시에 저장하기)` 어노테이션만 설정하면 `쓰기 후 캐시에 저장하고, 복제 지연이 발생할 수 있는 짧은 시간 동안은 캐시에서 데이터를 읽는다. 캐시가 만료되면 읽기 DB에서 읽게된다.` -> 이 요구사항을 구현할 수 있습니다.

`@Cacheable`이 메서드를 실행하기 전에 캐시를 먼저 조회하고 없으면 메서드를 실행하고, `@CachePut`이 메서드를 실행하고 캐시에 저장하기 때문입니다!

2024-10-21 14:32 UTC, Minjoo522 commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final BigDecimal DISCOUNT_UNIT = BigDecimal.valueOf(500);
다뤄야하는 데이터가 금액과 관련된 데이터이고 금액은 정밀한 계산을 필요로하기 때문에 `BigDecimal`을 선택했습니다.
사실 요구조건 상으로만 생각하면 BigDecimal까지 필요 없고 int, long도 괜찮지만 우선 금액이 들어오는 란이니 아무리 큰 값이어도 들어올 수 있게하고 내부에서 예외처리를 할 수 있도록 BigDecimal을 사용했습니다. int나 long을 사용하는 경우에는 값이 순환하여 다시 최소값 또는 최대값으로 돌아가는 순환적 오버플로우가 발생할 수 있기 때문에 BigDecimal을 사용하는게 좋겠다고 판단했습니다.
특히, 요구사항이 변경되어 더 큰 금액을 다루게 된다면 자료형도 바꿔야하는 번거로움을 피하고싶기도 했습니다!

2024-10-21 15:30 UTC, Minjoo522 commented
> 캐시 사용이 어떻게 보면 복제용 DB가 한 개 더 생기는 느낌이 드는데, 캐시 역시 복제 지연이 생길 가능성은 없을까요? 복제 지연이 어떤 상황에서 발생하는 지 설명해주시면 캐시 사용이 더 납득될 것 같아요 😀 
추가적으로 레디스에서 캐시가 만료되면 데이터가 완전히 삭제되는 건지도 궁금해요.

캐시 사용이 복제 DB와 비슷하게 느껴질 수 있지만, 복제 지연과 캐시의 동작 원리는 조금 달라요. 복제 지연은 source(writer)-replica(reader) 구조의 데이터베이스에서 발생하는데, writer DB에 쓰기가 완료된 데이터가 reader DB에 동기화되는 시간이 지연될 때 나타납니다.

캐시는 메서드가 실행되면서 바로 데이터를 캐시에 저장하기 때문에, 복제 지연처럼 동기화가 늦어질 가능성은 거의 없다고 생각해요. 캐시는 데이터베이스와 직접적인 동기화를 하는게 아니라 메서드가 호출될 때 캐시를 갱신하는 방식으로 작동합니다. 제 코드에서는 `@CachePut`어노테이션이 붙은 메서드를 호출하면 캐시가 저장됩니다. 😊

레디스에서 캐시가 만료되면 그 데이터는 만료 시간이 지나면 자동으로 삭제되고 삭제된 이후에 다시 캐시에 접근하려고 하면, 원본 DB에서 데이터를 다시 가져와 캐시에 저장합니다.

2024-10-23 14:16 UTC, Minjoo522 commented on src/main/java/coupon/infra/RedisCacheConfig.java
> +                .entryTtl(Duration.ofMinutes(30))
사실 별 생각이 없었고... 일단 30분이면 복제 지연은 막을 수 있겠다는 생각이었어요 ㅋㅋㅋㅋㅋㅋㅋ
복제 지연이 1분 정도 일어나기 때문에 짧은 시간만 캐싱해두고 있어도 괜찮긴하지만 캐싱되어 있는 동안은 빠른 조회가 가능하기 때문에 그 장점을 굳이 가져가지 않을 필요는 없다고 생각했어요 😅

2024-10-25 13:34 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    }
네 맞아요! 제가 궁금했던 점은, `@ConfigurationProperties` 을 사용해서 writer의 type을 지정해주고 있음에도 애플리케이션에서 한 번 더 지정할 필요가 있는 지에 대한 의문이었습니다. 😀

![image](https://github.com/user-attachments/assets/655e5fe5-e091-4537-b289-1d7b1f4df478)

2024-10-25 13:39 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    ) {
오 그렇군요 👍👍 `@DependsOn`의 쓰임을 잘 몰랐는데 설명해주시니 이해가 잘 가네요. 
그럼 빈 이름과 필드 명 (writeDataSource, readDataSource) 이 같음에도 불구하고 `@Qualifer`를 작성한 이유는 휴먼 에러 방지를 위함인가요?

2024-10-25 13:41 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceConfig.java
> +    @Primary
오 그렇군요 ! 꼼꼼한 처리가 인상 깊습니다. 
궁금한 것은, dataSource 빈 주입하는 메서드가 이것 하나뿐인 것 같은데 `@Primary`를 작성한 것 역시 휴먼 에러 방지를 위함인가요?

2024-10-25 13:53 UTC, Mingyum-Kim commented on src/main/java/coupon/infra/DataSourceRouter.java
> +        return DataSourceType.WRITER;
오 상세한 설명 감사합니다 😀
추가적으로 writer DB를 default datasource로 지정하신 이유가 있을까요?

2024-10-25 14:01 UTC, Mingyum-Kim commented on src/main/java/coupon/application/coupon/CouponService.java
> +    }
아, 메서드 파라미터로 사용된 변수가 사용 기준이 되는 거군요! 이해했습니다. 그럼 `@Cacheable`과 `@CachePut`만 지정하면 자동으로 조회 결과를, 생성 객체를 캐싱하는 것인가요? 
그리고 만약 `@Cacheable`에 의해 지정한 조회 결과가 캐시에 없으면 어떻게 동작하는 지 궁금합니다. 😀

2024-10-25 14:03 UTC, Mingyum-Kim commented on src/main/java/coupon/domain/coupon/DiscountAmount.java
> +    private static final BigDecimal DISCOUNT_UNIT = BigDecimal.valueOf(500);
굿굿 좋습니다 👍👍👍 저도 이번 미션에서 `BigDecimal`을 사용해봤는데 소수점에 대한 기능이 많아서 정확한 요구사항 구현에 적합하다고 판단했습니다. 
추가 요구사항까지 고려하신 점 멋져요!

2024-10-25 14:17 UTC, Mingyum-Kim commented
안녕하세요 리브! 늦어서 죄송합니다 🙇‍♀️
답변 남겨주신 것 잘 확인하였습니다.

추가로 궁금한 점에 대해 질문 남겨놓았고, 요구사항도 충분히 만족하신 것 같아요 👏👏 그러나 설정 문제 탓인지 로컬에서 테스트가 돌아가지 않아서, 이 부분만 확인된다면 바로 머지드리겠습니다.
우선 RC 남길테니, 추가적인 질문에 대해 간단히 이야기 나누고 다음 단계 진행해요.
다음 미션 일정이 있는만큼, 빠르게 피드백 드릴게요 👍👍

2024-10-25 14:20 UTC, Mingyum-Kim requested changes
안녕하세요 리브! 늦어서 죄송합니다 🙇‍♀️
답변 남겨주신 것 잘 확인하였습니다.

추가로 궁금한 점에 대해 질문 남겨놓았고, 요구사항도 충분히 만족하신 것 같아요 👏👏 그러나 설정 문제 탓인지 로컬에서 테스트가 돌아가지 않아서, 이 부분만 확인된다면 바로 머지드리겠습니다.
우선 RC 남길테니, 추가적인 질문에 대해 간단히 이야기 나누고 다음 단계 진행해요.
다음 미션 일정이 있는만큼, 빠르게 피드백 드릴게요 👍👍

2024-10-25 15:31 UTC, Mingyum-Kim approved these changes
리브 테스트 코드 잘 돌아가는 것 확인해서 이만 머지하겠습니다. 👍
남긴 질문들도 한번씩 확인해주시면 감사하겠습니다. 🙇‍♀️
다음 단계 미션도 화이팅이에요!

2024-10-25 15:31 UTC, merged