[2단계 - DB 복제와 캐시] 미아(이종미) 미션 제출합니다.
woowacourse/java-coupon pull request #95
Opened 2024-10-27 08:21 UTC by jongmee

안녕하세요 짱수! 이번 단계도 잘 부탁드립니다 🙇🏻‍♀️

저는 쿠폰을 캐싱할 때 읽기 전략은 **Look aside**, 쓰기 전략은 **Write around**로 선택했습니다. 

현재 사용자가 발급받은 쿠폰 목록을 조회할 때 쿠폰 정보를 캐시에서 조회하고 있습니다. 따라서 쿠폰 발급 기간에만 쿠폰 정보가 조회될 것이므로 쿠폰을 생성할 때마다 캐시에 저장하기 보다는 cache miss가 발생했을 때 db에서 쿠폰 정보를 조회하고, 캐시에 저장하는 것이 더 효율적이라고 생각했어요 😊 

잘부탁드려요!!

2024-10-29 08:13 UTC, zangsu requested changes
미아! 전체적으로 코드 잘 작성해 주셨네요!
캐시 전략도 적절히 잘 도입한 것 처럼 보입니다!
다만, 지금 테스트가 두개 터지고 있네요 🥲 
![image](https://github.com/user-attachments/assets/df4bf29f-115a-41b0-8139-bf15d4d4e45f)

해당 부분 확인해주세요!

2024-10-29 08:13 UTC, zangsu commented on src/main/java/coupon/domain/vo/IssuePeriod.java
> +    public boolean isInIssuePeriod(LocalDateTime issueDateTime) {
```suggestion
    public boolean isBetween(LocalDateTime issueDateTime) {
```
미아가 이미 도메인, 파라미터 이름을 직관적으로 잘 지어두어서 메서드 명을 더 간단하게 바꾸어도 잘 이해가 될 것 같아요~!

2024-10-29 08:13 UTC, zangsu commented on src/main/java/coupon/domain/MemberCoupon.java
> +    public void loadCoupon(Coupon coupon) {
일반적인 setter와 동작이 거의 동일하네요?
이름을 `setXX` 가 아닌 `loadCoupon` 으로 지은 이유가 있을까요?

2024-10-29 08:13 UTC, zangsu commented on src/main/java/coupon/service/CouponService.java
> +import coupon.utill.WriterDbReader;
👀

2024-10-29 08:13 UTC, zangsu commented on src/main/java/coupon/service/MemberCouponService.java
> +    private List<Coupon> findCouponsWithCache(Set<Long> couponIds) {
이 메서드에서 cache miss 가 발생하면 캐시를 업데이트 해 주는군요!
조금 아쉬운 점은 캐시 업데이트 로직이 조금 복잡하게 느껴지는 것인데요.
저도 잠시 코드를 끄적여보다가 말았네요 ㅎㅎ,,,

혹시나 나중에 여유가 된다면 이 부분을 각잡고 다듬어 보아도 좋을 것 같네요.
다음 리뷰에서 이 피드백은 반영하지 않아도 괜찮습니다! 편하게 생각해보세용~

2024-10-29 08:13 UTC, zangsu commented on src/test/java/coupon/service/MemberCouponServiceTest.java
> +    void issueUpTo5Coupons() {
전체적으로 테스트 꼼꼼하게 잘 작성해 주셨네요 👍

2024-10-30 05:38 UTC, jongmee commented on src/main/java/coupon/domain/MemberCoupon.java
> +    public void loadCoupon(Coupon coupon) {
MemberCoupon entity에 db 혹은 캐시에서 조회한 연관객체 Coupon을 로딩한다는 의미에서 `set`대신 `load`라는 네이밍을 사용했습니다 :)

2024-10-30 05:39 UTC, jongmee commented on src/main/java/coupon/domain/vo/IssuePeriod.java
> +    public boolean isInIssuePeriod(LocalDateTime issueDateTime) {
그렇네요! `issuePeriod.includes(issueDateTime)`도 자연스러워 보여서 `includes`로 변경해보았습니다! 👍👍

2024-10-30 05:40 UTC, jongmee commented on src/main/java/coupon/service/CouponService.java
> +import coupon.utill.WriterDbReader;
엇 오타가 😅 `util`로 수정했습니다!

2024-10-30 06:01 UTC, jongmee commented on src/main/java/coupon/service/MemberCouponService.java
> +    private List<Coupon> findCouponsWithCache(Set<Long> couponIds) {
쿼리를 줄이려고 하다보니 서비스 로직이 복잡해졌네요 🥲 좀 더 개선하고자 `CouponCacheManager`를 서비스 계층에 하나 만들어서 여기에서 캐싱 관련 로직을 다루었습니다!

2024-10-30 06:02 UTC, jongmee commented
안녕하세요 짱수! 리뷰 반영하고 코멘트 달아두었습니다 !

그리고 로컬에서 테스트 깨지는 게 재현이 안되는데 어느 지점에서 null pointer exception이 발생하는지 알 수 있을까요 ?? 🥺

2024-10-30 06:28 UTC, zangsu commented on src/main/java/coupon/domain/MemberCoupon.java
> +    public void loadCoupon(Coupon coupon) {
아하, 일차적으로 `setCoupon()` 라는 이름의 메서드는 존재하지 않으니 setter로의 사용을 막아줄 수 있겠군요.
이해했습니다~!

2024-10-30 11:28 UTC, zangsu approved these changes
미아, 바쁜 와중에 미션까지 제출 하시느라 고생 많으셨습니다!
이미 캐싱을 잘 적용해 주셨고, 캐싱 전략에 대해서도 충분히 생각해 보신 것 같아 이만 머지하겠습니다!

+)분명 NPE가 발생했었는데.. 지금은 아무리 돌려도 실행이 잘 되네요..?
문제가 터지지 않으니 일단은 넘어가도록 하겠습니다!

2024-10-30 11:28 UTC, merged